### ISSUE TITLE
在子组件中有一个v-viewer，现在父组件请求加载不同的图片资源，把数据传到子组件之后，怎么才能update到最新的图片？

### ISSUE THREAD

**Issue by sugerHub** [mirari/v-viewer#10]

**Comment by mirari** [comment]
组件还是指令形式调用？
指令形式的话组件发生变化时会自动重建viewer
组件形式时当options或者images数组发生变化时会自动重建，如果仅仅是images数组元素属性变化的话，现在可以用ref获取到viewer组件后手动执行createViewer方法

**Comment by sugerHub** [comment]
是指令形式的
![hghh](https://user-images.githubusercontent.com/9622842/34706621-caed8e14-f543-11e7-939a-e9e3e522c503.png)
如果指令放在span上的话，就每次images数组改变的时候都可以进行点击放大等操作，但是无法切换到下一张图片。

**Comment by sugerHub** [comment]
![default](https://user-images.githubusercontent.com/9622842/34706776-95e1b582-f544-11e7-896f-3ce3afc4d1c6.png)
我全局注册了之后进行使用的。

**Comment by mirari** [comment]
images数组改变是指数量上的改变还是内部元素属性的变化？
代码上没有看出问题，demo的指令式示例也是支持数组改变的，而且展现正常，参照对比一下吧。
看一下控制台输出了什么错误。
或者改成组件式调用看看，另外要检查一下实装的版本，可能是viewer.js的某几个版本不稳定。

**Comment by sugerHub** [comment]
我刚才发现，
![default](https://user-images.githubusercontent.com/9622842/34709276-8a734294-f551-11e7-8c78-78ab77b46f91.png)
每次切换之后都无法点击查看图片，但是在随意点击编辑按钮之后就可以进行查看图片了.(点击编辑不会改变界面和images)。
然后我查看了event info
发现点击编辑之后，有click事件，就可以进行点击查看大图。
![click](https://user-images.githubusercontent.com/9622842/34709521-8b807f7a-f552-11e7-8dd9-b0b1ed27813a.png)
没有点击之前是这个事件，无法点击查看大图。是不是冲突了？
![focus](https://user-images.githubusercontent.com/9622842/34709523-8c80b4da-f552-11e7-98ee-2aa0d7efc262.png)

**Comment by mirari** [comment]
应该不是这类冲突，按理说指令所在元素有任意变化的时候都会重建viewer，但看着像是重建时内部元素还没有渲染完。
从demo示例开始一步步往里加元素，逐个排查看看，
或者改成组件式调用试试吧

**Comment by sugerHub** [comment]
当子组件中再套一层子组件时，dom还没有加载完，viewer就创建了。
![default](https://user-images.githubusercontent.com/9622842/34751763-758d7820-f5e9-11e7-9c15-f17f0cbbc3fd.png)
如果把你的源码修改成这样就每次都好用了。
![update](https://user-images.githubusercontent.com/9622842/34751735-538cc320-f5e9-11e7-9b12-ca8dafee3203.png)

**Comment by mirari** [comment]
0.3.1发布了，现在指令式的viewer初始化都会在nexttick中执行
