### ISSUE TITLE
Cannot read property 'endX' of undefined

### ISSUE THREAD

**Issue by hamonCordova** [mirari/v-viewer#101]
When swipe and hold on image the error "Cannot read property 'endX' of undefined" is printed on console.

![Showing Error](https://user-images.githubusercontent.com/34840363/70081719-d5fd5700-15e7-11ea-9a47-f02a718c8442.png)

**Comment by mirari** [comment]
I'm sorry `v-viewer` is just an adapter on `vue`, and `viewer.js` was not specifically designed for mobile before, you can make a issue to [viewer.js](https://github.com/fengyuanchen/viewerjs/issues).

**Comment by hamonCordova** [comment]
Ok, i'm will make a issue on viewer.js. Thanks.
