### ISSUE TITLE
请问在查看大图时按delete快捷键删除当前图片，在不关闭查看大图窗口情况下，怎么更新视图？非常感谢

### ISSUE THREAD

**Issue by xinxiangzhene** [mirari/v-viewer#102]

**Comment by mirari** [comment]
这个需求用v-viewer有些折腾，建议使用viewerjs原生引入方式，然后在删除图片时使用viewer实例的update方法

**Comment by mirari** [comment]
直接升级到1.5.1最新版，默认配置下直接更新images数组即可更新视图，不会关闭大图查看窗口了
[https://codepen.io/mirari/pen/ZdMbOK](https://codepen.io/mirari/pen/ZdMbOK)
