### ISSUE TITLE
不能在iview  tablez组件里面的render当中使用该组件

### ISSUE THREAD

**Issue by 13615817501** [mirari/v-viewer#103]
不能在iview  tablez组件里面的render当中使用该组件
![image](https://user-images.githubusercontent.com/23720587/70421917-bcf01c80-1aa5-11ea-937a-a421fc58e36c.png)

**Comment by mirari** [comment]
试了一下没有问题
[https://codepen.io/mirari/pen/BayzLwP](https://codepen.io/mirari/pen/BayzLwP)
看看是不是render渲染的内容出错

**Comment by 13615817501** [comment]
![image](https://user-images.githubusercontent.com/23720587/72131867-70577400-33b8-11ea-8ffd-843eae127a0c.png)
按照你的写法没有任何报错，但是就是没显示

**Comment by mirari** [comment]
viewer.css引入了吗
