### ISSUE TITLE
How can I can add a custom button 

### ISSUE THREAD

**Issue by HT-Moh** [mirari/v-viewer#107]
I would like to add a custom button when near the image when it's open on modal view, or near the close button. ?

**Comment by mirari** [comment]
Customization is not supported currently, you may have to fork or make a feature request on [viewer.js](https://github.com/fengyuanchen/viewerjs)

**Comment by mirari** [comment]
You can refer to this example:
https://codepen.io/mirari/pen/GRMBrBv
