### ISSUE TITLE
如何自定义title

### ISSUE THREAD

**Issue by yi-jun** [mirari/v-viewer#108]
dependencies 版本 1.5.1
指定title: true后,  viewer-title显示的图片的url名称
如何自定义这个title?

**Comment by mirari** [comment]
默认配置下img的alt属性值就是title
也可以通过函数定制，详情查看viewer.js的文档：
[https://github.com/fengyuanchen/viewerjs#title](https://github.com/fengyuanchen/viewerjs#title)

**Comment by yi-jun** [comment]
感谢感谢, 没想到这么简单
