### ISSUE TITLE
viewer.view(index) not working

### ISSUE THREAD

**Issue by iec989** [mirari/v-viewer#11]
I've got a div element with multiple images inside.

If I do the below
`    var img = document.getElementById('imgdivid').$viewer;
      img.show();
      img.view(index);`

It always shows the first picture, while I want the _index_ one to be loaded instead.

Is there any callback in show that I can use, so I can execute the view(index) once the viewer is shown?

Any idea why is that?

**Comment by marufmax** [comment]
Having same issue. How do you get it fixed then?

**Comment by mirari** [comment]
Try this:
[https://codesandbox.io/s/relaxed-torvalds-jvv2y26ov9](https://codesandbox.io/s/relaxed-torvalds-jvv2y26ov9)

**Comment by marufmax** [comment]
Thank you but I am getting this
```
this.$refs.viewer.show is not a function
````

show method: 
```
this.$refs.viewer.show(
                [
                    "https://picsum.photos/200/200?random=" + i,
                    "https://picsum.photos/300/200?random=" + (i + 1),
                    "https://picsum.photos/250/200?random=" + (i + 2)
                ],
                i % 3
            );
```

**Comment by marufmax** [comment]
Thank you, everything is working properly now expect `inited` method is called by once of a index.
Viewer instance is called once by a particular index. if I open twitch of an index nothing is happening. `inited` event is not firing also. 

Event payload is saying (first open): 
```
payload:Array[1]
0:Unknown Component
```

**Comment by marufmax** [comment]
figured it out. i have to call `view` method to initialized the viewer.

thanks
