### ISSUE TITLE
Touch events less "agressive"

### ISSUE THREAD

**Issue by simplenotezy** [mirari/v-viewer#111]
Is it possible to make the touch events less aggressive? It's easy to switch to next image by mistake on mobile, if you're just trying to move the image a bit - it's actually impossible unless you zoom in a bit.

Otherwise good job with this package - seems like the best one out there; expect I'd love if you could also deliver a "lite" version with only the most basic features.

**Comment by mirari** [comment]
Sorry, `viewer.js` was not specifically designed for mobile before, you can make a issue to [viewer.js](https://github.com/fengyuanchen/viewerjs/issues).
`v-viewer` is just an adapter on `vue`.

In this case, you may temporarily disable image moving:
```
options: {
  movable: false
}
```

**Comment by simplenotezy** [comment]
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
