### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by chuliul** [mirari/v-viewer#114]
<div class="images" v-viewer="{movable: false}">
      <img v-for="src in images" :src="src" :key="src">
    </div>
<el-table>
<el-table-column><button type="button" @click="show">Show</button></el-table-column>
</el-table>
show(){
      this.$nextTick(() => {
                const viewer = this.$el.querySelector('.images').$viewer;
                viewer.show();
       });
}
您好，在点击按钮时，获取table当前行的图片，进行预览时，有时候会报Cannot read property 'offsetWidth' of undefined，预览弹层上只能显示缩略图无法显示大图，导致后面的所有图片显示时都会出现这种情况

**Comment by mirari** [comment]
[https://codepen.io/mirari/pen/MqYzJX](https://codepen.io/mirari/pen/MqYzJX)
最好能用在线例子复现一下场景，不然难以定位问题

**Comment by chuliul** [comment]
[https://codepen.io/chicken-dish/pen/rNVwZJQ](https://codepen.io/chicken-dish/pen/rNVwZJQ)，您好，出现的概率非常小。。大概几十次才会报一次，是我使用得不对吗？

**Comment by mirari** [comment]
无法复现啊，可以改用组件式调用试试
