### ISSUE TITLE
想把按钮变大，该怎么弄？

### ISSUE THREAD

**Issue by gujunwuxichina** [mirari/v-viewer#115]
按钮太小了，想调大点

**Comment by mirari** [comment]
```
import 'viewerjs/dist/viewer.css'
```
改成自己自定义的样式

**Comment by gujunwuxichina** [comment]
> ```
> import 'viewerjs/dist/viewer.css'
> ```
> 
> 改成自己自定义的样式

问下就是图片预览中的按钮中的+ - x这些符号怎么调大小

**Comment by mirari** [comment]
原生的css里这些图标是一个base64的sprite图，要修改大小就自己弄个更大的图替换原来的样式，同时修改宽高。
或者偷懒用scale，缺点是会糊。
[https://codepen.io/mirari/pen/mdJqwPB](https://codepen.io/mirari/pen/mdJqwPB)

**Comment by gujunwuxichina** [comment]
多谢
