### ISSUE TITLE
BUG： 当Viewer 处于ElementUI的dialog内时，输入elementUI表单无限触发viewer的更新操作，$input事件影响的

### ISSUE THREAD

**Issue by TSnowRock** [mirari/v-viewer#116]

**Comment by mirari** [comment]
不要使用指令形式，监听内部元素变化的行为可能被其他组件影响。用组件形式，这样只有images更新时才会更新viewer。

**Comment by JiaXueYan** [comment]
未使用指令模式，使用的是组件模式
![image](https://user-images.githubusercontent.com/32946543/76304279-131b6880-62fe-11ea-8ccd-1e589b109501.png)
这是一段代码 无限更新及闪烁

**Comment by JiaXueYan** [comment]
![image](https://user-images.githubusercontent.com/32946543/76304379-4100ad00-62fe-11ea-9827-7f49db3f2775.png)
每次按键输入立马触发

**Comment by mirari** [comment]
[https://codepen.io/mirari/pen/mdJpGzv](https://codepen.io/mirari/pen/mdJpGzv)
上面的代码看不全，用我的在线例子改一下看能不能复现

**Comment by JiaXueYan** [comment]
<el-dialog title="审核" :visible.sync="realVisible" :close-on-click-modal="false" width="1050px">
    <div style="display: flex">
      <div>
        <el-form ref="realForm" :model="realFormTemp" label-position="right" label-width="92px" style="width: 470px; margin: 0 auto; margin-right: 50px">
          <el-form-item label="审核结果" prop="audit">
            <el-radio-group v-model="realFormTemp.audit">
              <el-radio :label="1">通过</el-radio>
              <el-radio :label="0">不通过</el-radio>
            </el-radio-group>
          </el-form-item>
          <el-form-item label="姓名" prop="realName">
            <el-input v-model="realFormTemp.realName" placeholder="请输入姓名" show-word-limit maxlength="20" @change="changeVal" />
          </el-form-item>
          <el-form-item label="身份证号" prop="realIdCardNum">
            <el-input v-model="realFormTemp.realIdCardNum" placeholder="请输入身份证号" maxlength="18" show-word-limit @change="changeVal" />
          </el-form-item>
          <el-form-item label="审核意见" prop="cause">
            <el-row :style="isCreateCause ? `margin-bottom: 20px` : ''">
              <el-select v-model="realFormTemp.cause" style="width: 310px;margin-right: 10px;" clearable placeholder="请选择">
                <el-option v-for="item in causeOptions" :key="item.id" :label="item.content" :value="item.content" />
              </el-select>
              <el-button class="regular" icon="el-icon-plus" @click="isCreateCause = true" />
            </el-row>
            <el-row v-if="isCreateCause">
              <el-input v-model="causeText" style="width: 213px;margin-right: 10px" placeholder="添加常用原因（20字以内）" maxlength="20" show-word-limit @change="inputValCause" />
              <el-button class="regular" @click="handleSaveCause">保存</el-button>
              <el-button class="regular" @click="handleCloseCause">取消</el-button>
            </el-row>
          </el-form-item>
          <el-form-item label="联系地址" prop="address">
            <el-cascader v-model="realFormTemp.address" :options="cities" style="width: 100%" placeholder="请选择所在城市地区" @change="handleChangeAddress" />
          </el-form-item>
          <el-form-item label="详细地址" prop="detailAddress">
            <el-input v-model="realFormTemp.detailAddress" type="textarea" style="width: 100%" placeholder="请输入详细地址" maxlength="50" show-word-limit @change="changeVal" />
          </el-form-item>
        </el-form>
      </div>
      <div style="width: 600px; height: 400px; ">
        <div v-viewer>
          <template v-for="i in imageList">
            <img :key="i.id" :src="i.url" class="image">
          </template>
        </div>
        
        
        
      </div>
    </div>
    <div slot="footer" class="dialog-footer">
      <el-button type="primary" :loading="submitLoading" @click="realVisible = false">
        取消
      </el-button>
      <el-button type="primary" :loading="submitLoading" @click="onSubmitAudit('realForm')">
        确定
      </el-button>
    </div>
  </el-dialog>

**Comment by JiaXueYan** [comment]
`  <el-dialog title="审核" :visible.sync="realVisible" :close-on-click-modal="false" width="1050px">
    <div style="display: flex">
      <div>
        <el-form ref="realForm" :model="realFormTemp" label-position="right" label-width="92px" style="width: 470px; margin: 0 auto; margin-right: 50px">
          <el-form-item label="审核结果" prop="audit">
            <el-radio-group v-model="realFormTemp.audit">
              <el-radio :label="1">通过</el-radio>
              <el-radio :label="0">不通过</el-radio>
            </el-radio-group>
          </el-form-item>
          <el-form-item label="姓名" prop="realName">
            <el-input v-model="realFormTemp.realName" placeholder="请输入姓名" show-word-limit maxlength="20" @change="changeVal" />
          </el-form-item>
          <el-form-item label="身份证号" prop="realIdCardNum">
            <el-input v-model="realFormTemp.realIdCardNum" placeholder="请输入身份证号" maxlength="18" show-word-limit @change="changeVal" />
          </el-form-item>
          <el-form-item label="审核意见" prop="cause">
            <el-row :style="isCreateCause ? `margin-bottom: 20px` : ''">
              <el-select v-model="realFormTemp.cause" style="width: 310px;margin-right: 10px;" clearable placeholder="请选择">
                <el-option v-for="item in causeOptions" :key="item.id" :label="item.content" :value="item.content" />
              </el-select>
              <el-button class="regular" icon="el-icon-plus" @click="isCreateCause = true" />
            </el-row>
            <el-row v-if="isCreateCause">
              <el-input v-model="causeText" style="width: 213px;margin-right: 10px" placeholder="添加常用原因（20字以内）" maxlength="20" show-word-limit @change="inputValCause" />
              <el-button class="regular" @click="handleSaveCause">保存</el-button>
              <el-button class="regular" @click="handleCloseCause">取消</el-button>
            </el-row>
          </el-form-item>
          <el-form-item label="联系地址" prop="address">
            <el-cascader v-model="realFormTemp.address" :options="cities" style="width: 100%" placeholder="请选择所在城市地区" @change="handleChangeAddress" />
          </el-form-item>
          <el-form-item label="详细地址" prop="detailAddress">
            <el-input v-model="realFormTemp.detailAddress" type="textarea" style="width: 100%" placeholder="请输入详细地址" maxlength="50" show-word-limit @change="changeVal" />
          </el-form-item>
        </el-form>
      </div>
      <div style="width: 600px; height: 400px; ">
        <div v-viewer>
          <template v-for="i in imageList">
            <img :key="i.id" :src="i.url" class="image">
          </template>
        </div>
        
        
        
      </div>
    </div>
    <div slot="footer" class="dialog-footer">
      <el-button type="primary" :loading="submitLoading" @click="realVisible = false">
        取消
      </el-button>
      <el-button type="primary" :loading="submitLoading" @click="onSubmitAudit('realForm')">
        确定
      </el-button>
    </div>
  </el-dialog>`

**Comment by JiaXueYan** [comment]
完整代码附上
`
import Viewer from 'v-viewer'
import 'viewerjs/dist/viewer.css'
Vue.use(Viewer)

Viewer.setDefaults({
  Options: { 'inline': true, 'button': true, 'navbar': true, 'title': true, 'toolbar': true, 'tooltip': true, 'movable': true, 'zoomable': true, 'rotatable': true, 'scalable': true, 'transition': true, 'fullscreen': true, 'keyboard': true, 'url': 'data-source' }
})
`

**Comment by JiaXueYan** [comment]
指令模式没出现这种问题，组件模式不行

**Comment by mirari** [comment]
这代码没法看啊 ，抽取核心演示代码改到在线例子上吧
