### ISSUE TITLE
播放方式下，上一张下一张切换失效

### ISSUE THREAD

**Issue by 1134617484** [mirari/v-viewer#118]
请问播放方式下，上一张下一张切换失效，这个有什么好的思路没？看半天都不知道播放的逻辑怎么走的，只看到类似轮播图的方式，但是找不到播放的逻辑代码，想改都改不了

**Comment by mirari** [comment]
播放就是幻灯片播放，按配置项里的Interval间隔自动切换下一张图片，不可操作。
代码在viewer.js里
[https://github.com/fengyuanchen/viewerjs](https://github.com/fengyuanchen/viewerjs)

**Comment by 1134617484** [comment]
哦哦。大致明白了，我去看下源码。谢谢您。我看百度的图片预览有播放时切换图片，您有考虑过加这个功能吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mirari"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 下午2:14
收件人:&nbsp;"mirari/v-viewer"<v-viewer@noreply.github.com&gt;;
抄送:&nbsp;"あ生如夏花＆"<1134617484@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mirari/v-viewer] 播放方式下，上一张下一张切换失效 (#118)





 
播放就是幻灯片播放，按配置项里的Interval间隔自动切换下一张图片，不可操作。
 代码在viewer.js里
 https://github.com/fengyuanchen/viewerjs

**Comment by mirari** [comment]
这得去原作者的viewer.js里提issue了，v-viewer只是一个壳子

**Comment by 1134617484** [comment]
哦哦，好的，还是谢谢你。这个v-viewer的确帮了我很大的忙，播放我得去看源码才能想到怎么修改


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mirari"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 下午2:22
收件人:&nbsp;"mirari/v-viewer"<v-viewer@noreply.github.com&gt;;
抄送:&nbsp;"あ生如夏花＆"<1134617484@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mirari/v-viewer] 播放方式下，上一张下一张切换失效 (#118)





 
这得去原作者的viewer.js里提issue了，v-viewer只是一个壳子
