### ISSUE TITLE
iphonex上 右上角关系按钮太靠上无法点击 能让它下移点么...

### ISSUE THREAD

**Issue by Catlc** [mirari/v-viewer#120]
![WechatIMG199](https://user-images.githubusercontent.com/26428695/78210429-c251f680-74dc-11ea-9897-527e6a95fa8e.png)

**Comment by mirari** [comment]
可以自己写全局样式替换原生的样式
比如：
[https://codepen.io/mirari/pen/dyoLNgP](https://codepen.io/mirari/pen/dyoLNgP)
