### ISSUE TITLE
Production didn't include CSS

### ISSUE THREAD

**Issue by rikusen0335** [mirari/v-viewer#121]
`v-viewer.js` in plugins

```js
import Vue from 'vue'
import 'viewerjs/dist/viewer.css'
import Viewer from 'v-viewer'

Vue.use(Viewer);
```

and add the plugin to `nuxt.config.ts`

```ts
  plugins: [
    '~/plugins/v-viewer.js',
  ],
```

but css wasn't include in Production. Development include css and works fine.

**Comment by mirari** [comment]
This may be `nuxt`'s config problem, have you tried to import other css files?

**Comment by rikusen0335** [comment]
yes I did. Including css file to header is only worked.
