### ISSUE TITLE
分页

### ISSUE THREAD

**Issue by COMAC919** [mirari/v-viewer#122]
请问，如果图片过多，能进行分页展示吗？或者隐藏一部分，但是往后切换可以查看所有图片
![image](https://user-images.githubusercontent.com/58909486/78866210-8d601980-7a71-11ea-902d-1fc4c509f5c3.png)

**Comment by mirari** [comment]
这需求需要去[viewer.js](https://github.com/fengyuanchen/viewerjs)提了。
不过默认也只有当前正在看的图会被加载原图啊，出现在列表里的全部是缩略图
