### ISSUE TITLE
请问用指令形式 显示时候， 如何能打开当前指定的图片  

### ISSUE THREAD

**Issue by shenjieming** [mirari/v-viewer#125]
有一个图片List。 用指定形式 调用show 方法后， 永远显示的是 第一张图片， 而不是具体指定打开的图片

**Comment by mirari** [comment]
需要提供一下复现代码，参考[https://codepen.io/mirari/pen/PePrVq](https://codepen.io/mirari/pen/PePrVq)

**Comment by wissen1995** [comment]
> 有一个图片List。 用指定形式 调用show 方法后， 永远显示的是 第一张图片， 而不是具体指定打开的图片

需要设置options.initialViewIndex

**Comment by mirari** [comment]
initialViewIndex是viewer实例被初始化后打开的第一个索引，只在初次实例化时生效，如果你的需求是每次点击后打开指定的图片，应该用viewer.view(index)更合适
[https://github.com/fengyuanchen/viewerjs#viewindex](https://github.com/fengyuanchen/viewerjs#viewindex)

**Comment by wissen1995** [comment]
> initialViewIndex是viewer实例被初始化后的默认索引，如果你的需求是每次点击后打开指定的图片，应该用viewer.view(index)更合适
> https://github.com/fengyuanchen/viewerjs#viewindex

嗯是的，你把两种场景都列出来了👍
