### ISSUE TITLE
如何判断当前图片的index值，以及prev 和 next 点击事件

### ISSUE THREAD

**Issue by wangyong991** [mirari/v-viewer#127]
需求是点击上下一张的时候判断是否是第一张和最后一张给予提示，全屏关闭后，也要保证关闭前图片和关闭后缩略图选中的图片保持一致（也就是获取当前显示图片的index值）

**Comment by mirari** [comment]
[https://github.com/fengyuanchen/viewerjs#view-1](https://github.com/fengyuanchen/viewerjs#view-1)
监听view事件，里面有index

**Comment by wangyong991** [comment]
```
    inited(viewer){
      this.$viewer = viewer
      this.$viewer.element.addEventListener('view', function (e) {
        console.log(e.detail)
        console.log(this.viewer)
      })
    }
```
我这样些监听切换图片的时候能获取到了。我最开始想像 @inited 一样 直接在组件上使用 @view，没有效果，楼主只提供了 inited事件么。

**Comment by mirari** [comment]
也可以在options里面传入回调

之前期望解耦配置项和事件，没有提供其他事件，怕影响版本兼容。后续会加上。

**Comment by wangyong991** [comment]
ok
