### ISSUE TITLE
怎么做到点击不显示图片呢？比如有个开关控制是否点击显示大图

### ISSUE THREAD

**Issue by Catlc** [mirari/v-viewer#129]

**Comment by mirari** [comment]
隐藏用来做viewer的图片，使用其他元素来触发
参考例子：
[https://codepen.io/mirari/pen/vjjXwj](https://codepen.io/mirari/pen/vjjXwj)

**Comment by Catlc** [comment]
😂其实我问的问题跟 #125 一样 不过我这边是个二维的数组 类似一个分组的瀑布流布局 然后编辑的是时候点击图片不显示大图 刚发现 它一直没有调用我写的viewer.show() 貌似是点击图片的时候触发的 编辑模式下我写的
          this.$viewer.destroy();
          this.inited(viewer);
          this.$viewer.hidden();
阻止它弹出图片预览 ，但调用这个方法后 在点击图片就会显示最后显示的一张图 因为这个时候调用的是 viewer.show() 。数据源是二维的 有section 和 row 得计算出图片的index么 然后传进去

**Comment by Catlc** [comment]
测试用viewer.show()还是只能显示最后显示的一张，设置rebuild = true 解决了
