### ISSUE TITLE
filter 性能很差

### ISSUE THREAD

**Issue by Fournny** [mirari/v-viewer#130]
场景这样：我要实现类似QQ 微信的聊天界面图片显示 问题是 emoji 表情也是 img标签，所以我过滤了emoji图片，问题是用filter性能很差，感觉也没必要。

问：有没有可以指定<img> class 的方法？

**Comment by mirari** [comment]
按viewerjs原生的方案，目前就只有filter来过滤。
或者另外建立一个独立组件，用脚本传递图片数组并打开viewer，避免图片数组与聊天列表耦合。
参考
[https://codesandbox.io/s/v-viewer-zhezr](https://codesandbox.io/s/v-viewer-zhezr)

**Comment by Fournny** [comment]
嗯 我想到的也是这个方法，加载聊天消息的时候 用正则把正常图片处理下，点击的时候单独显示这个数组
