### ISSUE TITLE
回调函数 viewed 方法里给vue  data 赋值会闪退全屏预览

### ISSUE THREAD

**Issue by z138141855** [mirari/v-viewer#133]
![image](https://user-images.githubusercontent.com/25737102/84338778-908d9800-abcf-11ea-8e88-38bddab620a7.png)
![image](https://user-images.githubusercontent.com/25737102/84338807-a3a06800-abcf-11ea-9d6e-82cb8b098804.png)
![image](https://user-images.githubusercontent.com/25737102/84338890-d4809d00-abcf-11ea-921e-914f86100d64.png)

目的是为了在切换图片、或者第一次打开图片时添加给页面元素添加数据，会导致预览闪退，而且无法进入到@hidden事件

漏了一个东西：使用了el-tooltip 才会出现这样的情况，而且图片要双击才能放大预览

**Comment by mirari** [comment]
viewed、hidden事件是viewer.js的？这个目前不能用vue的事件监听来处理，得在options里以回调形式传入，或者从$viewer实例上执行监听。

el-tooltip有可能在切换时引起了内部元素变化，触发了v-viewer的重建动作。如果内部元素初始化后就不会变动，可以用v-viewer.static阻止元素变化监听。

双击等问题最好提供在线实例复现。viewer+element的在线例子参考：
[https://codepen.io/mirari/pen/pYeQjP](https://codepen.io/mirari/pen/pYeQjP)

**Comment by z138141855** [comment]
太棒了，v-viewer.static直接解决了我的问题，感觉楼主

**Comment by mirari** [comment]
一种做法是不要用指令形式，改用组件形式传入图片数组，只有图片数组变化时viewer实例才会刷新，这样可以避免tooltip的dom操作造成的干扰。

一种做法是仍然传入static指令，在inited事件里拿到$viewer实例，然后在图片渲染完毕后手动执行$viewer.createViewer()方法。

还有一种做法是把viewer所需的图片数组与用来点击打开viewer的小图区分开，比如[这样](https://codesandbox.io/s/v-viewer-zhezr)

**Comment by ye666** [comment]
> ![image](https://user-images.githubusercontent.com/25737102/84338778-908d9800-abcf-11ea-8e88-38bddab620a7.png)
> ![image](https://user-images.githubusercontent.com/25737102/84338807-a3a06800-abcf-11ea-9d6e-82cb8b098804.png)
> ![image](https://user-images.githubusercontent.com/25737102/84338890-d4809d00-abcf-11ea-921e-914f86100d64.png)
> 
> 目的是为了在切换图片、或者第一次打开图片时添加给页面元素添加数据，会导致预览闪退，而且无法进入到@hidden事件
> 
> 漏了一个东西：使用了el-tooltip 才会出现这样的情况，而且图片要双击才能放大预览



> ![image](https://user-images.githubusercontent.com/25737102/84338778-908d9800-abcf-11ea-8e88-38bddab620a7.png)
> ![image](https://user-images.githubusercontent.com/25737102/84338807-a3a06800-abcf-11ea-9d6e-82cb8b098804.png)
> ![image](https://user-images.githubusercontent.com/25737102/84338890-d4809d00-abcf-11ea-921e-914f86100d64.png)
> 
> 目的是为了在切换图片、或者第一次打开图片时添加给页面元素添加数据，会导致预览闪退，而且无法进入到@hidden事件
> 
> 漏了一个东西：使用了el-tooltip 才会出现这样的情况，而且图片要双击才能放大预览

我也遇到了这个问题，就是想要显示图片信息，然后图片一切换，信息跟着变换就会出现闪动

**Comment by uCloudCastle** [comment]
![微信截图_20200715103912](https://user-images.githubusercontent.com/7778471/87497108-7b50d100-c687-11ea-8717-01e135a10e39.png)
我也遇到这个问题，但我是使用组件方式引入的，可以确定centiImages在viewer显示过程中不会变化，但因为界面是定时刷新的，界面刷新时viewer就会闪退

**Comment by mirari** [comment]
> ![微信截图_20200715103912](https://user-images.githubusercontent.com/7778471/87497108-7b50d100-c687-11ea-8717-01e135a10e39.png)
> 我也遇到这个问题，但我是使用组件方式引入的，可以确定centiImages在viewer显示过程中不会变化，但因为界面是定时刷新的，界面刷新时viewer就会闪退

定时刷新做了什么操作？

**Comment by uCloudCastle** [comment]
> > ![微信截图_20200715103912](https://user-images.githubusercontent.com/7778471/87497108-7b50d100-c687-11ea-8717-01e135a10e39.png)
> > 我也遇到这个问题，但我是使用组件方式引入的，可以确定centiImages在viewer显示过程中不会变化，但因为界面是定时刷新的，界面刷新时viewer就会闪退
> 
> 定时刷新做了什么操作？

data中的变量会改变，界面上有图表，动画之类的展示。比如echart的曲线增加一项数据，viewer就消失了

**Comment by mirari** [comment]
> > > ![微信截图_20200715103912](https://user-images.githubusercontent.com/7778471/87497108-7b50d100-c687-11ea-8717-01e135a10e39.png)
> > > 我也遇到这个问题，但我是使用组件方式引入的，可以确定centiImages在viewer显示过程中不会变化，但因为界面是定时刷新的，界面刷新时viewer就会闪退
> > 
> > 
> > 定时刷新做了什么操作？
> 
> data中的变量会改变，界面上有图表，动画之类的展示。比如echart的曲线增加一项数据，viewer就消失了

我在本地尝试了定时修改data其他数据，无法复现啊。把页面精简下再排查是哪里操作了centiImages变量。
即使数据完全一致，对数组的赋值操作也会导致viewer重建
