### ISSUE TITLE
重新下了包之后发现图片无法打开

### ISSUE THREAD

**Issue by 747497456** [mirari/v-viewer#134]
![image](https://user-images.githubusercontent.com/24621758/86325748-2ec2ca00-bc73-11ea-864e-16e51301d63f.png)
![image](https://user-images.githubusercontent.com/24621758/86325764-397d5f00-bc73-11ea-9e7b-85414a9f5d32.png)
以前一直是正常使用的，这两天重新下了一遍包就失效，经排查是这个月viewerjs更新的版本导致的问题，用1.3.4的viewerjs版本就能正常打开
请问能解决一下问题或者在package.json里固定一下viewerjs的版本号吗

**Comment by mirari** [comment]
错误提示是什么？我试了下viewerjs更新到1.6.1没有问题啊

**Comment by 747497456** [comment]
没有错误提示

**Comment by 747497456** [comment]
![image](https://user-images.githubusercontent.com/24621758/86328097-d8578a80-bc76-11ea-8db3-8293cb451d6d.png)
原来设置的版本是这个

**Comment by 747497456** [comment]
"v-viewer": "^1.4.0",
"viewerjs": "^1.3.6",

**Comment by mirari** [comment]
只需要引入v-viewer就行了，不用手动再引一次viewerjs

**Comment by 747497456** [comment]
好我试试

**Comment by 747497456** [comment]
![image](https://user-images.githubusercontent.com/24621758/86331420-aa287980-bc7b-11ea-8bd4-408cc223c224.png)
还是一样 这是我输出的console image是空的

**Comment by 747497456** [comment]
![image](https://user-images.githubusercontent.com/24621758/86331513-c9270b80-bc7b-11ea-8bca-d83f82a4e96a.png)
但我viewer里是有绑定照片的

**Comment by 747497456** [comment]
![image](https://user-images.githubusercontent.com/24621758/86331654-f7a4e680-bc7b-11ea-9b90-def53d1c185a.png)
但我是有绑定照片的

**Comment by mirari** [comment]
包管理用的是npm还是yarn？看看v-viewer和viewerjs的实际版本是什么。
img属性是初始就有值的还是之后赋值上去的？

**Comment by 747497456** [comment]
包管理用的npm 下包用的cnpm
实际版本
![image](https://user-images.githubusercontent.com/24621758/86334652-16a57780-bc80-11ea-911f-e1452e45e34c.png)
![image](https://user-images.githubusercontent.com/24621758/86334674-1e651c00-bc80-11ea-8c45-5e882025bfaa.png)
img属性我用的v-if 绑定的图片数组有长度才为true，不过可以覆盖修改

**Comment by 747497456** [comment]
viewerjs 1.6.1
v-viewer 1.5.1

**Comment by mirari** [comment]
我在本地跑的这两个版本还是无法复现，感觉不是版本的问题

**Comment by 747497456** [comment]
不好意思 搞错了 刚重新排了一遍 发现是
![image](https://user-images.githubusercontent.com/24621758/86338343-cda3f200-bc84-11ea-9d1d-044851a0b69c.png)
这句话出了问题

**Comment by 747497456** [comment]
把这个设置去掉就能正常使用，加上的话就不行

**Comment by 747497456** [comment]
是不是这个属性和新版本的viewerjs冲突啦

**Comment by mirari** [comment]
是新版本viewerjs的一项改进，如果img元素没有`url`指定的属性，就会被忽略，因为那样会展现出无法显示的图片

**Comment by 747497456** [comment]
emm所以说这个属性就是废掉了嘛 不好意思辛苦大佬了 感谢解惑！

**Comment by mirari** [comment]
是根据需要配置的，如果小图和大图用的是同一张，就不配置，url的默认值是src。如果要区分缩略图和原始图，就在img元素上给src配置缩略图，给url指定的属性配置原始图
