### ISSUE TITLE
删除其中一张照片后会自动显示 前一张照片，怎么能让它自动到下一张照片？

### ISSUE THREAD

**Issue by cnhuye** [mirari/v-viewer#137]
删除当前浏览的图片后，它会自动显示前一张照片。
有没有办法让它自动显示下一张照片？

已经尝试了 以下代码手动控制，但无法像期望中那样正常工作:

````
...
this.images.split(this.index,1)
// 连续删除的话， 下边这两行代码都会随机性的不起作用, 仍然跳转到前一张照片
this.$viewer.view(this.index)
-- or --
this.$viewer.next()
...
````

**Comment by mirari** [comment]
images修改之后，实际的渲染还没有开始，需要等待viewer重建完成，在inited事件里重新获得$viewer对象，再进行后续操作

**Comment by cnhuye** [comment]
非常感谢，解决了我的问题。

> images修改之后，实际的渲染还没有开始，需要等待viewer重建完成，在inited事件里重新获得$viewer对象，再进行后续操作。
> 
> 有个不太优雅的写法是:
> 
> ```
>   this.$nextTick(() => {
>     this.$nextTick(() => {
>       this.$viewer.next()
>     })
>   })
> ```
> 
> 套两层，因为viewer重建是在第一个nextTick之后。
