### ISSUE TITLE
Re render viewer when resize window

### ISSUE THREAD

**Issue by nakalissi** [mirari/v-viewer#14]
Hi,
Do you have any idea if I can re-render the viewer when I manipulate the window width. I've tried to re-assign the options with a dynamic minWidth param but it doesn't work.
I appreciate with some could help me out with this issue.
Regards,

**Comment by mirari** [comment]
You can use the `createViewer` method to destroy and re-create viewer instance.
Component:
```
<viewer ref="viewerA">
```
```
function onResize () {
  this.$refs['viewerA'].createViewer()
}
```

**Comment by nakalissi** [comment]
Great! It works, I've forgot to declare the viewer component inside my own component, I'm using the Vue.use instead. Do you know the difference between them? Thank you

**Comment by mirari** [comment]
`Vue.use` register both the global component and directive.

The install method:
```
  install (Vue, {name = 'viewer', debug = false, defaultOptions} = {}) {
    Viewer.setDefaults(defaultOptions)

    Vue.component(name, extend(Component, { name }))
    Vue.use(directive, {name, debug})
  },
```
