### ISSUE TITLE
Drawing on top of the images 

### ISSUE THREAD

**Issue by askari12** [mirari/v-viewer#142]
Hello, I'm using your viewer for a project. I need to be able to draw boxes on top of the images, I was trying to embed an html5 canvas on top of the image but that didn't work properly. Can you help me on how to draw on top of images ?

**Comment by mirari** [comment]
Is this what you mean?
[https://codepen.io/mirari/pen/pobbdoE](https://codepen.io/mirari/pen/pobbdoE)

**Comment by askari12** [comment]
Hi @mirari :) Not quite exactly. This was how I was doing it myself as well. The canvas isnt able to move the same way the image does with respect to zooming, rotating and all stuff like that. Would there be a way to have the canvas move with the images as well ? 

I would really appreciate the help ! :D

**Comment by mirari** [comment]
I'm afraid it's hard to do in the current version of `viewerjs`, you can make a feature request to `viewerjs`, change `.viewer-canvas > img` to `.viewer-canvas > div > img`
