### ISSUE TITLE
Reset state of the viewer

### ISSUE THREAD

**Issue by eduardobalbo** [mirari/v-viewer#143]
I need to reset the state of the Viewer when i reopen it. 
When i close it, i'm trying to use the `hidden()` event to trigger my function and `destroy()` the state, as documented on the _viewer.js docs_. But the method dosnt work, also i dont know if destroy is the right method to achieve what i'm trying to do.
Is there a way of reseting the state on this version?

**What i need to do:** 
After selecting any image on the viewer, when i close it and open it again, i need the viewer to go back to the first image, instead of opening on the last one i clicked.

` export default {
        data(){
            return{
                options:{
                    hidden:function(event) {
                        this.$viewer.destroy();
                    }
                }
            }
        },
`

**Comment by mirari** [comment]
You don't need to use `destroy()`, use `this.$viewer.view(0)` to show the first image.

**Comment by eduardobalbo** [comment]
Oh i see, but how would i access the method `view()` inside of the` hidden()` event? It shows me that the viewer is _undefined_ everytime i try to acess something inside the method. Because i need the "reset/first image" to be called only when I close the viewer, so when i open a new viewer it need's to have the first image selected again, to achieve this the trigger that i'm using is the `hidden()` event.

Right now this is what i'm trying to do.

Vue code:

```
    import 'viewerjs/dist/viewer.css'
    import Viewer from 'v-viewer'
    import Vue from 'vue'
    
    Vue.use(Viewer, {
        defaultOptions: {
            rotatable: false,
            scalable: false,
            zoomable: false,
            movable: false,
            inline: false,
        }
    });

    export default {
        data(){
            return{
                options:{
                    transition: true,
                    hidden(){
                        console.log(this.$viewer);
                        this.$viewer.view(0)
                    }
                }
            }
        },
```

Component call:
```

<template>
    <v-layout align-center justify-center row fill-height pa-5>
        <v-flex xs12> 
            <viewer :images="imagens" class="viewer" ref="viewer"  @inited="inited" :options="options" >
                <img v-for="(item, index) in imagens"  :alt="(item.LEGENDA == '') ?'  ':item.LEGENDA"  :src="item.IMAGEM" :key="index" class="ocultar">
            </viewer>
        </v-flex>
    </v-layout>
</template>

```

**Comment by mirari** [comment]
```
hidden: () => { 
  //...
}
```
I guess you got the `this` from wrong context.

**Comment by eduardobalbo** [comment]
I found out a way of achieving what i was trying, i needed to reset the image to the first one when i opened the viewer, so i just did this. 

```
 methods: {
            inited(viewer){
                this.$viewer = viewer
                if (this.imagens.length > 0) {
                    this.$viewer.view(0);
                }
            },  

            show(){
                this.$viewer.view(0);
            },
        },
```
But thank you for the help!
