### ISSUE TITLE
Can we have a new release to take advantage of new features in viewerjs

### ISSUE THREAD

**Issue by davbaron** [mirari/v-viewer#144]
Hello,

I recently asked the author of viewerjs to add two new events, 'play' and 'stop', which relate to the 'slide show player', versus the viewer, which only had 'show' and 'hide'.  

The author was kind enough to add those and put out a new release, 1.7.0 (and then another one, 1.7.1) near the end of September. I'm assuming we would need a new release of this library to take advantage of the new functionality, correct?

Thank you!

**Comment by mirari** [comment]
Sorry for taking so long to reply.

The dependent version of `viewerjs` in `v-viewer` is `^1.5.0`, so if you install `v-viewer` now, the actual version of `viewerjs` will be `1.7.1`.
You can check it in `yarn.lock` or `package-lock.json`.

```
viewerjs@^1.5.0:
  version "1.7.1"
  resolved "https://registry.yarnpkg.com/viewerjs/-/viewerjs-1.7.1.tgz#dba6198a6542942cd78904c780fba9fe9503a269"
  integrity sha512-OQ6zYzIgyeAO1kutwdtwhTb3OTcThVWsjUV216cb4q5vnJFpsAaVmn+cQ3PhIXXrFZ6T60TwbH0DLVJ9ijhVPg==
```

**Comment by davbaron** [comment]
Thank you for your response.  Since I already have v-viewer installed, my package-lock.json has the following within it:
"v-viewer": {
      "version": "1.5.1",
      "resolved": "https://registry.npmjs.org/v-viewer/-/v-viewer-1.5.1.tgz",
      "integrity": "sha512-Q5ICKzmYQD0qTf+hti2Lhgy6UYY2zgFr+YrN9a3yPgr7pOjYrG405Pz4+6Z6FXlhdhGysCWFJUNCI2tsIyvjWQ==",
      "requires": {
        "throttle-debounce": "^2.0.1",
        "viewerjs": "^1.5.0"
      }
    },

and:

"viewerjs": {
      "version": "1.5.0",
      "resolved": "https://registry.npmjs.org/viewerjs/-/viewerjs-1.5.0.tgz",
      "integrity": "sha512-ZiJ0vrXDvomLSY3ixaZCJtmdenomsvPPQwZKwvtXUMCiO2HHtFGoB/KqpS9QzABSeKaRLfcENp1uRYJ7l1MkYQ=="
    },

Are you suggesting that I uninstall, and then re-install your package?  Or, can/should I simply edit my package-lock.json file to what your showed in your last response?

Thank you again!

**Comment by mirari** [comment]
Yes, uninstall and re-install `v-viewer`, only modifying the `package-lock.json` file will not be effective.

**Comment by davbaron** [comment]
That worked fine, and the new events from viewerjs are now available to me.  Thank you!
