### ISSUE TITLE
更改容器

### ISSUE THREAD

**Issue by Sunny-kai** [mirari/v-viewer#145]
请问一下怎么更改展示的容器，默认是全屏

**Comment by mirari** [comment]
就用inline模式

**Comment by Sunny-kai** [comment]
我的那个容器元素默认是没有创建的，只有我点击了某个操作，才会创建，我想知道怎么在他创建后获取容器并改变，如果我是在弹框内，点击一个按钮创建一个框，并且在框内预览图片，有这个需求，求助大佬，有没有具体的实例大佬

**Comment by mirari** [comment]
可以参考这个例子
https://codesandbox.io/s/v-viewer-zhezr
把viewer设置成inline模式，套在一个弹窗组件里，点击按钮时，弹出弹窗并执行例子里的动作

**Comment by Sunny-kai** [comment]
大佬我安装实例的方式还是不行，可以加个vx或QQ问一下吗，感谢

**Comment by mirari** [comment]
https://codesandbox.io/s/v-viewer-inline-modal-p3462
弹窗例子

**Comment by Sunny-kai** [comment]
感谢大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mirari/v-viewer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 晚上6:03
收件人:&nbsp;"mirari/v-viewer"<v-viewer@noreply.github.com&gt;;
抄送:&nbsp;".Sunny🍼"<1775765534@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mirari/v-viewer] 更改容器 (#145)





 
https://codesandbox.io/s/v-viewer-inline-modal-p3462
 弹窗例子
