### ISSUE TITLE
如何监听全屏按钮的点击事件

### ISSUE THREAD

**Issue by Sunny-kai** [mirari/v-viewer#147]

**Comment by mirari** [comment]
是说按钮栏中央的那个播放按钮还是inline模式右上角那个最大化按钮？

播放按钮的话监听play事件
https://github.com/fengyuanchen/viewerjs#play-1


后者的话很遗憾viewerjs默认没提供，只能迂回自行实现或者找viewerjs作者提功能请求了

**Comment by Sunny-kai** [comment]
(⊙o⊙)嗯好哒谢谢

**Comment by Sunny-kai** [comment]
你好，我想通过点击其他按钮模拟点击inline模式右上角最大化的按钮，这个有没有对应的方法

**Comment by mirari** [comment]
拿到viewer实例后，执行viewer.full()
https://codepen.io/mirari/pen/OJRVzam

**Comment by Sunny-kai** [comment]
谢谢大佬，还有个问题因为我的图片预览器是放在弹框中的，我弹框改变大小后，发现图片预览器的容器是初始我的弹框容器大小，我想设置为百分比跟着我弹框大小改变

**Comment by mirari** [comment]
改变大小后，手动重建v-viewer
组件模式this.$refs.viewer.onChange()

或者尝试执行viewer实例的update方法

**Comment by Sunny-kai** [comment]
大佬，我调用实例的update方法会一直触发图片更新 刷新似的，大小不会变 ，onChange方法不是监听窗口的大小吗，我弹框改变大小了，容器的值一直是固定的

**Comment by mirari** [comment]
不是用inline模式的吗？inline下的图片浏览容器不就是图片列表容器？
