### ISSUE TITLE
在inline模式下，点击右上角全屏预览后点图片空白区域全屏不会消失！

### ISSUE THREAD

**Issue by lemonade-YH** [mirari/v-viewer#148]
我在inline模式下，点了右上角的全屏预览，但是在点击空白区域，这个全屏的弹框并不会消失，只能还是点击右上角图标让他消失，但是在modal模式下就可以，想问下有什么好的解决方法没？
![image](https://user-images.githubusercontent.com/39424896/99608892-c883eb80-2a49-11eb-8932-540424112378.png)

**Comment by mirari** [comment]
这是viewerjs原生的限制，恐怕只能去viewerjs提issue看作者是否愿意增加配置项了（大概率不会改）

或者自己folk viewerjs的代码，这个改动很小

**Comment by beautiful-guy** [comment]
好吧，谢谢
