### ISSUE TITLE
请问如何点击背景关闭图片预览窗口？

### ISSUE THREAD

**Issue by pylee** [mirari/v-viewer#15]
请问一下如何设置或者修改代码能够实现点击黑色背景关闭预览窗口的功能呢？现在的左上角关闭有点不好操作，谢谢。

**Comment by mirari** [comment]
点击背景关闭预览功能在全屏模式下本来就有啊

**Comment by pylee** [comment]
没有点出来呢，我试了官方LiveDemo，勾选Fullscreen，但是点击黑背景不会关闭预览啊，难道还需要怎么设置？

**Comment by mirari** [comment]
viewer.js有两种初始化模式，modal和inline。modal就是点击图片才出现viewer浏览界面，可以点击右上角X号或者点击背景关闭，inline模式始终显示viewer浏览界面，没有关闭功能。
demo里第一个例子就是modal模式。第二个例子默认是inline模式，需要点击modal按钮切换。
配置项中的fullscreen不是你所想的作用，是点击播放按钮的时候是否进入全屏浏览，不过viewer.js这个配置项现在有BUG，等后续版本修复。
