### ISSUE TITLE
作者你好， 何时可以支持vue3.0版本？

### ISSUE THREAD

**Issue by ralfsqual** [mirari/v-viewer#152]

**Comment by mirari** [comment]
还没用上vue3，有空时试试

**Comment by 1129zaj** [comment]
同问，希望能支持vue3

**Comment by ataylor32** [comment]
It doesn't work in Vue 3. I used Vue CLI to create a new Vue 3 project. I then replaced the contents of src/main.js with this:

```
import { createApp } from 'vue';
import Viewer from 'v-viewer';
import App from './App.vue';
import router from './router';
import store from './store';

createApp(App)
  .use(Viewer)
  .use(store)
  .use(router)
  .mount('#app');
```

I also replaced the contents of src/views/Home.vue with this:

```
<template>
  <div class="images" v-viewer="{movable: false}">
    <img v-for="src in images" :src="src" :key="src">
  </div>
  <button type="button" @click="show">Show</button>
</template>

<script>
export default {
  data: () => ({
    images: ['1.jpg', '2.jpg'],
  }),
  methods: {
    show() {
      const viewer = this.$el.querySelector('.images').$viewer;
      viewer.show();
    },
  },
};
</script>
```

Next, I ran `npm run serve`, opened the project in my browser, and clicked the "Show" button. This is what I saw in my console:

```
Uncaught TypeError: this.$el.querySelector is not a function
    at Proxy.show (Home.vue?bb51:15)
    at Object.onClick._cache.<computed>._cache.<computed> (Home.vue?bb51:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js?830f:333)
```

**Comment by ralfsqual** [comment]
额 我根据作者的源码直接放到vue3 vite中搞了一下。 在用了。

**Comment by ralfsqual** [comment]
主要还是viewjs库。大家自行引入吧。 
`<template>
  <div ref="el" class="img-viewer-container" :style="containerStyle">
    <div v-for="(img, idx) in images" :key="img.uid +'-' +idx" class="item" :style="itemStyle">
      <img :src="img.url" :alt="`${img.alt}`" />
    </div>
  </div>
</template>

<script>

import 'viewerjs/dist/viewer.min.css'
import {onMounted, onBeforeUnmount, ref, reactive, watch, toRaw, nextTick} from 'vue';
import Viewer from 'viewerjs';

// 基于viewerjs
export default {
  name: "ImgViewer",
  props: {
    images: {
      type: Array,
      default:[]
    },
    rebuild: {
      type: Boolean,
      default: false
    },
    immediate: {
      type: Boolean,
      default: false
    },
    options: {
      type: Object
    },
    containerStyle:{
      type:Object,
      default: ()=>({})
    },
    itemStyle: {
      type:Object,
      default: ()=>({})
    }
  },
  setup(props, {emit}) {

    const el = ref();

    let viewer;

    const create = ()=>{
      viewer = new Viewer(el.value, props.options)
      emit('ready', viewer);
    }

    const destroy = ()=>{
      viewer && viewer.destroy();
    }

    const update = ()=>{
      viewer && viewer.update();
    }

    const rebuild = ()=>{
      destroy();
      create();
    }

    const refresh = ()=> {
      props.rebuild ? rebuild() : update();
    }

    const view = (index = 0)=> {
      viewer && viewer.view(index);
    };

    watch(()=>props.images, (newVal)=> {
      nextTick(()=>{
        refresh();
        if(newVal){
          if(props.immediate){
            nextTick(()=>{
              view(0);
            });
          }
        }
      });

    }, {
      deep: true
    });

    onMounted(()=>{
      create();
      window.vmViewer = viewer;
    });

    onBeforeUnmount(()=>{
      destroy();
    });

    return {
      el,
      images: props.images,

      create,
      refresh,
      view,
      update,
    };
  }
}
</script>

<style scoped>
.img-viewer-container{
  border: 1px solid #efefef;
}

.img-viewer-container .item {
  display: inline-block;
  width: 150px;
  height: 150px;
  line-height: 150px;
  margin: 2px;
}

.img-viewer-container img{
  width: auto;
  height: auto;
  max-width: 100%;
  max-height: 100%;
  cursor: zoom-in;
}
</style>
`

**Comment by mirari** [comment]
vue3版本已发布，中文文档之后补上

https://github.com/mirari/v-viewer/tree/v3
