### ISSUE TITLE
使用v-viewer后，input无法获取焦点，无法正常输入

### ISSUE THREAD

**Issue by jilieryuyi** [mirari/v-viewer#157]
如题，去除v-viewer后，input恢复正常。这是不是哪里的事件导致的？求教下！！

**Comment by mirari** [comment]
是不是用了指令形式，内部除了图片还有input？
指令形式默认开启了内部元素变化监听，任何变化都会引起viewer重置。
改用组件形式传递图片数组来避免不必要的重置。
指令形式也可以用static来标记避免自动重置。
