### ISSUE TITLE
您好，有个非常重要的问题需要咨询您

### ISSUE THREAD

**Issue by houkongquan12138** [mirari/v-viewer#158]
您好，我现在手机上需要使用您的这个组件，但是在pc游览器上测试时，他是没有问题的，但是我在手机上时，就会变得非常卡，

需求是这样的，我有一个网页，有个图片上传，上传成功后有一个回显，这个图片回显列表使用了这个组件，

出现问题是 ，会特别的卡顿，当在 钉钉内置游浏览器里时，都直接卡退了

难道是因为我的图片列表的动态改变的，导致的原因吗

**Comment by mirari** [comment]
是指令引用还是组件引用？
先用组件试一下，只要图片数组不变，不应该有卡顿
