### ISSUE TITLE
Capture click even on rendered v-viewer image

### ISSUE THREAD

**Issue by romines** [mirari/v-viewer#16]
I am trying to capture a click event on the image element as it is rendered by v-viewer. I have tried adding template markup using scoped slots, and extending the whole component with no luck.

Ultimately I would like to record the X and Y position of the click in order to simulate 'dropping a pin' on the image.

Do you think it is possible?

Thank you for an awesome component!

**Comment by mirari** [comment]
I think you have to use `this.$el.querySelector('...')` to get the element, and then add your event  listener to the target element which is created by `viewer.js`.
This may be very troublesome but not impossible.
