### ISSUE TITLE
指令形式设置options内的toolbar按钮

### ISSUE THREAD

**Issue by xdmatirx** [mirari/v-viewer#160]
作者你好，我想隐藏toolbar中部分按钮（prev, play, next），对options内的toolbar进行设置时，会导致所有按钮均不见了
例子用的是 https://codepen.io/mirari/pen/PePrVq
仅仅修改了传给它的options 
  <div v-viewer="{toolbar : {next: false}}" class="images clearfix">
初学者想请教如何设置

**Comment by mirari** [comment]
我试了下，这好像是viewerjs的配置项取默认状态出了问题。
目前的解决办法是显式声明所有按钮的状态：
```
toolbar: {
        zoomIn: 1,
        zoomOut: 1,
        oneToOne: 1,
        reset: 1,
        prev: 0,
        play: 0,
        next: 0,
        rotateLeft: 1,
        rotateRight: 1,
        flipHorizontal: 1,
        flipVertical: 1
      },
```

**Comment by xdmatirx** [comment]
哇，谢谢作者这么快回复消息，我就是只声明了部分按钮的显示状态，那暂时这样处理下
