### ISSUE TITLE
请问可以支持本地图片展示吗?

### ISSUE THREAD

**Issue by toraji1** [mirari/v-viewer#162]
请问可以支持本地文件展示吗?目前支持http://xxx/xxx.jpg这样的，请问是否可以支持例如c:\1.jpg，c:\2.jpg这样 的本地图片展示并翻页。

**Comment by mirari** [comment]
不可行，也不建议采用这种方案，你会遇到浏览器权限等各种坑
给本地图片文件夹搭个本地服务器都比直接访问本地资源靠谱
