### ISSUE TITLE
提个需求，能否让下面的button操作栏（放大，缩小等等）支持slot方式传入

### ISSUE THREAD

**Issue by bingyuea** [mirari/v-viewer#164]
提个需求，能否让下面的button操作栏（放大，缩小等等）支持slot方式传入，因为想新增按钮或者更改按钮图表

**Comment by mirari** [comment]
图片浏览的需求需要向viewerjs提，v-viewer本质上只是一个适配vue环境的壳子。
但是viewerjs作者之前表示不会添加新功能了，所以这个需求你可能需要自己fork项目来实现了

**Comment by bingyuea** [comment]
ok
