### ISSUE TITLE
使用 Vite + Vue3 + Ts 重构，新加 API 调用方式。

### ISSUE THREAD

**Issue by haiweilian** [mirari/v-viewer#167]
你好，感谢作者提供的插件之前我也一直在使用。

周末准备用 `Vue3` 重构的此项目，重构完之后发现您已在 `cli3` 分支开发（还以为是脚手架呢，就没注意）。本来不打算写了，我看了您的实现方式思路和我不太一样，觉得可以讨论一下比较好的方案。

#### 完整的代码地址

<https://github.com/haiweilian/v-viewer/tree/next>

#### 删除指令的功能

我不太清楚作者之前是什么原因添加指令功能的，使用指令监听子元素的变化的方式会造成很多意外的问题，我也没再使用。在现在的版本有些不方便的是，不能自定义标签名、或者有时造成多余的层级嵌套、没有 API 调用的方式。

我想有其他的办法可以解决，比如指令使用 `v-is`，它也会保留原始标签的属性。

```html
<section v-is="'viewer'" :images="reactiveImages.asyncImages">
  <img v-for="item of reactiveImages.asyncImages" :key="item" :src="item" width="200" height="200" />
</section>
```

#### 组件使用函数

使用 `render` 函数，控制标签的标签名添加 `tag` 属性实现、还比较容易扩展。

```ts
return () =>
  h(props.tag, { ref: $root }, slots.default && slots.default({ ...props })
);
```

这将渲染 `section` 标签。

```html
<viewer tag="section">
  <img v-for="item of reactiveImages.syncImages" :key="item" :src="item" width="200" height="200" />
</viewer>
```

#### API 调用的方式

使用 `API` 的方式，会很方便的处理某些问题，比如点击一个按钮然后预览图片，之前使用图片隐藏的方式太过麻烦也不太优雅。

期望调用方式如下，然后返回组件实例。

```js
viewerInstance = ViewerPreview({
  images: Images,
  options: Options,
});

nextTick(() => {
  viewerInstance.$viewer().view(1);
});
```

用 `render` 函数去渲染 `component` 组件，再返回组件实例。

```ts
function ViewerPreview(options: ViewerPreviewOptions) {
  // ....
  const vm = h(
    ViewerComponent,
    options,
    options.images.map((src) => {
      return typeof src === "string"
        ? h("img", { src })
        : h("img", { src: src.src });
    })
  );
  // ...
}
```

#### 整体的方案

我还没有做过多的测试，或者是否有其他更好的方式去实现。如果觉得可行，我将提交一个新分支。

**Comment by mirari** [comment]
非常感谢你的贡献，欢迎共同开发和探讨。
图片浏览的核心代码都是viewerjs的，v-viewer本质上只是一个壳子，纯粹是为了方便vue环境使用，并附带一些响应式的效果。
一开始加入指令的目的是想以尽快速度和尽量少的代码给项目内已有的图片列表增加大图浏览功能，指令写法的优点是给原有标签加一句指令就完了，不用关心标签或组件是什么、images的变量名是什么等，缺点是内部的元素需要尽可能简单，肯定不适合复杂页面。
这也是最接近viewerjs原始的加载思路——将指定元素下所有的img生成画廊。
也是因为监听内部元素容易出现各种意外，后来又加了组件形式，让用户传入images来优化viewer重载的时机，避免不必要的开销。(还有static标记，适用于确定内部img不会改变的场景)

但是viewerjs的加载方式也带来限制：必须生成实体img元素供其进行初始化。
比如一个el-table，每行显示一张图片，但点击放大时需要列出所有图片。这个场景需要将viewer放到比表格相同或更高的层级，但显示小图的行为只能交给表格，而不是viewer。
我也希望实现api的调用形式，但我觉得隐藏图片的方式绕不过去，不过可以把这些麻烦的逻辑放到组件内部实现，而不是让用户来做。

**Comment by mirari** [comment]
指令形式往元素上塞变量需要禁用ts校验，我还在想有没有更好的解决方案。

**Comment by mirari** [comment]
脚手架方面，我尝试了一下vite，但是还有一些问题没解决，比如eslint、sass变量等。
demo方面我希望保持之前的内容，你可以试一下把我的cli3分支里的示例代码迁移过去看能否运行

**Comment by haiweilian** [comment]
> 指令形式往元素上塞变量需要禁用ts校验，我还在想有没有更好的解决方案。

```ts
// 全局声明合并，global.d.ts
interface HTMLElement {
  $viewer: any
}

// 或者局部继承，directive.ts
interface ElementExtend extends Element {
  $viewer: any
}
```

**Comment by haiweilian** [comment]
> 脚手架方面，我尝试了一下vite，但是还有一些问题没解决，比如eslint、sass变量等。
> demo方面我希望保持之前的内容，你可以试一下把我的cli3分支里的示例代码迁移过去看能否运行

当然可以，因为这周末有事情需要处理，说的测试这事也没处理。可以加个微信吗(wx524066202)，互相学习下。
