### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by leefreeF** [mirari/v-viewer#17]
这个length的错误是从哪里来的  一直没有找到

**Comment by leefreeF** [comment]
![11](https://user-images.githubusercontent.com/32056701/37010634-69fc371c-2127-11e8-87f8-d7bdfef4ab64.png)

**Comment by leefreeF** [comment]
![22](https://user-images.githubusercontent.com/32056701/37010649-789fd4c2-2127-11e8-930a-2cf6c333e103.png)

**Comment by leefreeF** [comment]
![33](https://user-images.githubusercontent.com/32056701/37010652-7e6e58e2-2127-11e8-9cab-7b08f30a5dc1.png)

**Comment by leefreeF** [comment]
![44](https://user-images.githubusercontent.com/32056701/37010657-85e153a4-2127-11e8-8d08-00749edd74f5.png)

**Comment by leefreeF** [comment]
我用<div v-viewer>...  当一个单独的窗口显示我传进去的图片   现在出现一个length的错误  不知道从哪里出来的

**Comment by leefreeF** [comment]
![55](https://user-images.githubusercontent.com/32056701/37010780-14e78b4a-2128-11e8-9c40-3005cd7db5b3.png)

**Comment by mirari** [comment]
加个`v-if='images.length'`试试，viewer.js之前的版本一直有遗留问题，图片不存在的话初始化会报错。

**Comment by leefreeF** [comment]
![55](https://user-images.githubusercontent.com/32056701/37010805-3a70d664-2128-11e8-8552-5d22f6327a40.png)

**Comment by leefreeF** [comment]
你好  我再问个问题  $viewer of null  是什么原因呢

**Comment by leefreeF** [comment]
![66](https://user-images.githubusercontent.com/32056701/37011076-601cd02e-2129-11e8-8241-e6e6d7a3aba3.png)

**Comment by mirari** [comment]
肯定是querySelector没有找到元素啊。Vue的渲染不是同步的，要执行dom查询得放在vue渲染之后，可以用$this.,nextTick

**Comment by leefreeF** [comment]
![77](https://user-images.githubusercontent.com/32056701/37011478-56709eb4-212b-11e8-915e-191106fbc5a2.png)
![88](https://user-images.githubusercontent.com/32056701/37011483-5ef3dfd8-212b-11e8-9aca-929e892fbfd0.png)
已经应用了this.nextTick(function)

**Comment by mirari** [comment]
元素渲染出来了但viewer还没初始化完。要么改成组件式用法监听inited事件，要么看下viewer.js文档，把后续动作放到options里的ready回调里

**Comment by leefreeF** [comment]
谢谢你   明白了   万分感谢你的帮助

**Comment by leefreeF** [comment]
额  大神   options里的ready回调    有例子么  不知道该怎么开始写啊

**Comment by leefreeF** [comment]
比如说在我全局引入的main.js里面的options里面写时间   还是在vue文件里面的哪个钩子函数里面写  还是在methods方法里面写

**Comment by mirari** [comment]
options的用法在例子的源码里有
```
options: {
        ready () {
          console.log(1)
        },
        url: 'data-source'
      },
```
像这样配置就行。
不过，我刚看了下viewerjs的文档，全屏模式下ready事件只有在点击放大以后才能触发，但是指令模式现在无法捕获这个钩子，所以你只能改成组件写法，然后在inited事件里执行show方法。

**Comment by leefreeF** [comment]
我这里总是报 $viewer of null   这个$viewer是从哪里来的    直接使用可以么    是不是viewer初始化完成  就能获取到$viewer了

**Comment by leefreeF** [comment]
![1553b9ec1704fd01302df926273a1bb](https://user-images.githubusercontent.com/32056701/37019445-403d6bcc-2153-11e8-9b74-6b85e0a821cc.png)
![d9cdf7d03b02d195881ec4dfd8f5635](https://user-images.githubusercontent.com/32056701/37019447-41e6a272-2153-11e8-9027-1511d6b68ca7.png)
![6ccbc6c3c0b72ff9e734cc93836561d](https://user-images.githubusercontent.com/32056701/37019449-430f78e0-2153-11e8-88e8-0c8e1cc0def6.png)
![d1a36274c6de2f84383a7b7c4e13880](https://user-images.githubusercontent.com/32056701/37019451-440c3878-2153-11e8-99a9-4aa192b4d78f.png)

**Comment by leefreeF** [comment]
options:{
  inline:ture
}的时候是全屏  而且关闭不了


![1277eb91360737d08a046098ab9f949](https://user-images.githubusercontent.com/32056701/37022210-393044b2-215d-11e8-8828-b15235a5ad47.png)

**Comment by mirari** [comment]
inline本来就是占用页面内固定区域的，设计如此。
我说了show要放在inited事件回调中执行。
