### ISSUE TITLE
viewerjs 升级了，使用typescript会有问题

### ISSUE THREAD

**Issue by baixiaosh** [mirari/v-viewer#173]
报错提示：
Property 'flipHorizontal' of type 'boolean | 0 | Function | "small" | "medium" | 2 | 1 | 4 | 3 | "large" | ToolbarButtonOptions | undefined' is not assignable to string index type 'ToolbarOption'.

**Comment by baixiaosh** [comment]
Property 'flipHorizontal' of type 'boolean | 0 | Function | "small" | "medium" | 2 | 1 | 4 | 3 | "large" | ToolbarButtonOptions | undefined' is not assignable to string index type 'ToolbarOption'.

**Comment by mirari** [comment]
看上去是viewerjs的ts声明里没有加上新属性，如果你知道如何修改，可以在本地验证后，直接到
https://github.com/fengyuanchen/viewerjs/blob/master/types/index.d.ts
修改并提交pr

**Comment by baixiaosh** [comment]
已经有人提PR了 [#473](https://github.com/fengyuanchen/viewerjs/pull/473)
