### ISSUE TITLE
组件形式使用，突然发生的问题

### ISSUE THREAD

**Issue by ofgood** [mirari/v-viewer#177]
之前是^1.2.1版本，昨天项目上线打包的时候出现了，
`* v-viewer/src/component.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/viewer/index.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/view/flow/flowPicture.vue?vue&type=script&lang=js&
`
意思是就是找不到，v-viewer/src/component.vue ，这个依赖，很奇怪。
一个问题是，目前发现 1.5.0 版本是没有问题的，解决方案暂时是，直接锁住1.5.0版本

**Comment by mirari** [comment]
原因是npm发包时，把src目录去掉了。

其实不建议用这种形式引入。
通常node_modules目录下的脚本都会默认为是编译后的成品，所以babel等配置默认都会忽略node_modules。这时候如果直接打包项目，执行到这个未经转译的vue文件就会报错，除非再到babel配置里把这个库设置成强制编译。

使用最新的1.6.x版本，component组件可以通过` import { component } from 'v-viewer'`来获取，后续的使用跟之前没有区别。而且这是编译成品，无需面对上面这些繁琐问题。

**Comment by cereschen** [comment]
> import { component } from 'v-viewer'

请更新文档

**Comment by mirari** [comment]
> > import { component } from 'v-viewer'
> 
> 请更新文档

之前v2文档遗漏了，谢谢提醒，已更新
