### ISSUE TITLE
如何懒加载图片？

### ISSUE THREAD

**Issue by C-racker** [mirari/v-viewer#178]
现在如果有100张图片，点击某个图片触发后100张图片都会进行加载，而且切换图片也会进行加载，如何只加载需要显示的图片？

**Comment by mirari** [comment]
切换图片本身应该不会触发重加载，看看是不是调试模式开启了Disable cache。禁用缓存的话每次图片请求都会重新从网络获取。
默认的viewer弹窗会显示底部的图片列表navbar，这个目前没有懒加载功能，有多少就显示多少。
优化的一个方案是隐藏navbar，一个方案是用缩略图+大图模式优化加载速度。

**Comment by C-racker** [comment]
> 切换图片本身应该不会触发重加载，看看是不是调试模式开启了Disable cache。禁用缓存的话每次图片请求都会重新从网络获取。
> 默认的viewer弹窗会显示底部的图片列表navbar，这个目前没有懒加载功能，有多少就显示多少。
> 优化的一个方案是隐藏navbar，一个方案是用缩略图+大图模式优化加载速度。

非常感谢，确实是禁用缓存造成的，还有一个问题，如何配置可以显示当前第几张和总张数？例如 10/100

**Comment by mirari** [comment]
配置项里的title可以是函数，在函数中返回类似的逻辑，参考：
https://github.com/fengyuanchen/viewerjs#title
