### ISSUE TITLE
In readme default Options wrong name for object?

### ISSUE THREAD

**Issue by nicolascampbell** [mirari/v-viewer#179]
`import VueViewer from 'v-viewer'`
`import Vue from 'vue'`
`Vue.use(VueViewer)`
**`Viewer.setDefaults({`**
`    zIndexInline: 2017`
`})`
This is the last part of Readme. Shouldn't it be like this?:
`import VueViewer from 'v-viewer'`
`import Vue from 'vue'`
`Vue.use(VueViewer)`
**`VueViewer.setDefaults({`**
`  zIndexInline: 2017`
`})`

**Comment by mirari** [comment]
Thank you for the correction, it has been fixed.
