### ISSUE TITLE
1.6.3 版本依赖的 viewerjs@^1.6.2 全局监听键盘事件不生效

### ISSUE THREAD

**Issue by BelinChung** [mirari/v-viewer#180]
将 `viewerjs` 升级到 `^1.10.0` 问题解决

还有就是一个建议，需要把 `package-lock.json` 或者 `yarn.lock` 文件放到源码里，这样用户安装的依赖版本才可以跟作者的调试环境保持一致

**Comment by mirari** [comment]
组件项目一般不会用这种形式指定版本的，都是npm安装的，依赖的第三方库版本只能通过dependencies指定，一般不会是具体值。
组件的使用者才会用lock文件锁定版本，确实需要版本更新时，只能主动执行更新命令。

**Comment by BelinChung** [comment]
讨论的问题1：
`.lock` 能帮助开发者锁定 `dependencies`, `devDependencies` ，这样在多人协作开源项目的情况下，能保持小版本一致，有时候有些依赖不遵循版本声明，即使是重大变更，也只改小版本，这样多个开发者就会依赖了不同的版本（包括 `devDependencies`），比如有朋友想向你提交 `PR`

讨论的问题2：
通过 `npm install v-viewer` 安装的 `viewerjs` 版本是 `1.6.2`，这时候键盘监听事件无效。我猜想您没有发现这个问题的原因跟我一样，因为安装过 `v-viewer@next` 这时候 `.lock` 文件锁定的 `viewerjs` 的版本是 `1.10.0`，即使我切换回 `v-viewer@1.6.2` ，`.lock` 文件依然依赖的是 `viewerjs@v1.10.0`，所以问题才没有被抛出来。

至于真实的原因是为何，我暂时没有深究，通过本地额外依赖了  `viewerjs@v1.10.0` 也解决了这个问题

**Comment by mirari** [comment]
你应该是以前装过v-viewer，存在lock文件了吧，全新安装`npm install v-viewer`里面依赖的viewer实际版本应该是1.10.0。

**Comment by mirari** [comment]
你应该是以前装过v-viewer，存在lock文件了吧，全新安装`npm install v-viewer`里面依赖的viewer实际版本应该是1.10.0。

**Comment by BelinChung** [comment]
好的，我再注意一下
