### ISSUE TITLE
options里的container属性有问题？

### ISSUE THREAD

**Issue by JokingYi** [mirari/v-viewer#182]
container属性不起作用？还是说我使用方式不对，在本地使用npm引入也试过了
![image](https://user-images.githubusercontent.com/23569247/123221621-b5fef280-d501-11eb-833f-a40f19901506.png)

**Comment by JokingYi** [comment]
另外，本地使用Npm引入时，toolbar以及container属性都不起作用，是接口不一样？还是其他问题
![image](https://user-images.githubusercontent.com/23569247/123223289-5acdff80-d503-11eb-89d4-67e77efd983f.png)

**Comment by mirari** [comment]
我试了一下，container可以生效啊
https://codepen.io/mirari/pen/LYWwEMP

**Comment by JokingYi** [comment]
Vue.use(VueViewer.default)

是一定要加这个吗？
通过npm引入的话，加入这行会报错

**Comment by JokingYi** [comment]
谢谢答复

**Comment by mirari** [comment]
npm里不需要写default。
import xxx from 'xxx'这个写法默认取的就是default对象。

**Comment by JokingYi** [comment]
> npm里不需要写default。
> import xxx from 'xxx'这个写法默认取的就是default对象。

不知道放不方便给个npm的demo，还是不明白为什么本地Npm就是不起作用

**Comment by mirari** [comment]
https://codesandbox.io/s/v-viewer-api-nxh1g
最简单的用法是引入以后直接use

**Comment by JokingYi** [comment]
谢谢，不过我指的是在使用npm时，使用container的属性
在你上面给我的demo中，我使用container又出现了问题
![InkeduTools_1625141488011_LI](https://user-images.githubusercontent.com/23569247/124122487-b9b5ea80-daa8-11eb-95e8-f28083b7eb6b.jpg)
是我哪里使用有问题，给的参数都是一样的才对？

**Comment by mirari** [comment]
container不是这么用的，或者说viewerjs在后续设计时不再考虑把全屏模式放到一个容器里的场景了，全屏模式弹窗的样式用的是fixed，不会受父元素尺寸的限制，内部图片计算位置用的也是屏幕宽度而不是容器宽度。我前面的演示能把它限制在容器里是因为利用了fixed在transform父元素下的一个渲染差异。
如果你希望在容器内展现viewer，应该用inline模式。

**Comment by JokingYi** [comment]
好吧，不过你这句话不大明白“我前面的演示能把它限制在容器里是因为利用了fixed在transform父元素下的一个渲染差异。”，不理解为什么container又不能用了

**Comment by mirari** [comment]
position:fixed的元素一般情况下就是以窗口定位的，所以不管你的container放在页面的什么位置，最后打开的viewer弹窗总会全屏显示。如果你折腾container的目的是希望让弹窗只显示到页面红色部分，那这个写法显然不会生效。

transform会产生一个新的布局定位，导致fixed的样式坐标系被限制在该元素内。
https://www.cnblogs.com/xxhuan/p/11030244.html
但是viewer页面展示用到的其他计算都是来自窗口的尺寸，而不是container元素的尺寸，所以实际展现还是会出问题。

**Comment by JokingYi** [comment]
ok, 谢谢作者耐心解释
