### ISSUE TITLE
api形式调用在线上环境出错

### ISSUE THREAD

**Issue by 956632862** [mirari/v-viewer#185]
在线上环境打印了viewer，发现没有api这个方法，无法使用api调用
![image](https://user-images.githubusercontent.com/33861685/124879788-2d537c80-e000-11eb-81bf-f823cdd6bbf1.png)

**Comment by mirari** [comment]
是不是没有更新依赖，api是1.6.x新增的功能

**Comment by 956632862** [comment]
> 是不是没有更新依赖，api是1.6.x新增的功能

啊？可是最新版本不是1.5.1吗？而且本地的1.5.1版本也是有这个api函数的

**Comment by mirari** [comment]
最新版本是1.6.3，可以去node_modules下找到v-viewer的package.json文件或者直接查看npm或者yarn的lock文件确定下当前版本

**Comment by 956632862** [comment]
> 最新版本是1.6.3，可以去node_modules下找到v-viewer的package.json文件或者直接查看npm或者yarn的lock文件确定下当前版本

github上没有更新哦..

**Comment by mirari** [comment]
npm是最新版，github仓库也是，只是没有打release包，你是用npm安装的吧

**Comment by 956632862** [comment]
> npm是最新版，github仓库也是，只是没有打release包，你是用npm安装的吧

是啊，我在release看那个版本是1.5.1，我就没去在意版本了，现在解决了，谢谢

**Comment by woyehaizaixiang** [comment]
现在使用最新版本3.0.9依然没有导出api，......

**Comment by mirari** [comment]
> 现在使用最新版本3.0.9依然没有导出api，......

3.0.9是vue3用的，版本是否对应？我这边测试npm引入和在线例子都没问题

**Comment by woyehaizaixiang** [comment]
> > 现在使用最新版本3.0.9依然没有导出api，......
> 
> 3.0.9是vue3用的，版本是否对应？我这边测试npm引入和在线例子都没问题

通过npm安装的，是否是打包问题？

**Comment by mirari** [comment]
可以到node_modules目录下检查下版本，也可以在源码下搜一下关键字，但是vue3版本是一开始就支持api的，需要看下引入方式和调用方式是否正确
