### ISSUE TITLE
按鈕圖片沒出現

### ISSUE THREAD

**Issue by hsujoe** [mirari/v-viewer#186]
![image](https://user-images.githubusercontent.com/23050612/124893276-28e19080-e00d-11eb-904b-dc7c91bb4624.png)

想請問這個按鈕沒出現icon是什麼原因?

**Comment by mirari** [comment]
按钮图片用的是CSS Sprite
去浏览器开发者工具中检查是否有全局样式影响
比如`li::before`之类的样式定义
