### ISSUE TITLE
生产环境控制台输出问题

### ISSUE THREAD

**Issue by javed119** [mirari/v-viewer#187]
在指定NODE_ENV=production后仍然会打印相关语句
![image](https://user-images.githubusercontent.com/35559286/125283519-13d96a00-e34b-11eb-9448-8de58d36a984.png)

**Comment by mirari** [comment]
感谢反馈，是个愚蠢的错误，合并pr的代码中有直接引入vue，打包时没有排除，导致集成了vue本体，连着包也大了一圈。
更新到1.6.4即可。
