### ISSUE TITLE
您好，请问下如何监听move事件

### ISSUE THREAD

**Issue by CathyFen** [mirari/v-viewer#191]

**Comment by mirari** [comment]
在options里写回调，或者在viewer对象上监听
https://github.com/fengyuanchen/viewerjs#move
https://github.com/fengyuanchen/viewerjs#move-1

**Comment by smj199265** [comment]
options里写没有用呀，viewer监听应该放在哪里呀?

**Comment by mirari** [comment]
https://codepen.io/mirari/pen/ZwpGBO
