### ISSUE TITLE
为啥要把vue打包到dist里面，感觉要优化下实现和构建

### ISSUE THREAD

**Issue by yulodl** [mirari/v-viewer#193]

**Comment by mirari** [comment]
之前某个版本打进去了，现在应该没有了啊

**Comment by yulodl** [comment]
确实是`1.6.3`里面有，升级了下没有了

**Comment by yulodl** [comment]
如果用了`import()`进行路由分割，好像还是会把vue给bundle进来 @mirari

**Comment by mirari** [comment]
可以看下node_modules/v-viewer/dist下的源文件，1.6.4的话应该是只有viewer相关逻辑的，未压缩是700多行，如果还有vue被打包进来，应该是项目其他地方的配置问题
