### ISSUE TITLE
问下怎么做才能把图片铺满屏幕 

### ISSUE THREAD

**Issue by 617450941** [mirari/v-viewer#195]
问下怎么做才能等比例把图片铺满屏幕  现在默认图片是不铺满整个容器的

**Comment by mirari** [comment]
目前应该不支持，需求需要去viewerjs下面提issue，v-viewer只是一个壳子
https://github.com/fengyuanchen/viewerjs/issues

**Comment by CuiYuXi** [comment]
试一下 setTimeout(function(){_this.$viewer.zoomTo(1);},"300"); 如果可以就尝试调小一下时间
