### ISSUE TITLE
支持自定义按钮吗？比如增加删除和下载按钮

### ISSUE THREAD

**Issue by muziling** [mirari/v-viewer#196]
想增加删除当前查看的图片，下载当前图片的功能 ，翻了使用说明 没找到，想请教下要怎么实现。
原viewerjs里有人提到：https://github.com/fengyuanchen/viewerjs/issues/490

**Comment by mirari** [comment]
目前没有原生的方式实现。只能在初始化回调后，自己用操作DOM元素的方式往页面上添加按钮

**Comment by mirari** [comment]
可以参考这个示例
https://codepen.io/mirari/pen/GRMBrBv
