### ISSUE TITLE
vue3 版本更改options 无法update

### ISSUE THREAD

**Issue by cnhuye** [mirari/v-viewer#197]
之前是vue2 版本，使用正常。  
升级到 vue3 后， 更改 options 如 options.navbar, viewer 不会更新。 chrome 中加断点发现，viewsjs 中的 options 仍然是首次初始化时的数据。

查看了v-viewer 代码发现，原来在 watch(options) 时会 rebuildviewer(), view3 中只会 updateviewer()。

**Comment by mirari** [comment]
感谢反馈，3.0.10已修复
