### ISSUE TITLE
IE 11: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by willsilvano** [mirari/v-viewer#2]
Hello friend!

I'm getting this error when open the component in IE 11.

`Object doesn't support property or method 'assign'`

Can you help me?

**Comment by willsilvano** [comment]
Fixed using this: https://github.com/JeffreyWay/laravel-mix/issues/436#issuecomment-281374759

**Comment by mirari** [comment]
That's my oversight. I use babel-polyfill to build my example project so it works in IE 11, but babel-loader does not include transform-object-assign.
I will try to optimize the config later.

**Comment by mirari** [comment]
0.2.1 fixed
