### ISSUE TITLE
动态变更图片列表时遇到的问题；

### ISSUE THREAD

**Issue by kumakumasan** [mirari/v-viewer#20]
作者好！非常感谢您提供这么好的代码。
我在处理自己的一个场景时遇到了一些问题，特请指导如何修正；

场景描述：
我使用组件方式，希望能通过点击某个对象后获取到一个图片url，然后再将这个url放到images中，然后再打开全屏浏览。在点击之前，images里面应该是空的。每次点击前都需要将images清掉。

代码：
![qq 20180401160724](https://user-images.githubusercontent.com/26767042/38171193-087dc6fe-35c7-11e8-9aef-8b0bfc255540.png)
此处我不需要显示图片列表，所以我用了一个v-show来不显示；

![qq 20180401160808](https://user-images.githubusercontent.com/26767042/38171198-31afde18-35c7-11e8-84de-88a2860e5df5.png)

![qq 20180401160836](https://user-images.githubusercontent.com/26767042/38171199-35adb364-35c7-11e8-8c36-06682733989c.png)

采用这种方法，会报“viewer.esm.js:352 Uncaught TypeError: Cannot read property 'length' of undefined" 的异常；

我看了你在别的issue中的回复，决定在viewer上增加了一个 v-if="images.length"条件，然后将show()移到了inited中，原有的imageShow方法，去掉了this.$view.show()。

但是新的问题又出现了，图片虽然能正常打开，但是貌似是3张相同的层叠在一起，需要点击图外关闭三次。

请问，像我这样的场景，最佳的处理方式是怎样的，谢谢！

**Comment by kumakumasan** [comment]
不好意思，是我犯了一个低级错误，把viewer放到了一个for循环里面了，导致被渲染了3次。谢谢！

**Comment by mirari** [comment]
主要代码来自viewer.js，我只是套了个壳给vue环境用。
this.$viewer.show最好在nextTick回调里执行。images立即改变时页面元素可能还没渲染完。

**Comment by 531431988** [comment]
> 在iview table组件中 render 的td 中点击，需要点击2次才能弹出显示，没有任何错误提示，求解

https://jsfiddle.net/s31qpr8m/

**Comment by mirari** [comment]
@531431988 
nextTick中只是images数据渲染完成，但viewer还没来得及初始化，初始化动作也是异步执行的。
一种方案是监听inited回调，在回调里再执行show方法：
[https://jsfiddle.net/s31qpr8m/](https://jsfiddle.net/s31qpr8m/)
一种方案是每行都创建一个viewer：
[https://codepen.io/mirari/pen/JxdZVG](https://codepen.io/mirari/pen/JxdZVG)
还有一种方案是不使用viewer自身的变化监听，自己来执行初始化动作：
[https://jsfiddle.net/rsz3ctg8/](https://jsfiddle.net/rsz3ctg8/)
