### ISSUE TITLE
图片预览

### ISSUE THREAD

**Issue by 1yuwang** [mirari/v-viewer#200]
图片预览  无论我点击哪张图片  播放的都是第一张图片  不应该是我点击哪张 放大的就是哪张吗  还是说我使用的方法不对

**Comment by mirari** [comment]
参考demo示例贴一下代码吧

**Comment by 1yuwang** [comment]
<span v-for="attachment in attachments"
          class="inline-block overflow-hidden attachmentsImg">
      <img 
           :src="attachment.url"
           class="item w-full h-full"
           @click="show"
           style=" min-width: 28.3vw; min-height: 32vw; margin-top: -29%; vertical-align: middle;"
      >
    </span>



 show() {
      const images = []
      for(let item of this.attachments){
        images.push(item.url)
        
      }
      this.$viewerApi({
          images
        })
    },

**Comment by mirari** [comment]
使用api模式时，你只传递了数组，viewer实例不知道你想默认显示的是哪张图。
需要传入options对象，并指定initialViewIndex。

但是如果这些图片本来就需要展现出来，没必要使用api模式，直接用组件或者指令就行了，会自动给图片添加点击事件

**Comment by 1yuwang** [comment]
组件我试了 没效果啊  有详细的文档吗

**Comment by 1yuwang** [comment]
已经解决了 谢谢
