### ISSUE TITLE
怎么自定义toolbar

### ISSUE THREAD

**Issue by chenxin9482** [mirari/v-viewer#201]
我想只保留上一张和下一张两个选项，下面是我的配置，可是不生效，是我写错了么
Viewer.setDefaults({
  Options: {
    "inline": true,
    "title": true,
    "toolbar": {
      prev: function () {
        Viewer.prev(true);
      },
      next: function () {
        Viewer.next(true);
      },
    }
  }
});
Vue.use(Viewer);

**Comment by mirari** [comment]
参考示例
https://codepen.io/mirari/pen/gOgMqeE
只能定义按钮开关，不能自定义功能
