### ISSUE TITLE
Are these any release of this library for ReactJs

### ISSUE THREAD

**Issue by vanminhquangtri** [mirari/v-viewer#204]
Hello,

Thank you so much for this perfect library. I helps me very much on my Vue projects. I am going to create new project with Reactjs so I wonder Are these any release of this library for ReactJs?

If it has please send me npm link. I searched on Internet but no result found.

Thank you.

**Comment by mirari** [comment]
I'm not sure if there is a react version, but `v-view` is just an adapter for `viewerjs` in `Vue`, so you can use `viewerjs` directly with Reactjs, passing an HTML element like this:
https://github.com/fengyuanchen/viewerjs#syntax

**Comment by vanminhquangtri** [comment]
Many thanks for your useful response.
