### ISSUE TITLE
How to update images array in v-viewer?

### ISSUE THREAD

**Issue by shizzic** [mirari/v-viewer#207]
I mean this.images have some urls and i delete some of them. Viewer not updating this reactivly. How to make viewer to see new data?
```js
    show() {
        this.$viewerApi({
            options: {
                focus: false,
                toolbar: false,
                title: false,
                tooltip: false,
                viewed: this.currentImage
            },
            images: this.images,
        });
        
    },
    currentImage(event) {
        console.log(event);
        let result = {};
        result['images'] = ["https://media.isinda.ru/localhost/users/3/images/2/full.png", "https://media.isinda.ru/localhost/users/3/images/3/full.png"];
        this.$emit('newImages', result);
    }
```

**Comment by mirari** [comment]
When using api mode, images should be refreshed instantly and I can't reproduce the problem you describe. You can refer to the following example to provide code examples:
https://codepen.io/mirari/pen/zYEKxLQ

**Comment by shizzic** [comment]
> When using api mode, images should be refreshed instantly and I can't reproduce the problem you describe. You can refer to the following example to provide code examples: https://codepen.io/mirari/pen/zYEKxLQ

Noooo. I did this with restart viewer. I mean you first remove or add image and only after that start viewer. But i need this with working viewer without restart.
Can i do that?

**Comment by shizzic** [comment]
I did this with using v-viewer as directive. And with that, data reactively updating.

**Comment by mirari** [comment]
Data is not responsive when using api mode.
Component and directive are currently available to meet your needs.
They use the `viewerjs` native `update` command for refreshing by default, but this can sometimes be problematic.
