### ISSUE TITLE
Rotate button is not working in my app even in official demo too

### ISSUE THREAD

**Issue by EABangalore** [mirari/v-viewer#209]
Hi @mirari i'm seeing that rotate button is not working even in your official demo https://mirari.cc/v-viewer/  in my app too.

please fix that or let us know any solution exists.

**Comment by mirari** [comment]
I am unable to reproduce the problem and need to provide details of the runtime environment. If you have a similar problem with your application at [viewer.js](https://fengyuanchen.github.io/viewerjs/), it may be that the container does not support some css syntax.
