### ISSUE TITLE
Getting a "Failed to resolve directive: viewer"?

### ISSUE THREAD

**Issue by MarbilleJuntado** [mirari/v-viewer#21]
I downloaded `v-viewer.js` into my project and registered it using `Vue.use(VueViewer)`. I start getting the warning whenever I use "v-viewer" in my html. I'm assuming there are additional steps to successfully register the directive?

**Comment by mirari** [comment]
Could you give me an example? Like this:
[https://jsfiddle.net/mirari/n1L0gxtv/](https://jsfiddle.net/mirari/n1L0gxtv/)
