### ISSUE TITLE
建议添加一个下载的功能

### ISSUE THREAD

**Issue by WFL-Tian** [mirari/v-viewer#210]
建议添加一个下载的功能，显示的告诉用户可以点击下载，而不是让用户右击保存图片下载。

**Comment by mirari** [comment]
功能性需求需要去viewer.js下面提，但是作者应该不会增加新功能了。只能在viewer创建的回调中，用原生脚本往按钮栏添加自定义按钮

**Comment by mirari** [comment]
发现现在已经可以自定义了，参考以上示例即可
