### ISSUE TITLE
使用pnpm安装时，导入css样式提示找不到

### ISSUE THREAD

**Issue by ljxyaly** [mirari/v-viewer#212]
This dependency was not found:

* v-viewer/dist/viewer.css in ./src/main.js

pnpm扁平化结构中的文件夹为v-viewer，则链接指向的实际安装包的名称为viewerjs，不知道是不是这个原因

**Comment by mirari** [comment]
v-viewer依赖viewerjs，css也是viewerjs里的，引入css的地方不能写v-viewer，改成
```
import 'viewerjs/dist/viewer.css'
```

**Comment by ljxyaly** [comment]
是的，一直以来就是这样引入的
`import 'viewerjs/dist/viewer.css'`

只是改成 pnpm 安装时，实际引用的 viewerjs 的包是放置在 `.pnpm/node_modules` 中，此时如果这样引用
`import '.pnpm/node_modules/viewerjs/dist/viewer.css'` 好像没问题

但如果是在 `v-viewer/src/index.js` 中加入 `import 'viewerjs/dist/viewer.css'`,即将该css也打包出来，此后引入则可使用
`import 'v-viewer/dist/style.css'`，在使用时隔绝对viewerjs的依赖

这样的话您觉得可行吗？

**Comment by mirari** [comment]
之前是考虑直接引入css的，但是有些人反馈NUXT之类的SSR的脚手架这么写会报错，就去掉改成自行引入了
显式引入viewerjs再用上面的写法试试吧

**Comment by ljxyaly** [comment]
放本地引入了
