### ISSUE TITLE
使用inline模式展示在一个非全屏元素里时，viewer-container还带有".viewer-fixed"类名

### ISSUE THREAD

**Issue by WWan-Wu** [mirari/v-viewer#219]
![1646709611946](https://user-images.githubusercontent.com/38873504/157159831-2e092b69-ebc4-4061-aab9-fbbf3eb5a1ae.jpg)
<img width="532" alt="image" src="https://user-images.githubusercontent.com/38873504/157160008-6ef2359c-d89d-42d4-9427-8ee2a84b66cb.png">
受.viewer-fixed影响，预览区域变成了整个视窗

**Comment by mirari** [comment]
api方式调用时不支持inline模式。
https://github.com/mirari/v-viewer#usage-of-api
这应该是配置冲突导致了全屏模式独有的样式残留了。
api方式调用的本质是创建了一个临时元素存储图片然后用viewerjs初始化，适用于简单的动态图片数组全屏展示。

inline模式建议用组件或者指令实现，修改图片数组会自动更新内容。
