### ISSUE TITLE
请问支持外部按钮控制缩放，重置，旋转等功能吗

### ISSUE THREAD

**Issue by lin-97** [mirari/v-viewer#223]

**Comment by mirari** [comment]
获取到viewer实例后(文档中关于`$viewer`的使用)，可以执行任何开放给外部调用的功能，详情需要查看viewerjs文档
https://github.com/fengyuanchen/viewerjs

**Comment by lin-97** [comment]
组件调用方式可以吗？而且配置了fullscreen: false,     inline: true

**Comment by mirari** [comment]
组件调用的默认例子里包含了这个需求的运用

https://github.com/mirari/v-viewer#usage-of-component

**Comment by lin-97** [comment]
好的，谢谢作者大大

**Comment by lin-97** [comment]
实例上面好像没看到旋转的方法和其他方法，只看到一个onResize的方法，可以用，其他没看到，是不是存在某个属性下面

**Comment by lin-97** [comment]
谢谢可以了，v-viewer  yyds， 英文文档太难读了，呜呜呜
