### ISSUE TITLE
用api方式预览时，页面上的input获取不到焦点，无法输入

### ISSUE THREAD

**Issue by WWan-Wu** [mirari/v-viewer#225]
特殊原因只能使用api方式，预览的容器元素和input元素层级上没有重叠覆盖问题。api方式能使用static参数吗？

**Comment by mirari** [comment]
能提供一个复现例子吗？参考https://codepen.io/mirari/pen/NWpwVdd
api方式是不支持inline模式的，但是你想要的效果肯定能用api方式以外的形式实现

**Comment by WWan-Wu** [comment]
<img width="958" alt="WeChat633c88f74d3960383c49b097db8f5b87" src="https://user-images.githubusercontent.com/38873504/160966837-2e321971-af65-4798-a06a-63c27faa52cd.png">
点击输入框后获取不到焦点，控制台document.activeElement取到的是左侧的预览容器。
没用api方式以外的形式是因为页面上不能放缩略图，其他两种方式都是放了缩略图，然后点击打开预览模式。
如果用标签方式能够做成不需要在页面上放占位，直接能进入预览模式也行

**Comment by mirari** [comment]
图片标签可以隐藏，参考
https://codepen.io/mirari/pen/vjjXwj
