### ISSUE TITLE
怎么获取图片初始化时候的显示缩放大小比例

### ISSUE THREAD

**Issue by lin-97** [mirari/v-viewer#226]

**Comment by mirari** [comment]
如果是zoom缩放，就监听zoom事件
https://github.com/fengyuanchen/viewerjs#zoom-1

**Comment by lin-97** [comment]
初始化的时候zoom事件不触发

**Comment by lin-97** [comment]
options: {
				fullscreen: false,
				inline: true,
				toolbar: false,
				navbar: false,
				rotatable: true,
				backdrop: true,
				button: true,
				zoom: (e) => {
					console.log('hahah', e)
					this.zoomProportion = parseInt(e.detail.ratio * 100) + '%'
				},
				ready: () => {
					console.log('666', this.$viewer)
				},
				viewed: (e) => {
					// console.log('准备', e)
					// this.$viewer.zoomTo(0.15)
				}

**Comment by lin-97** [comment]
好像找到了，好像是在实例对象initialImageData属性上
			options: {
				fullscreen: false,
				inline: true,
				toolbar: false,
				navbar: false,
				rotatable: true,
				backdrop: true,
				button: true,
				zoom: (e) => {
					this.zoomProportion = parseInt(e.detail.ratio * 100) + '%'
				},
				ready: () => {
					setTimeout(() => {
						this.zoomProportion = parseInt(this.$viewer.initialImageData.ratio * 100) + '%'
					}, 300)
				},
				viewed: (e) => {
					// console.log('准备', e)
					// this.$viewer.zoomTo(0.15)
				}

**Comment by mirari** [comment]
应该也可以在viewed回调中处理
event对象里也可以拿到viewer

**Comment by lin-97** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mirari ***@***.***&gt;
发送时间: 2022年3月31日 16:11
收件人: mirari/v-viewer ***@***.***&gt;
抄送: 史蒂芬林 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [mirari/v-viewer] 怎么获取图片初始化时候的显示缩放大小比例 (Issue #226)





 
应该也可以在viewed回调中处理
 event对象里也可以拿到viewer
