### ISSUE TITLE
How can can stash the rotate toolbar icon

### ISSUE THREAD

**Issue by cibilex** [mirari/v-viewer#227]
Hi there,I need help for these problems
1. I want to remove this button but I couldn't.
![image](https://user-images.githubusercontent.com/55107569/162576192-76809279-539e-45e3-98f8-e082b82c94a1.png)
![image](https://user-images.githubusercontent.com/55107569/162576218-20669b4b-9719-4f00-b552-f4ea60d2eb01.png)

2. I want to change styles of buttons and background

**Comment by mirari** [comment]
Refer to this example:
https://codepen.io/mirari/pen/GRMBrBv
Overriding the original css to change the style.

https://github.com/fengyuanchen/viewerjs#toolbar
