### ISSUE TITLE
Drawing html5 elements on the image

### ISSUE THREAD

**Issue by askari12** [mirari/v-viewer#228]
I need to draw on the image using html5 . For that I need to get the active canvas object somehow so I can manipulate it to draw on top of the displayed image.

Is there a way for this functionality to be added ? Or maybe if this functionality exists, can you guide me to how I can use it ?

Thanks in advance !

**Comment by mirari** [comment]
There is no such function, I can provide a similar example but not sure if it is what you need:
https://codepen.io/mirari/pen/pobbdoE

**Comment by askari12** [comment]
Hi mirari, thanks so much for your speedy response !

It's not exactly what I'm looking for.. I would like the html5 element to be scaled up and down , rotated etc .with the image as well .. would that also be possible ?

**Comment by mirari** [comment]
Unfortunately, this is not possible at the moment. ViewerJS uses CSS to achieve effects such as scaling and rotation of images, which is a different system from canvas.

**Comment by rohith217** [comment]
If i change the key for the image and if want the zoomed position and the moved position retained, is it possible?

**Comment by mirari** [comment]
@rohith217 
At present, there seems to be no official solution.
I can only provide this idea without practice:
1. Save the `ratio` value on [`zoomed`](https://github.com/fengyuanchen/viewerjs#zoom-1) event, and do the same in other events.
2. Set the [`transition`](https://github.com/fengyuanchen/viewerjs#transition) to false in the option.
3. Call `zoomTo` and other methods in the `viewed` callback with the previously saved values.
4. Enable `transition`.

**Comment by rohith217** [comment]
Thank you for the reply @mirari  ,
But zoomTo always is zoomed to the center of the image. If i have moved the image how can i set that exact position?

**Comment by mirari** [comment]
@rohith217 
Save the value on [`moved`](https://github.com/fengyuanchen/viewerjs#move-1) event.
