### ISSUE TITLE
 no such file v-viewer.js

### ISSUE THREAD

**Issue by yurayurakh** [mirari/v-viewer#233]
Error: ENOENT: no such file or directory, open 'node_modules/v-viewer/dist/v-viewer.js'

**Comment by yurayurakh** [comment]
![image](https://user-images.githubusercontent.com/13859486/167832689-7a4b53a6-de72-4f04-8e1e-3e5a4f26d467.png)

**Comment by yurayurakh** [comment]
install viewer for Vue 3, command -  npm install v-viewer@next and after install i do not find file v-viewer.js in the forlder node_modules/v-viewer
![image](https://user-images.githubusercontent.com/13859486/167846667-f83880b6-451f-4eea-8f9c-d86b79fe1de8.png)

**Comment by mirari** [comment]
vue3-viewer uses a different packaging tool and generates different paths.
You don't need to write a fixed path.

CDN:
`<script src="//unpkg.com/v-viewer@next"></script>`
The actual path is:
`https://unpkg.com/v-viewer@3.0.10/dist/index.umd.js`
Module:
`import vue3-viewer`
The actual path is:
`vue3-viewer/dist/index.umd.js`
