### ISSUE TITLE
每次切换分支后都提示要重新安装v-viewer，不知道怎么回事

### ISSUE THREAD

**Issue by leoleor** [mirari/v-viewer#237]
These dependencies were not found:

* v-viewer in ./src/main.js
* viewerjs/dist/viewer.css in ./src/main.js

To install them, you can run: npm install --save v-viewer viewerjs/dist/viewer.css

**Comment by mirari** [comment]
检查切换分支后node_modules下是否存在v-viewer文件夹

**Comment by leoleor** [comment]
> 检查切换分支后node_modules下是否存在v-viewer文件夹

我发现没有找到，而且npm install --save v-viewer后能运行了，但是也找不到

**Comment by mirari** [comment]
这应该跟v-viewer无关了，检查node_modules目录是否被添加到git版本管理中了
