### ISSUE TITLE
作者你好, 在项目中使用v-viewer遇到问题无法解决(附在线BUG复现链接)。

### ISSUE THREAD

**Issue by AoHongJie** [mirari/v-viewer#238]
给viewer设置容器, 并在容器外放置一个兄弟元素。
兄弟元素显示内容为vue data中的数据初始值为空对象。
在viewed()方法中获取图片数据对数据赋值时viewer预览图像发生了闪退, 浏览器中的元素也消失了。
附在线链接[https://codepen.io/aohongjie/pen/vYdRdaJ](url)

**Comment by mirari** [comment]
闪退其实是viewer发生了重载，原因是检测到images或者options发生变化。
这里没有修改images，实际上是options变化导致的，因为没有把options作为变量传递而是在模板中声明了一个临时变量，这样可能在页面渲染时重复执行变量构造，触发watch监听。
把options里的配置改成变量就好了
https://codepen.io/mirari/pen/bGLvLXO

**Comment by AoHongJie** [comment]
> 闪退其实是viewer发生了重载，原因是检测到images或者options发生变化。 这里没有修改images，实际上是options变化导致的，因为没有把options作为变量传递而是在模板中声明了一个临时变量，这样可能在页面渲染时重复执行变量构造，触发watch监听。 把options里的配置改成变量就好了 https://codepen.io/mirari/pen/bGLvLXO

现在已将options定义在了data()中,但出现了新的问题
container容器是在dialog中的div
dialog是通过外层图片列表点击事件打开的, 并调用$viewer.show()显示图片预览
这时候dialog成功打开图像正常显示, 但没有显示在容器当中并且viewed(e) { console.log(e) } 打印为undefined
options配置如下
      options: {
        viewed: () => this.viewed(),
        hidden: () => this.handleHidden(),
        container: this.$refs.viewerContainer,
        backdrop: false,
        button: false,
        keyboard: false,
        url: 'data-source'
      }

**Comment by mirari** [comment]
data定义阶段子元素还没有开始渲染，这时候refs下所有变量都是未定义，赋值container实际上只能被回滚为默认值。
需要在mounted回调以后再赋值，但你的需求实际上应该用inline模式就可以满足了，不需要指定container(viewerjs全屏模式原生的container实现也存在问题，仅仅是把组件放到了该容器下，实际上宽高居中等计算都是以视窗大小决定的，无法限制在容器内，只有inline模式可以)

**Comment by AoHongJie** [comment]
> data定义阶段子元素还没有开始渲染，这时候refs下所有变量都是未定义，赋值container实际上只能被回滚为默认值。 需要在mounted回调以后再赋值，但你的需求实际上应该用inline模式就可以满足了，不需要指定container(viewerjs全屏模式原生的container实现也存在问题，仅仅是把组件放到了该容器下，实际上宽高居中等计算都是以视窗大小决定的，无法限制在容器内，只有inline模式可以)

业务场景是点击图片展示图片预览和其他信息(获取图像信息经纬度地图展示等...), 不适合用inline模式。
所以我选择对viewer的css修改来实现, 放到dialog拆分成组件。
刚才看了您的回答我尝试使用一下两种写法，但任然没有展示到cintainer容器当中
mounted() { this.options.container = this.$refs.viewerContainer }
data() {
return {
    options: {
            container: this.$nextTick(() => this.$refs.viewerContainer),
        }
    }
}

**Comment by mirari** [comment]
第二种方法肯定不行的，第一种方法不知道为什么没触发，但是可以将options整个赋值
```
  mounted() {
     this.options = {
        viewed: () => {
          this.viewed();
        },
        container: this.$refs.viewerContainer
      }
  },
```

inline模式也可以展现其他信息啊，而且应该比全屏模式更容易实现

**Comment by mirari** [comment]
我这里测试整个赋值是没有问题的
https://codepen.io/mirari/pen/bGLvLXO

而且我觉得你绕远路了，inline跟全屏的触发区别只在点击图片这个行为，既然你挪到对话框里使用了，那点击这个行为完全可以脱离viewer独立实现，inline模式只用于图片预览展现

**Comment by AoHongJie** [comment]
> 我这里测试整个赋值是没有问题的 https://codepen.io/mirari/pen/bGLvLXO
> 
> 而且我觉得你绕远路了，inline跟全屏的触发区别只在点击图片这个行为，既然你挪到对话框里使用了，那点击这个行为完全可以脱离viewer独立实现，inline模式只用于图片预览展现

谢谢大佬，你的回答很有帮助，我得重新想一下实现了。
