### ISSUE TITLE
想在点击的时候显示对应索引的图片, 这样写为什么会报错呢?

### ISSUE THREAD

**Issue by AoHongJie** [mirari/v-viewer#240]
问题链接: https://codepen.io/aohongjie/pen/XWZxapJ

**Comment by mirari** [comment]
加载时展现某个索引的图片，在配置中定义initialViewIndex就行了
https://github.com/fengyuanchen/viewerjs#initialviewindex

不要在inited回调里修改options和images，有可能反复触发inited回调导致死循环

**Comment by mirari** [comment]
参考实现：
https://codesandbox.io/s/v-viewer-zhezr

**Comment by AoHongJie** [comment]
> 加载时展现某个索引的图片，在配置中定义initialViewIndex就行了 https://github.com/fengyuanchen/viewerjs#initialviewindex
> 
> 不要在inited回调里修改options和images，有可能反复触发inited回调导致死循环

可是如果我这样写
options:{
viewed: () => this.viewed()
}

viewed(e) {console.log(e)} // 打印结果为undefined

inited(viewer) {this.$viewer.options.viewed = this.viewed}

viewed(e) {console.log(e)} // 正常打印

**Comment by mirari** [comment]
viewed回调是带参数的，你在定义阶段把参数丢了，执行到打印时当然就没东西了

**Comment by AoHongJie** [comment]
感谢大佬, 完美解决了问题。

**Comment by AoHongJie** [comment]
还有一个问题，外面会需要展示图片，点击图片把图片列表传到弹窗中inline模式展现。
这时候外面已经加载出来图片了，可以弹窗中确没有，viewer会重新等图片加载再渲染就导致点开弹窗还要加载一次图片不能马上显示出来, 该如何解决?

**Comment by AoHongJie** [comment]
还有一个问题，外面会需要展示图片，点击图片把图片列表传到弹窗中inline模式展现。
这时候外面已经加载出来图片了，可是弹窗中却没有，viewer会重新等图片加载再渲染就导致点开弹窗还要加载一次图片不能马上显示出来, 该如何解决?

**Comment by mirari** [comment]
如果外面已经加载过，那正常情况下会缓存。开发者调试模式想看到正常浏览的效果，需要关闭禁用缓存

**Comment by AoHongJie** [comment]
好的,感谢大佬解答。
