### ISSUE TITLE
图片会被渲染两次

### ISSUE THREAD

**Issue by Clownsw** [mirari/v-viewer#242]
环境: node 14 + vue2
使用了 `v-viewer` 绑定在了 `mavon-editor` 就导致图片会出现两次

**Comment by mirari** [comment]
需要更详细的描述，或者提供复现案例
出现两次是指图片加载了两次，还是在不同地方出现

**Comment by Clownsw** [comment]
> 需要更详细的描述，或者提供复现案例 出现两次是指图片加载了两次，还是在不同地方出现

#https://github.com/Clownsw/vueblog/blob/master/web/before/src/views/BlogDetail.vue

**Comment by Clownsw** [comment]
![3YVqFdY9m9](https://user-images.githubusercontent.com/28394742/175677120-09b8f0fc-7242-4dd3-ba6a-1652e7865970.png)

**Comment by mirari** [comment]
mavon-editor这个组件在渲染页面的时候在它的内部生成了两组数据。
一个在.v-note-show下面
一个在.v-note-read-model下面
重复的图片标签导致了重复生成的viewer

一种方案是在渲染完成的钩子中对.v-note-show进行手动实例化viewerjs；
另一种方案是在viewerjs的options中添加filter，过滤掉.v-note-read-model下面的那些图片
参考实现如下：
https://codepen.io/mirari/pen/JjLjBvz

**Comment by Clownsw** [comment]
> 

确实感谢
