### ISSUE TITLE
如何设置预览图像的初始比例呢?

### ISSUE THREAD

**Issue by AoHongJie** [mirari/v-viewer#243]

**Comment by mirari** [comment]
viewerjs没有提供配置项，但可以在回调中设置
https://codepen.io/mirari/pen/ZwpGBO

**Comment by AoHongJie** [comment]
现在是这样实现的,但是图片显示的大小不一致而且会先展现大图然后再缩小。  
  viewed(e) {
      this.$viewer.zoomTo(0.25)
    },

**Comment by mirari** [comment]
先大图再缩小这个勉强可以通过关闭transition配置项实现
但是要指定大小这个现在viewjs没有提供相关的配置，只能去那边提需求了
有类似的需求，但是目前没有实现
https://github.com/fengyuanchen/viewerjs/issues/337
https://github.com/fengyuanchen/viewerjs/issues/268
