### ISSUE TITLE
3.0.10生产环境报错

### ISSUE THREAD

**Issue by EvanYung** [mirari/v-viewer#245]
- vue: 3.2.31
- vite: 2.9.9
- v-viewer: 3.0.10
- 包管理: pnpm

![image](https://user-images.githubusercontent.com/20455032/176358892-fcadb85a-4d66-4df4-8dd3-c2fe19771dbb.png)

开发环境正常，生产环境打包后，页面报错 Unexpected token '...'

![image](https://user-images.githubusercontent.com/20455032/176358479-539d82ee-8547-4282-b0b5-ca039540ff38.png)

**Comment by mirari** [comment]
没有复现此问题，看下是否是在生产环境打包中使用了移除console.log命令的工具

**Comment by EvanYung** [comment]
> 没有复现此问题，看下是否是在生产环境打包中使用了移除console.log命令的工具

确实是这样，去掉就可以了，但是不知道为什么
![image](https://user-images.githubusercontent.com/20455032/176370395-cdf66da4-f5ab-4902-8ba1-3211fdd226cb.png)

**Comment by mirari** [comment]
v-viewer组件在打开调试配置项时会使用console.log输出日志，这个日志移除工具可能遗漏了一些特定场景，把console.log(...xxx)变成了...xxx，导致语法错误。

也可以看看这个工具是否允许例外
