### ISSUE TITLE
v0.3.x 升级 v1.x  直接乱

### ISSUE THREAD

**Issue by evolutionjay** [mirari/v-viewer#25]
讲真, 给个升级 API 修改提醒啊. 如果不是 vue 版的问题, 那么也在文档说出 viewerjs  在接口做出变更的提醒啊...

**Comment by mirari** [comment]
抱歉，唯一的重要改动就是需要自己手动引入css文件了
```
import 'viewerjs/dist/viewer.css'
```
文档稍后增加变更提醒
