### ISSUE TITLE
请问如何在play时如何获取当前图片的信息

### ISSUE THREAD

**Issue by Phyday** [mirari/v-viewer#251]
点击play开始播放后，如何获取当前播放图片的信息，如index？

**Comment by mirari** [comment]
viewerjs播放功能做得很简略，在播放时可能没有做回调触发，这个需求需要到viewerjs那边提了
或者你可以尝试自己实现，使用自定义按钮触发定时逻辑，图片浏览中的viewed等事件都可以正常触发

**Comment by Phyday** [comment]
ok
