### ISSUE TITLE
使用指令的方式如何更新图片集

### ISSUE THREAD

**Issue by zhanbinbin** [mirari/v-viewer#252]
使用指令的方式如何更新图片集

**Comment by zhanbinbin** [comment]
如下图所示，使用指令的方式调用，需要在特殊情况下更新当前图片，应该如何操作
![微信截图_20220723164808](https://user-images.githubusercontent.com/105685954/180597860-d0969842-2e4f-4950-891f-613255465d56.png)

**Comment by mirari** [comment]
api形式不支持响应式修改图片数组。如果有这样的需求，应该使用组件或者指令形式实现一个自定义组件，然后用脚本去控制它

**Comment by zhanbinbin** [comment]
使用api方式打开，然后在必要的时候使用api销毁（执行类似点击非图片区关闭预览），再重新打开是不是也可以，那么现在我想知道击非图片区关闭是需要调用什么方法，我试过destroy但是不行

**Comment by mirari** [comment]
执行api方法时返回的就是viewerjs对象，可以对实例对象进行操作
```
const viewer = api({
  images,
})
setTimeout(() => {
  viewer.hide()
}, 3000)
```

**Comment by zhanbinbin** [comment]
我已经解决了
