### ISSUE TITLE
api调用

### ISSUE THREAD

**Issue by AtroxEzerel** [mirari/v-viewer#254]
支持api调用是哪个版本开始支持的
现在使用1.4.0
![9xWv1fHN8QIc2qnRlVoOXQ==](https://user-images.githubusercontent.com/55567122/182777334-fbb1ba3f-c4a8-4b30-8a03-7e28f8816dfe.png)
返回是undefined

**Comment by mirari** [comment]
1.5.1以后，建议升级到最新版

**Comment by AtroxEzerel** [comment]
> 1.5.1以后，建议升级到最新版

好的 已解决 感谢🎈
