### ISSUE TITLE
列表加载的时候生成好多元素出来，有什么办法解决吗

### ISSUE THREAD

**Issue by 1047415098** [mirari/v-viewer#256]
列表页面加载的时候生成好多dom元素出来，有什么办法解决吗，不想生成加载那么多dom出来
![image](https://user-images.githubusercontent.com/28483622/183551781-f3a7c2b7-f107-4867-a593-5399da409617.png)

**Comment by mirari** [comment]
提供一下复现的例子吧，现在的信息没法定位问题

**Comment by 1047415098** [comment]
![image](https://user-images.githubusercontent.com/28483622/183552458-58018583-d0c6-4b89-a973-8627ee79322f.png)
![image](https://user-images.githubusercontent.com/28483622/183552519-955762f6-6746-4aac-bb76-c76fcebbcf55.png)
![image](https://user-images.githubusercontent.com/28483622/183552576-84741276-91b8-4ab1-b07a-2b31c5479516.png)

就是列表加载的时候，查看dom元素，就会发现生成出好多元素

**Comment by mirari** [comment]
每一行列表依次点击的话确实是会创建多个viewer。如果希望不要这么多，可以改用api模式，列表里的图片只触发点击按钮，点击后调用api打开viewer查看

**Comment by 1047415098** [comment]
有案例吗？我想问下怎么写的

**Comment by mirari** [comment]
在图片上绑定click事件，
在回调方法中执行api，传入url和配置项

https://github.com/mirari/v-viewer#usage-of-api
https://codepen.io/mirari/pen/NWpwVdd

**Comment by 1047415098** [comment]
好的，谢谢大佬，那就是没办法在设置配置里解决这个问题了咯，因为要改的话，工作量挺大的

**Comment by mirari** [comment]
配置没法解决，在循环里创建viewer，那当然是循环几次就有几个viewer实例

**Comment by 1047415098** [comment]
要怎么处理？我也觉得没必要处理，只是公司同事叫看能不能处理这个问题，他说一加载生成那边多dom元素，会不好，浏览器会卡

**Comment by mirari** [comment]
从数量上说，这些dom元素与表格行数一样多，如果认为这个数量算多，那表格内的tr也一样很多，td更多，无非一个在外一个在内，一眼看不到。
从渲染逻辑说，这些dom元素在viewer不打开时都是display:none状态，只占据极微小的一点内存，不参与页面重绘重排，且列表翻页或销毁时就会被从内存中释放。
如果一定要优化，就是我说的改为api调用模式，关闭viewer立刻释放。
