### ISSUE TITLE
您好,请问一下为什么我按指令方式调用后,能打开图片了,但下边的ToolBar却只有一张图片,不是全部呢?

### ISSUE THREAD

**Issue by visatest** [mirari/v-viewer#259]
<div class="img-item" v-for="(img, imgIndex) in _formFields[item.field]">
    <img v-viewer="options" :src="getSrc(img.path)" :onerror="errorImg" :key="imgIndex" />
</div>
export default {
  directives: {
    viewer: viewer({
      debug: true,
    }),
  },
 options: {
        toolbar: true,
        images: this.images,
        movable: false
      }
}

**Comment by mirari** [comment]
options没有images这个配置项，使用方法参考示例
指令和组件方式调用，都需要将图片实际渲染到目标元素内部
