### ISSUE TITLE
Component method not working!

### ISSUE THREAD

**Issue by harishankards** [mirari/v-viewer#26]
```html
<viewer :images="this.awardData.files">
          <img v-for="src in this.awardData.files" :src="'src'" :key="src">
        </viewer>
```
Hey, above is my code. I tried using component method. But nothing is shown in the browser.

Is that I should use `directive` method also or any of the methods(component, directives) is fine?

**Comment by mirari** [comment]
If your are using `1.x` version, you need to manually import the .css style:
```
import 'viewerjs/dist/viewer.css'
```

**Comment by harishankards** [comment]
Tried importing the CSS file and changing the data also. Dint help buddy @mirari

**Comment by mirari** [comment]
Check the console output, there must be a catch to it.

**Comment by harishankards** [comment]
@mirari 
console says
```js
 Failed to mount component: template or render function not defined.

found in

---> <viewer>
```

**Comment by mirari** [comment]
Register the component first, like this:
```
import 'viewerjs/dist/viewer.css'
import Viewer from 'v-viewer'
import Vue from 'vue'
Vue.use(Viewer)
```
or like this:
```
<template>
  <div id="app">
    <viewer :options="options" :images="images"
            @inited="inited"
            class="viewer" ref="viewer"
    >
      <template slot-scope="scope">
        <img v-for="src in scope.images" :src="src" :key="src">
        {{scope.options}}
      </template>
    </viewer>
    <button type="button" @click="show">Show</button>
  </div>
</template>
<script>
  import 'viewerjs/dist/viewer.css'
  import Viewer from "v-viewer/src/component.vue"
  export default {
    components: {
      Viewer
    },
    data() {
      images: ['1.jpg', '2.jpg']
    },
    methods: {
      inited (viewer) {
        this.$viewer = viewer
      },
      show () {
        this.$viewer.show()
      }
    }
  }
</script>
```

**Comment by harishankards** [comment]
Great! Thanks for the help @mirari ! Worked
But, the image is not responsive. How do I achieve that?

**Comment by mirari** [comment]
The viewer mode is responsive. If you mean the img tags you created, you need to define the styles by yourself.

**Comment by harishankards** [comment]
```html
<viewer :images="awardData.files">
          <img v-for="src in awardData.files" :src="'http://localhost:3000/'+src" :key="src">
        </viewer>
```
This is how I use it. How to make use of the viewer mode responsively than taking img tags paining myself too much on design?

**Comment by mirari** [comment]
Hide the img tags, and use the viewer instance method to show viewer mode, like this:
[https://codepen.io/mirari/pen/vjjXwj](https://codepen.io/mirari/pen/vjjXwj)
