### ISSUE TITLE
图片宽度可不可以为100%，自动播放间隔时间我设置不生效，能为3000,5000有点慢相对来说

### ISSUE THREAD

**Issue by TwenZi** [mirari/v-viewer#260]
![image](https://user-images.githubusercontent.com/49359809/195807533-f5214709-4af0-4cd6-8bde-1d13b76ca0b2.png)
[](url)

**Comment by mirari** [comment]
viewerjs刚刚添加了initialCoverage配置项，设置为1即可，详见https://github.com/fengyuanchen/viewerjs/commit/e2ced2deb3382ca9882e808fab59186721eaebd5
```
{
  initialCoverage: 1,
}
```
不过目前还没有正式发布，等待发布后更新即可。

自动播放时间间隔配置测试是有效的
```
{
  interval: 3000,
}
```

**Comment by TwenZi** [comment]
感谢前辈，自动播放时间间隔配置刚试了有效






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mirari/v-viewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mirari/v-viewer] 图片宽度可不可以为100%，自动播放间隔时间我设置不生效，能为3000,5000有点慢相对来说 (Issue #260)





 
***@***.***
 {   initialCoverage: 1, }  
不过目前还没有正式发布，等待发布后更新即可。
 
自动播放时间间隔配置测试是有效的
 {   interval: 3000, }
