### ISSUE TITLE
$viewerApi调用能否在增加一个index参数，去展示对应index的图片吗，不然一直打开都是默认第一张

### ISSUE THREAD

**Issue by 15309294916** [mirari/v-viewer#264]
$viewerApi({
    images: [src],
    index or current??
  });

**Comment by mirari** [comment]
viewerjs自带此配置，示例中已提供用法
`initialViewIndex`
https://codepen.io/mirari/pen/NWpwVdd

**Comment by 15309294916** [comment]
好的，万分感谢，怪我没有熟读文档，感谢作者
