### ISSUE TITLE
预览自定义右击事件

### ISSUE THREAD

**Issue by LemonStar0** [mirari/v-viewer#265]
我想在预览图片的时候自定义右击事件，有api支持吗？

**Comment by mirari** [comment]
可以在预览图片回调中获取dom对象并自行添加事件，原生不支持右键操作

**Comment by LemonStar0** [comment]
有预览图片的回调，没有关闭预览的回调？

**Comment by mirari** [comment]
https://github.com/fengyuanchen/viewerjs#hidden

**Comment by LemonStar0** [comment]
我的我的，漏看了，666
