### ISSUE TITLE
样式

### ISSUE THREAD

**Issue by zhengguodong** [mirari/v-viewer#266]
可以对图片预览的大小进行样式调整吗

**Comment by mirari** [comment]
如果指的是初始大小比例，用initialCoverage
https://github.com/fengyuanchen/viewerjs#initialcoverage

**Comment by zhengguodong** [comment]
> 如果指的是初始大小比例，用initialCoverage https://github.com/fengyuanchen/viewerjs#initialcoverage

就是预览时，所有图片统一宽高，能设置规定的长度

**Comment by mirari** [comment]
目前应该没有这样的配置

**Comment by wen18732367572** [comment]
请问如何对工具栏大小进行设置

**Comment by mirari** [comment]
开头引入的css，可以直接换成自定义的样式文件，修改其中对工具栏样式的定义
