### ISSUE TITLE
缩略图与原图

### ISSUE THREAD

**Issue by zgj1112** [mirari/v-viewer#267]
需求：缩略图链接已在数组中，原图链接能否在viewer弹出后再进行请求并填充至data-sorce

**Comment by mirari** [comment]
可以不要用组件或指令的形式调用。
自己实现缩略图的展现，然后监听缩略图的点击事件
在点击回调里拿到原图地址后，再调用api方式单独唤起viewer

**Comment by zgj1112** [comment]
感谢
