### ISSUE TITLE
v-viewer 使用报错

### ISSUE THREAD

**Issue by ZGKtob** [mirari/v-viewer#269]
Cannot read properties of undefined (reading '_c')

import 'viewerjs/dist/viewer.css';
import { component as Viewer } from 'v-viewer';

这样使用就报错

**Comment by mirari** [comment]
vue和v-viewer的版本号是什么？

**Comment by ZGKtob** [comment]
vue 3.0 v-viewer 3.0.10

**Comment by mirari** [comment]
我这里使用同样的版本环境没有复现问题，需要提供更多信息

**Comment by orlando-labs** [comment]
Hi, @mirari, first of all, thanks for your work, I highly appreciate it.

I can confirm the issue with the component-based usage
    "v-viewer": "^1.6.4",
    "vue": "^3.2.37",

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating '_vm._self._c')

**Comment by mirari** [comment]
> 
Vue3 needs to use vue3-viewer

https://github.com/mirari/vue3-viewer

**Comment by JustGogoing** [comment]
不要使用pnpm，我将pnpm切换成了npm就好了

> Cannot read properties of undefined (reading '_c')
> 
> import 'viewerjs/dist/viewer.css'; import { component as Viewer } from 'v-viewer';
> 
> 这样使用就报错

**Comment by mirari** [comment]
pnpm下，库的依赖不会出现在node_modules根目录里，显式引入viewerjs就行了，文档已更新
