### ISSUE TITLE
近期重新安装v-viewer插件之后使用组件方式调用失效

### ISSUE THREAD

**Issue by Ym-haohan** [mirari/v-viewer#274]
之前在本地运行的时候一切正常，最近重新安装了v-viewer包之后组件调用的方式就失效了，控制台没有任何报错，鼠标在单击被组件包裹的图片时无任何反应，v-viewer这个近几个月都没有更新，是不是依赖包viewer.js那边出问题了？

**Comment by mirari** [comment]
https://codepen.io/mirari/pen/PowNyEY
在线例子仍然可以运行，需要检查下v-viewer以及vue的版本号，还有是否正常导入css

**Comment by mirari** [comment]
在线例子vue2和3都有，上面那个地址是vue2的，对应的是v-viewer的1.6.4版本。

https://codesandbox.io/s/v-viewer-component-dps1f
沙箱版本也能正常运行，对照看下吧

**Comment by Ym-haohan** [comment]
问题已找到，重新安装v-viewer 1.6.4版本之后依赖的viewerjs版本从1.5.0更改为了1.11.3，所以组件调用方式失效，可以将1.6.4的依赖viewerjs版本锁定在1.5.0，沙箱环境可能是有lock文件锁定了依赖版本，但是重新拉取的话因为使用了viewerjs:^1.5.0
![image](https://github.com/mirari/v-viewer/assets/46101836/ab6a1dd4-3bf4-43b0-b665-c12d21ade467)
所以会拉取到新版本

**Comment by mirari** [comment]
在线例子用的viewerjs也是1.11.3，但是没有这个问题啊
