### ISSUE TITLE
'viewerjs/dist/viewer.css' 文件缺失

### ISSUE THREAD

**Issue by dizuncainiao** [mirari/v-viewer#276]
按文档指示，引入 css
`import 'viewerjs/dist/viewer.css'`

但是 CSS 文件没有
![image](https://github.com/mirari/v-viewer/assets/40376068/a2eebead-e472-4dc8-b09b-481f2679cba8)

**Comment by dizuncainiao** [comment]
这个 css 不知行不行 https://unpkg.com/viewerjs@1.11.3/dist/viewer.css，建议文档更新一下，或者将 css 打包进去

![image](https://github.com/mirari/v-viewer/assets/40376068/a59375fc-a1cd-42e8-8622-c676000eeb80)

**Comment by mirari** [comment]
包管理工具是什么？
手动npm i viewerjs之后应该就可以找到这个路径了，css不在v-viewer下而是在viewerjs下。
早期版本是打包了css的，但nuxt等工具解析import时会报错，因为有些场景往往还需要自定义css，所以索性没有强制引入，又分离开来让v-viewer只作为一个vue适配器。

**Comment by dizuncainiao** [comment]
> 包管理工具是什么？ 手动npm i viewerjs之后应该就可以找到这个路径了，css不在v-viewer下而是在viewerjs下。 早期版本是打包了css的，但nuxt等工具解析import时会报错，因为有些场景往往还需要自定义css，所以索性没有强制引入，又分离开来让v-viewer只作为一个vue适配器。

使用 pnpm 管理。
嗯嗯，我这边将 [viewer.css](https://unpkg.com/viewerjs@1.11.3/dist/viewer.css) 下载后本地引入解决的。
这个图片预览插件很好用，也是别人推荐给我的，应该有不少人用这个，所以建议作者有时间可以更新一下使用文档

**Comment by 1014156094** [comment]
+1

**Comment by mirari** [comment]
> 使用 pnpm 管理。 嗯嗯，我这边将 [viewer.css](https://unpkg.com/viewerjs@1.11.3/dist/viewer.css) 下载后本地引入解决的。 这个图片预览插件很好用，也是别人推荐给我的，应该有不少人用这个，所以建议作者有时间可以更新一下使用文档

不需要手动下载到本地引入，只要pnpm i viewerjs显式执行一下就行，后续操作与文档一致
