### ISSUE TITLE
v-viewer.js:414 Uncaught TypeError: Cannot set properties of undefined (setting '$viewerApi')

### ISSUE THREAD

**Issue by 1Telescope1** [mirari/v-viewer#279]
使用vue3跟着文档来然后控制台报错，"v-viewer": "^3.0.11"，在main.ts中也写了import 'viewerjs/dist/viewer.css'，
import Viewer from 'v-viewer' ，app.use(Viewer)

**Comment by mirari** [comment]
对照例子检查下写法吧
https://codesandbox.io/s/vue3-viewer-wfw2zk

**Comment by 1Telescope1** [comment]
> 对照例子检查下写法吧 https://codesandbox.io/s/vue3-viewer-wfw2zk

ok了
