### ISSUE TITLE
在iframe中使用回来时图片会跟随鼠标

### ISSUE THREAD

**Issue by mercuryKimi** [mirari/v-viewer#280]

**Comment by mirari** [comment]
大多数鼠标拖拽的实现都会有类似问题，一般不会特地对这种场景进行优化。
虽然可以提需求给viewerjs，但大概率是不会处理的。

建议更换思路，iframe内的组件只负责触发并通知外层容器调用图片浏览事件，将v-viewer放在最外层容器上，通过api形式调用打开。

**Comment by supuwoerc** [comment]
@mirari 按照这个思路或许是不是能让v-viewer支持挂在到window.parent上呢，我试试pr
