### ISSUE TITLE
点击缩略图, 怎样执行异步载入原始图片呢, 另外列表为base64时, 预览viewer-title好像把base64一大串字符串显示出来了

### ISSUE THREAD

**Issue by xibaoning** [mirari/v-viewer#282]
点击缩略图, 预览界面先显示载入等待图标, 载入完成后再显示, 
点击缩略图 怎样执行一个自定义函数, 然后这个函数去请求后台的地址,返回的信息包括了图片base64数据,如下伪代码:
<img  click="request" id="demo" />

function request(id){
   demo.loading=true  //显示载入中
   http.get(...).then(info=>{
       var title=info.Titil
       var imgdata=info.data
      demo.src='data:image/jpg;base64,'+imgdata
      demo.loading=false
   }

}

**Comment by mirari** [comment]
异步载入原始图片，就用api形式调用viewer，缩略图和点击逻辑自己实现
base64图片可以展示，如果是一堆字符串，就检查是不是格式写错了
