### ISSUE TITLE
VUE2用npm安装的本地开发正常，发布线上提示Assignment to constant variable

### ISSUE THREAD

**Issue by ivanlee93** [mirari/v-viewer#283]
VUE2用npm安装的本地开发正常，发布线上提示Assignment to constant variable

测试过，通过main引用了依赖其他啥都不动就会提示这个，本地开发不会

**Comment by mirari** [comment]
这是给常量赋值了，贴一下代码吧，至少也贴一下报错的上下文信息，不然没法判断问题

**Comment by Tim-LZT** [comment]
![image](https://github.com/mirari/v-viewer/assets/26397605/539ec886-8f77-4003-8431-c03bb016000b)

```js
function assign(target, ...args) {
  let i = 0;
  if (isPrimitive(target))
    target = args[i++];
  if (!target)
    target = {};
  for (; i < args.length; i++) {
    if (isObject$3(args[i])) {
      for (const key of Object.keys(args[i])) {
        if (isValidKey(key)) {
          if (isObject$3(target[key]) && isObject$3(args[i][key])) {
            assign(target[key], args[i][key]);
          } else {
            target[key] = args[i][key];
          }
        }
      }
      assignSymbols(target, args[i]);
    }
  }
  return target;
}
```

assign 方法打包后变成

```js
function l(e, ...t) {
      let r = 0;
      var i, n;
      for (("object" == typeof (i = e) ? null === i : "function" != typeof i) && (e = t[r++]),
      e || (e = {}); r < t.length; r++)
          if (c(t[r])) {
              for (const i of Object.keys(t[r]))
                  "__proto__" !== (i = i) && "constructor" !== i && "prototype" !== i && (c(e[i]) && c(t[r][i]) ? l(e[i], t[r][i]) : e[i] = t[r][i]);
              p(e, t[r])
          }
      return e
  }
```

不知道为啥打包后会有 i = i。

把 for (const key of Object.keys(args[i])) 改成  for (let key of Object.keys(args[i])) 就可以了。

**Comment by kkk-kppi** [comment]
我今天也遇到了，本地开发没问题；打包之后出现的，我在本地预览和SIT都出现了这个情况；
具体出现的版本：1.7.2、1.7.1都有这个问题
![image](https://github.com/mirari/v-viewer/assets/79731962/2bdb1038-58c5-4edc-9b39-e9da0219d1bd)

解决办法：我install 到1.6.4之后，没出现这个问题了

**Comment by mirari** [comment]
> 我今天也遇到了，本地开发没问题；打包之后出现的，我在本地预览和SIT都出现了这个情况； 具体出现的版本：1.7.2、1.7.1都有这个问题 ![image](https://private-user-images.githubusercontent.com/79731962/293883345-2bdb1038-58c5-4edc-9b39-e9da0219d1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzY1OTksIm5iZiI6MTcwNDI3NjI5OSwicGF0aCI6Ii83OTczMTk2Mi8yOTM4ODMzNDUtMmJkYjEwMzgtNThjNS00ZWRjLTliMzktZTlkYTAyMTlkMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZTZjZGFjYjNlN2NmN2Y0NTJmNzQzYmVlZDM5MTRmYzNhYzA5ZTRkYzY4N2NhMzNiZjgwZGIyMTRiYzc3MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wc_Gvq5-eOAozkYqu11a60s0Z1mAWvLeqAoz0kJV84I)
> 
> 解决办法：我install 到1.6.4之后，没出现这个问题了

1.7.x更新了部分工具函数。我会尝试再次更新工具函数，但这个错误看上去还是编译器压缩代码时导致的奇怪问题

**Comment by kkk-kppi** [comment]
> > 我今天也遇到了，本地开发没问题；打包之后出现的，我在本地预览和SIT都出现了这个情况； 具体出现的版本：1.7.2、1.7.1都有这个问题 ![image](https://private-user-images.githubusercontent.com/79731962/293883345-2bdb1038-58c5-4edc-9b39-e9da0219d1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzY1OTksIm5iZiI6MTcwNDI3NjI5OSwicGF0aCI6Ii83OTczMTk2Mi8yOTM4ODMzNDUtMmJkYjEwMzgtNThjNS00ZWRjLTliMzktZTlkYTAyMTlkMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZTZjZGFjYjNlN2NmN2Y0NTJmNzQzYmVlZDM5MTRmYzNhYzA5ZTRkYzY4N2NhMzNiZjgwZGIyMTRiYzc3MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wc_Gvq5-eOAozkYqu11a60s0Z1mAWvLeqAoz0kJV84I)
> > 解决办法：我install 到1.6.4之后，没出现这个问题了
> 
> 1.7.x更新了部分工具函数。我会尝试再次更新工具函数，但这个错误看上去还是编译器压缩代码时导致的奇怪问题

好，更新之后，我更新下依赖版本再继续看下是否仍会出现这个问题

**Comment by mirari** [comment]
@kkk-kppi 已更新到1.7.3了，移除了这部分会出现问题的函数

**Comment by monhly** [comment]
> @kkk-kppi 已更新到1.7.3了，移除了这部分会出现问题的函数

你好想问一下,更新完1.7.2以后为什么jenkins构建会出现这种错误? 是需要新装另外的插件吗?
<img width="1005" alt="image" src="https://github.com/mirari/v-viewer/assets/61449492/a9f41639-3cac-46c6-b6f1-8c0583c816f5">

**Comment by mirari** [comment]
@monhly 本地运行和build正常吗？

**Comment by mirari** [comment]
> > @kkk-kppi 已更新到1.7.3了，移除了这部分会出现问题的函数
> 
> 你好想问一下,更新完1.7.2以后为什么jenkins构建会出现这种错误? 是需要新装另外的插件吗? <img alt="image" width="1005" src="https://private-user-images.githubusercontent.com/61449492/293891081-a9f41639-3cac-46c6-b6f1-8c0583c816f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzkyODIsIm5iZiI6MTcwNDI3ODk4MiwicGF0aCI6Ii82MTQ0OTQ5Mi8yOTM4OTEwODEtYTlmNDE2MzktM2NhYy00NmM2LWI2ZjEtOGMwNTgzYzgxNmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwNDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZmJiMDk4N2MwZDdjYWM2MjAzZmVmZDg1YWJjNWFhNDgzZmE3YmVlNmZkMjY0NzQ1ZDg1MzQ5MzMyMDdjZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iBgN9w-OvyuH0yHot9lbvSUIaVZe3mi0I8SsuiOzs0Q">

看上去是viewerjs包没有安装。由于npm和pnpm下表现不一致，现在需要显式安装viewerjs
`npm i viewerjs v-viewer@legacy`

**Comment by kkk-kppi** [comment]
> @kkk-kppi 已更新到1.7.3了，移除了这部分会出现问题的函数

目前本地install1.7.3之后，本地打包和preview打包产物没有出现问题了

**Comment by mirari** [comment]
感谢及时反馈
