### ISSUE TITLE
Inline issue

### ISSUE THREAD

**Issue by Christian1626** [mirari/v-viewer#292]
Hello,

I'm using this component at the bottom of my page and I have the inline option set as "true".
When i'm reloading the page, I am **automatically** redirected to my component at the bottom of the page.
If i set inline as false, I don't have this issue; i'm staying at the top of the page.
How can I solve this ?

Here an example: [Demo](https://v-viewer-test.vercel.app/)
Code: [Github File](https://github.com/Christian1626/v-viewer-test/blob/main/src/components/ImageViewer.vue)

Thanks.

**Comment by mirari** [comment]
Sorry for not replying for a long time.
Has this problem been resolved? 
It seems that the performance in the demo is normal now. 
If there are still issues, you can try setting the `focus` value in options to `false`.

**Comment by Christian1626** [comment]
Yes perfect, that was exactly the property i was looking for.
Thanks.

**Comment by Christian1626** [comment]
Yes perfect, that was exactly the property i was looking for.
Thanks.
