### ISSUE TITLE
inline模式能否像modal 模式那样点击图片再显示出来吗

### ISSUE THREAD

**Issue by Lee66** [mirari/v-viewer#30]
现在看到的效果是默认就直接显示出来了，不能关闭。需要在inlne模式下点击哪张显示哪张，或者说可以让modal 模式可以放到某个div里

**Comment by mirari** [comment]
viewer.js上有[类似问题](https://github.com/fengyuanchen/viewerjs/issues/122)
你可以用inline模式自己定义一个弹窗，在别的地方点击后再弹出这个inline的viewer

**Comment by mirari** [comment]
原生的viewer.js就是将某个元素下所有img找出来，然后渲染出一个图片浏览器。v-viewer只是将那些img元素用了vue的双向绑定，在变化的时候销毁并重建渲染。
怎么修改vue对应的绑定数据需要你自己实现，viewer.js的api需要去viewer.js查看。
