### ISSUE TITLE
Enable photo download in the viewer toolbar

### ISSUE THREAD

**Issue by inakibs** [mirari/v-viewer#304]
Using this component I would be interested in **having an image download button in toolbar,** I understand there is nothing implemented yet. Is there any intention on this being able to be done in the future or **any suggestions on how to be able to do this**?

**Comment by mirari** [comment]
Perhaps the example at the top of the document is exactly what you want.

[custom toolbar](https://codepen.io/mirari/pen/GRMBrBv)

**Comment by panknows** [comment]
> Perhaps the example at the top of the document is exactly what you want.
> 
> [custom toolbar](https://codepen.io/mirari/pen/GRMBrBv)

How to make it globally?

**Comment by mirari** [comment]
> > Perhaps the example at the top of the document is exactly what you want.
> > [custom toolbar](https://codepen.io/mirari/pen/GRMBrBv)
> 
> How to make it globally?

Originally you could use [defaultOptions](https://github.com/mirari/v-viewer?tab=readme-ov-file#defaultoptions) to override some of the default settings, but when customizing buttons, it's difficult to get to the viewer object, so the best way to do this is to wrap a custom component.

**Comment by panknows** [comment]
> Originally you could use [defaultOptions](https://github.com/mirari/v-viewer?tab=readme-ov-file#defaultoptions) to override some of the default settings, but when customizing buttons, it's difficult to get to the viewer object, so the best way to do this is to wrap a custom component.

We can provide current viewer object to method parameter?

**Comment by mirari** [comment]
The defaultOptions usage doesn't work because there is no chance to get the viewer object at this point
