### ISSUE TITLE
页面中会出现两个viewer-container

### ISSUE THREAD

**Issue by Lee66** [mirari/v-viewer#31]
vue.js、viewer.js等是直接引入的，但是会出现并列两个viewer-container

**Comment by mirari** [comment]
贴下代码吧

**Comment by Lee66** [comment]
`<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>门店详情</title>
		<link rel="stylesheet" href="/static/css/base/base.css">
		<link rel="stylesheet" type="text/css" href="/static/css/base/viewer.min.css" />
		<link rel="stylesheet" href="/static/css/base/element-ui.css">
		<style>
			.el-textarea.is-disabled .el-textarea__inner {
				background-color: #FFFFFF;
				border-color: #e4e7ed;
				color: #000000;
				font-size: 14px;
			}
			
			.el-input.is-disabled .el-input__inner {
				background-color: #FFFFFF;
				border-color: #e4e7ed;
				cursor: not-allowed;
				color: #000000;
				font-size: 14px;
			}
			
			.el-input__inner {
				font-size: 14px;
				border-radius: 2px;
				border: 1px solid #a8aba7;
			}
			
			.el-form-item {
				margin-bottom: 5px;
			}
			
			.el-form-item__label {
				font-size: 14px;
				color: #304157;
			}
			
			.el-collapse-item__header {
				font-size: 18px;
			}
			
			.avatar-uploader {
				height: 149px;
			}
			
			.avatar-uploader .el-upload {
				border: 1.5px dashed #e4e7ed;
				border-radius: 6px;
				cursor: pointer;
				position: relative;
				overflow: hidden;
			}
			
			.avatar-uploader .el-upload:hover {
				border-color: #409EFF;
			}
			
			.avatar-uploader-icon {
				font-size: 28px;
				color: #8c939d;
				width: 146px;
				height: 146px;
				line-height: 146px;
				text-align: center;
			}
			
			.avatar {
				width: 146px;
				height: 146px;
				display: block;
			}
			
			.image li {
				float: left;
				/* 往左浮动 */
				margin: 10px;
			}
			
			.el-card,
			.el-notification {
				-webkit-box-shadow: none;
			}
			
			.el-card {
				border: 0px;
			}
			
			.textarea-box {}
			
			#tab1 .el-form-item__label {
				/*width: auto !important;*/
			}
			
			#tab1 .el-form-item__content {
				/*margin-left: 0 !important;*/
			}
			
			.el-tabs__item {
				font-size: 18px;
			}
			
			.offset-left {
				margin: 30px 0 0 -50px;
			}
			
			.storeInfoTitle {
				font-size: 18px;
				color: #304157;
				font-weight: bold;
				margin-left: 70px;
			}
			
			.viewer-navbar .viewer-list {
				height: 120px;
			}
			
			.viewer-navbar .viewer-list li {
				height: inherit;
				width: 50px;
			}
			
			.viewer-navbar .viewer-list li img {
				height: 30px !important;
			}
			
			.viewer-navbar .viewer-list li p {
				font-size: 14px;
				color: #fff;
				height: 30px;
				line-height: 1;
			}
		</style>
	</head>

	<body style="margin-left: 0px; margin-right: 0px; background-color: rgba(255, 255, 255, 1)">

		<div id="App" style="margin: 0 10px;" v-loading="loading">
			
			<div style="margin-bottom: 10px; margin-left: 24px; margin-top: 15px">
				<el-row>
					<el-col :span="22">
						<span style="font-size: 24px;  font-weight: bold; color: #304157">{{ detail.dealerInfo.name }}</span>
						<el-tag v-if="isMaster === '1' && detail.dealerInfo.status === 0" style="vertical-align: bottom;" type="danger">
							审核门店
						</el-tag>
					</el-col>
					<el-col :span="2" align="center">
						<div>
							<el-button type="primary" size="mini" @click="lastPage">上一页</el-button>
						</div>
					</el-col>
				</el-row>
			</div>
			
			<hr color="#C0C0C0" style="border-width: 0.5px" />
			<div style="margin-top: 30px; margin-left: 24px">
				<template>
					<el-tabs v-model="activeTab">
						
						<el-tab-pane label="门店" name="dealer" id="tab1">
							
							<el-col :span="10">
								<div class="offset-left">
									<span class="storeInfoTitle">门店信息</span>
									<el-form label-width="140px" style="margin: 20px 0px 0px 20px; color: #304157;">
										<el-row>

											<div class="grid-content bg-purple">
												<el-form-item label="业务类型">
													<el-input :value="detail.dealerInfo.bizTypeName" type="text" size="small" :disabled="true" resize="none" :rows="2" style="width: 320px"></el-input>
												</el-form-item>
											</div>

										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="门店类型">
													<el-input :value="detail.dealerInfo.typeName" type="text" size="mini" :disabled="true" resize="none" :rows="2" style="width: 320px"></el-input>
												</el-form-item>
											</div>
										</el-row>
										<el-row>

											<div class="grid-content bg-purple">
												<el-form-item label="所属城市">
													<el-input :value="detail.dealerInfo.cityName" type="text" size="mini" :disabled="true" resize="none" :rows="2" style="width: 320px"></el-input>
												</el-form-item>
											</div>

										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="所属市场" class="block">
													<el-input :value="detail.dealerInfo.marketName" type="text" size="mini" :disabled="true" resize="none" :rows="2" style="width: 320px"></el-input>
												</el-form-item>
											</div>
										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="门店名称">
													<el-input :value="detail.dealerInfo.name" type="text" size="mini" :disabled="true" resize="none" :rows="2" style="width: 320px"></el-input>
												</el-form-item>
											</div>

										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="详细地址" class="block">
													<el-input type="textarea" :value="detail.dealerInfo.address" size="5" :disabled="true" resize="none" :rows="2" style="width: 320px"></el-input>
												</el-form-item>
											</div>
										</el-row>
									</el-form>
								</div>
								<div class="offset-left">
									<span class="storeInfoTitle">门店联系人</span>
									<el-form label-width="140px" style="margin: 20px 0px 0px 20px; color: #304157;">
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="姓名">
													<el-input :value="detail.contacts[0].name" size="mini" :disabled="true" style="width: 320px"></el-input>
												</el-form-item>
											</div>

										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="性别">
													<el-input :value="detail.contacts[0].genderName" size="mini" :disabled="true" style="width: 320px"></el-input>
												</el-form-item>
											</div>
										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="身份" prop="titleName">
													<el-input :value="detail.contacts[0].titleName" size="mini" :disabled="true" style="width: 320px"></el-input>
												</el-form-item>
											</div>

										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="手机号" prop="mobile">
													<el-input :value="detail.contacts[0].mobile" size="mini" :disabled="true" style="width: 320px"></el-input>
												</el-form-item>
											</div>
										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="身份证号" prop="bossIdno">
													<el-input :value="detail.contacts[0].idNo" size="mini" :disabled="true" style="width: 320px"></el-input>
												</el-form-item>
											</div>

										</el-row>
										<el-row>
											<div class="grid-content bg-purple">
												<el-form-item label="有无营业执照" prop="hasLicenseName">
													<el-input :value="detail.contacts[0].hasLicenseName" size="mini" :disabled="true" style="width: 320px"></el-input>
												</el-form-item>
											</div>
										</el-row>
										<el-row>
											<el-col :span="12">
												<el-form-item label="附加影像信息">
													<div class="el-textarea is-disabled el-input-group textarea-box">
														<div disabled="disabled" class="el-textarea__inner" style="resize: none; min-height: 96px;width:320px;">
															<div v-for="additionAnnex in detail.contacts[0].additionAnnexes">
																{{ additionAnnex.annexName }} x{{ additionAnnex.count }}；
															</div>
														</div>
													</div>
												</el-form-item>
											</el-col>
										</el-row>

									</el-form>
								</div>

							</el-col>
							<el-col :span="13">
								<ul class="image" v-viewer style="opacity: 0;">
									<el-col tag="li" :span="6" v-for="imageItem of detail.accounts[0].accountImages[0].imageList">
										<el-card :body-style="{ padding: '0px' }" style="height: 210px">
											<div class="avatar-uploader">
												<div tabindex="0" class="el-upload el-upload--picture-card">
													<img @click="handlePictureCardPreview(imageItem)" :src="imageItem.thumbUrl" class="avatar" border="0" :alt="imageItem.imageName">
												</div>
											</div>
											<div style="padding: 10px; text-align: center;width: 128px;">
												<span>{{imageItem.imageName}}</span>
											</div>
										</el-card>
									</el-col>
								</ul>
							</el-col>
							
						</el-tab-pane>
						
						
						<el-tab-pane label="收款返点" name="account">
							<div style="margin-top: 30px;">
								<el-collapse v-model="activeNames" accordion>
									<el-collapse-item :key="index" v-if="item.status !== 2 || item.id == aid" v-for="(item, index) in detail.accounts" :name="item.id">
										
										<template slot="title">
											{{ item.accountName }}账户{{ item.isDelete === 1 ? '(已删除)' : '' }}
											<el-tag v-if="isMaster !== '1' && item.id == aid && item.status === 0" type="danger">
												审核账户
											</el-tag>
										</template>
										
										
										<el-row>
											<el-col :span="10" class="offset-left">
												<el-form label-width="140px" style="margin: 20px 0 0 20px; color: #304157;">
													<el-row>
														<div class="grid-content bg-purple">
															<el-form-item label="账户用途">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.purposeName">
																</el-input>
															</el-form-item>
														</div>
														<div class="grid-content bg-purple">
															<el-form-item label="账户类型">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.typeName">
																</el-input>
															</el-form-item>
														</div>
													</el-row>

													<el-row>
														<div class="grid-content bg-purple">
															<el-form-item label="账户姓名">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.accountName">
																</el-input>
															</el-form-item>
														</div>
														<div class="grid-content bg-purple">
															<el-form-item label="身份证号">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.accountIdno">
																</el-input>
															</el-form-item>
														</div>
													</el-row>
													<el-row>
														<div class="grid-content bg-purple">
															<el-form-item label="借记卡号">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.accountNo">
																</el-input>
															</el-form-item>
														</div>
														<div class="grid-content bg-purple">
															<el-form-item label="开户银行">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.bankName">
																</el-input>
															</el-form-item>
														</div>
													</el-row>
													<el-row>
														<div class="grid-content bg-purple">
															<el-form-item label="开户支行">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.branchBankName"></el-input>
															</el-form-item>
														</div>
														<div class="grid-content bg-purple">
															<el-form-item label="开户城市">
																<el-input size="mini" :disabled="true" style="width: 320px" :value="item.cityName">
																</el-input>
															</el-form-item>
														</div>
													</el-row>
												</el-form>
											</el-col>
											<el-col :span="13">
												<div style="color: #304157;overflow:auto;zoom:1;">
													<ul class="image" v-viewer style="opacity: 0;">
														<el-col tag="li" :span="6" v-for="imageItem of item.accountImages[0].imageList">
															<el-card :body-style="{ padding: '0px' }" style="height: 210px">
																<div class="avatar-uploader">
																	<div tabindex="0" class="el-upload el-upload--picture-card">
																		<img @click="handlePictureCardPreview(imageItem)" :src="imageItem.thumbUrl" class="avatar" border="0" :alt="imageItem.imageName">
																	</div>
																</div>
																<div style="padding: 10px; text-align: center;width: 128px;">
																	<span>{{imageItem.imageName}}</span>
																</div>
															</el-card>
														</el-col>
													</ul>
												</div>
											</el-col>
										</el-row>
										
										
										<div v-if="index !== 0 && (item.id != aid || item.status !== 0)">
											<hr color="#C0C0C0" style="border-width: 0.5px" />
											<div style="margin-top: 30px;">
												<span style="font-size: 18px; color: #304157; font-weight: bold;">审核意见</span>
												<el-form label-width="140px" style="margin: 20px 0 0 20px; color: #304157;">
													<el-form-item label="审核状态">
														({{ formatStatus(item.status).name }})
													</el-form-item>
													<el-form-item label="备注项目" v-if="item.status !== 0">
														<el-input :disabled="true" type="textarea" :value="item.auditRemark" style="width: 829px" resize="none" :rows="4"></el-input>
													</el-form-item>
												</el-form>
											</div>
										</div>
										<boss-audit-form v-if="isMaster !== '1' && item.id == aid && item.status === 0" ref="auditForm" :loading="loading" :dealer-id="id" :account-id="aid" :is-master="isMaster"></boss-audit-form>
										
									</el-collapse-item>
								</el-collapse>
							</div>
						</el-tab-pane>
						
					</el-tabs>
					
					<boss-audit-form v-if="isMaster === '1' && detail.dealerInfo.status === 0" ref="auditForm" :loading="loading" :dealer-id="id" :account-id="aid" :is-master="isMaster"></boss-audit-form>
					<div v-if="isMaster === '1' && detail.dealerInfo.status !== 0">
						<hr color="#C0C0C0" style="border-width: 0.5px" />
						<div style="margin-top: 30px;">
							<span style="font-size: 18px; color: #304157; font-weight: bold;">审核意见</span>
							<el-form label-width="140px" style="margin: 20px 0 0 20px; color: #304157;">
								<el-form-item label="审核状态">
									({{ formatStatus(detail.dealerInfo.status).name }})
								</el-form-item>
								<el-form-item label="备注项目">
									<el-input :disabled="true" type="textarea" :value="detail.dealerInfo.auditRemark" style="width: 829px" resize="none" :rows="4"></el-input>
								</el-form-item>
							</el-form>
						</div>
					</div>
					<div v-if="isMaster === '1' && detail.dealerInfo.status === 0">
						<el-button type="primary" size="mini" style="margin: 20px 160px" @click="submit">
							提&nbsp&nbsp交
						</el-button>
					</div>
					
				</template>
			</div>
		</div>
		<script type="text/javascript">
			document.domain = 'victorplus.cn';
		</script>
		<script src="/static/js/base/vue.js"></script>
		<script src="/static/js/base/viewer.js" type="text/javascript" charset="utf-8"></script>
		<script src="/static/js/base/v-viewer.min.js" type="text/javascript" charset="utf-8"></script>
		<script src="/static/js/base/element-ui.js"></script>
		<script src="/static/js/base/axios.js?v=1.0"></script>
		<script src="/static/js/base/util.js"></script>
		<script src="/static/js/page/dealer/dealerAuditDetail.js"></script>
		<script type="text/javascript">
			Vue.use(VueViewer.default, {
				defaultOptions: {
					inline: true
				}
			});
		</script>
	</body>

</html>`

**Comment by mirari** [comment]
你在两个地方写了v-viewer指令，又是inline模式的，肯定会渲染出两个viewer啊

**Comment by Lee66** [comment]
两渲染出来四个，我说的是一个会出现两个

**Comment by mirari** [comment]
给个完整的在线例子吧，这一大堆代码丢上来又运行不了，没法看
我这边直接出现两个是没有重复的
[https://codepen.io/mirari/pen/djYOav](https://codepen.io/mirari/pen/djYOav)
抽离多余的元素逐个排查下

**Comment by Lee66** [comment]
http://smallming.club/viewerTest/
在线的地址
这是我的qq 2987966029,不介意的话可以加一下

**Comment by mirari** [comment]
[https://jsfiddle.net/ph3vw24f/](https://jsfiddle.net/ph3vw24f/)
没有复现这个问题，建议你在复杂页面改用组件式引入，并且抽离多余内容逐步排查

**Comment by Lee66** [comment]
升级到1.2版本 有的时候的会创建2个viewer-container的问题消失了

**Comment by mirari** [comment]
好的，之前用指令写法时每次子元素变动都会重建，像el-table这种组件会在渲染时触发多次，现在应该没问题了
