### ISSUE TITLE
如何全屏的时候不自动切换图片

### ISSUE THREAD

**Issue by YoungY2** [mirari/v-viewer#310]
如何全屏的时候不自动切换图片

**Comment by YoungY2** [comment]
我设interval: 0虽然不会自动切换了，但是手动左右切换也不行了

**Comment by mirari** [comment]
这个估计是bug，需要去viewerjs上提issue

我看到有个类似的提交了
https://github.com/fengyuanchen/viewerjs/issues/608

目前的解决办法是把interval设置成一个极大值
