### ISSUE TITLE
版本v1.7.3对旧的1.x.x版本出现了兼容问题

### ISSUE THREAD

**Issue by cddsgtc** [mirari/v-viewer#311]
在引入css样式内容时报错。
如下图：
![v-viewer报错](https://github.com/mirari/v-viewer/assets/16315661/476c1130-e211-418c-bd5d-99bd299cf4ae)
在更改版本为=1.7.1后重新打包错误解决。

**Comment by mirari** [comment]
v-viewer声明了依赖viewerjs，但是pnpm安装时不会将viewerjs直接安装到node_modules目录下。为了统一效果，现在需要显式安装viewerjs本身。
`npm install v-viewer@legacy viewerjs`

之前版本的package.json里在dependencies声明了viewerjs，所以npm安装时不写也没问题。
其实打包时剥离viewerjs的最初原因是把css文件一起打包进js里会在nuxt等SSR框架下报错，所以将这部分逻辑改为用户自主控制了

**Comment by cddsgtc** [comment]
因为这个昨天上生产报错，今天来加班了。改成1.7.1虽然打包不报错，但是生产直接页面挂了。最少也得是1.6.x才行。哎。。。

**Comment by mirari** [comment]
非常抱歉发布时没考虑周全。在1.7.4中重新补充了dependencies，应该可以兼容npm以前的安装方式

**Comment by cddsgtc** [comment]
> 非常抱歉发布时没考虑周全。在1.7.4中重新补充了dependencies，应该可以兼容npm以前的安装方式

大家都吸取教训吧，这样的基本等同于破坏性更改还是从版本号上想办法打断比较好。
