### ISSUE TITLE
源码路径绝对路径

### ISSUE THREAD

**Issue by llspace8** [mirari/v-viewer#312]
插件打包后的文件 v-viewer/dist/v-viewer.js 文件中有 `Component.options.__file = "D:\\Workspaces\\Web\\Git\\v-viewer\\src\\component.vue"` 文件的源码路径绝对路径；
这会导致部分系统在进行安全性测试时 被误报为 泄露服务器绝对路径 的高危漏洞

**Comment by mirari** [comment]
版本是多少？v2版本更新到1.7.4，更换了编译工具，应该不会有这个问题了
