### ISSUE TITLE
手机端图片移动问题

### ISSUE THREAD

**Issue by happyyummy** [mirari/v-viewer#313]
在手机端移动图片时，图片会切换成之前缩放过的比例

**Comment by mirari** [comment]
viewerjs没有专门适配移动端，默认应该是没法拖动图片的
如果是自己实现了类似的需求，可以尝试关闭双击还原的配置项[toggleondblclick](https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#toggleondblclick)
还有就是如果使用了指令方式，可以尝试加入[static](https://github.com/mirari/v-viewer?tab=readme-ov-file#static)修饰符避免dom改变触发重载

**Comment by mirari** [comment]
如果你指的是切换图片时的新图展示比例，这个默认就是初始值0.9
可以通过[initialCoverage](https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#initialcoverage)配置项修改

**Comment by happyyummy** [comment]
in ./node_modules/v-viewer/dist/index.mjs

Module parse failed: Unexpected token (16:10)
You may need an appropriate loader to handle this file type.
现在又报这个错，应该安装什么loader呀

**Comment by happyyummy** [comment]
"v-viewer": "^3.0.13",   "viewerjs": "^1.11.6",  "vue": "^2.5.2", "webpack": "^3.6.0",

**Comment by mirari** [comment]
vue2需要安装legacy版本，不能使用3.x
`pnpm i v-viewer@legacy`

**Comment by happyyummy** [comment]
谢谢大佬，移动端也可用！
