### ISSUE TITLE
请问点击图片后，大图是从中间中心位置飞入放大，可以从底部飞入吗？

### ISSUE THREAD

**Issue by idealshan** [mirari/v-viewer#316]
请问点击图片后，大图是从中间中心位置飞入放大，可以从底部飞入吗？

**Comment by mirari** [comment]
viewer没有提供这样的配置。
可能需要fork项目修改源码实现了

**Comment by idealshan** [comment]
多谢大佬的解答，请问能指导一下修改那些部分嘛？

**Comment by mirari** [comment]
https://github.com/fengyuanchen/viewerjs/blob/cf6fb29a6bef0577cecad18a25770403c89a579d/src/js/render.js#L223

应该是在这附近，参考initialCoverage改动

**Comment by idealshan** [comment]
多谢大佬的解答，对initialCoverage改动，是要重新编译吧？

**Comment by mirari** [comment]
是的
initialCoverage只是初始比例，要改变位置得自己增加参数

**Comment by idealshan** [comment]
多谢大佬的解答！

**Comment by mirari** [comment]
不是大佬，只是套了个壳。这种定制还真帮不上什么忙

**Comment by idealshan** [comment]
研究了一中午也没搞定，我在vscode中打包总是出错。
大佬能否给改一个。

**Comment by mirari** [comment]
这个在原基础上改还是很麻烦的，高定制的需求还是找其他工具吧

修改源码涉及的参数也很多，一时半会搞不定。
可以尝试自己覆盖样式和加css动画，以下供参考：
https://codepen.io/mirari/pen/WNmywEw
