### ISSUE TITLE
vue2  v-viewer compile  error

### ISSUE THREAD

**Issue by craftlkhugetree** [mirari/v-viewer#318]
in ./node_modules/v-viewer/dist/index.mjs

Syntax Error: Unexpected token, expected ( (16:10)

  14 |     e[O] = void 0;
  15 |     var n = !0;
> 16 |   } catch {
     |           ^
  17 |   }

**Comment by xd15332538931** [comment]
你要 vue中 我使用 npm install v-viewer@legacy viewerjs 安装后 运行正常 使用compoment 形式引入时  报错Syntax Error: no such file or directory, open 'D:\companyProject\web_wmsn\node_modules\v-viewer\dist\v-viewer.js'

**Comment by mirari** [comment]
> 你要 vue中 我使用 npm install v-viewer@legacy viewerjs 安装后 运行正常 使用compoment 形式引入时 报错Syntax Error: no such file or directory, open 'D:\companyProject\web_wmsn\node_modules\v-viewer\dist\v-viewer.js'

较新版本的v-viewer，入口脚本不是这个路径。检查代码中是否显示指定了引入路径：
```
import VueViewer from 'v-viewer\dist\v-viewer.js'
```
改成
```
import VueViewer from 'v-viewer'
```
