### ISSUE TITLE
通过标签引入的形式，出现组件失效，无法使用。

### ISSUE THREAD

**Issue by Zhx-Chenailuoding** [mirari/v-viewer#319]
作者你好，我想问一下，我在一个el-dialog里面的el-upload组件嵌套了v-viewer，然后在第一次打开el-dialog的时候，是可以正常打开v-viewer的，关闭el-dialog后，再打开，就无法打开v-viewer了。请问这要怎么解决

**Comment by mirari** [comment]
需要补充信息，比如是用组件、指令还是api调用，环境、版本号等等，最好是提供复现案例
参考：
https://codepen.io/mirari/pen/mdJpGzv

**Comment by Zhx-Chenailuoding** [comment]
用组件调用的。v-viewer@1.6.4 vue2环境。

**Comment by mirari** [comment]
对照例子里的代码，例子就是放在dialog内部的
