### ISSUE TITLE
底部按钮只有5个无法增加

### ISSUE THREAD

**Issue by sun82878380** [mirari/v-viewer#322]
使用的版本是1.6.4,只有5个按钮,可以控制这五个按钮"zoomIn", "zoomOut", "oneToOne","rotateLeft", "rotateRight"的增减,其他按钮无法增加,是什么原因
![QQ截图20240410160403](https://github.com/mirari/v-viewer/assets/88037529/e15e6ed7-97c9-4ffc-8dff-3a805bee36e2)
![QQ截图20240410160423](https://github.com/mirari/v-viewer/assets/88037529/c9d6dea5-efd2-41e0-b3eb-c2728cf91b25)

**Comment by mirari** [comment]
在toolbar这个属性里面定义按钮
https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#toolbar

也可以参考例子自定义
https://codepen.io/mirari/pen/GRMBrBv
