### ISSUE TITLE
vue中 使用component 怎么监听图片移动以及缩放

### ISSUE THREAD

**Issue by xd15332538931** [mirari/v-viewer#324]
<viewer
        :images="images"
        :options="options"
        class="viewer"
        ref="viewer"
        @move="moveFun"
        v-if="images && images.length"
        style="width: 500px;height: 670px;"
      >
        <img
          v-for="{source, thumbnail} in images"
          :src="thumbnail"
          :data-source="source"
          :key="source"
          class="image"
        >
      </viewer>
      
      methods:{
            moveFun(event){
            console.log('移动',event)
        },
      }
      vue2中我这样绑定 移动图片触发的事件 移动图片时 moveFun函数没有 执行 
      我想监听 图片放大 缩小 执行一些逻辑 如何绑定相关事件呢

**Comment by mirari** [comment]
这些事件是从dom元素上发起的，不是viewer组件的自定义事件。使用组件形式时，需要加上.native后缀
```
@move.native="onMove"
```

**Comment by xd15332538931** [comment]
我设置了@move.native="onMove" 还是没有执行 没作用

**Comment by xd15332538931** [comment]
使用你那个例子可以 但是在我的系统里面就不起作用

**Comment by xd15332538931** [comment]
<template>
    <viewer
        :images="images"
        :options="options"
        class="viewer"
        ref="viewer"
        @inited.native="inited"
        @move.native="onMove"
        v-if="images && images.length"
        style="width: 500px;height: 670px;"
      >
        <img
          v-for="{source, thumbnail} in images"
          :src="thumbnail"
          :data-source="source"
          :key="source"
          class="image"
        >
      </viewer>

  </template>

**Comment by mirari** [comment]
那就需要你提供一个最简复现案例了

使用组件的问题已经解决了？那我关闭上一个issue了

**Comment by xd15332538931** [comment]
使用组件的那个一直都是提示那个报错 组件未引入   import Vue from "vue";
  import Viewer from "v-viewer";
  import "viewerjs/dist/viewer.css";
  Vue.use(Viewer); 我只有使用这样的方式才能使用
