### ISSUE TITLE
使用组件引入如何在固定框之间放大缩小

### ISSUE THREAD

**Issue by xd15332538931** [mirari/v-viewer#325]
我想咨询下 我设置了  inline: true,  固定一个宽高框 移动图片 图片不能全部移出固定的框  缩小图片的时候 根据条件 缩小到一定程度 就不能缩小了 具体怎么实现？

**Comment by xd15332538931** [comment]
![Uploading 缩放图片.jpeg…]()

**Comment by xd15332538931** [comment]
![缩放图片](https://github.com/mirari/v-viewer/assets/118961373/17d216f8-2121-4811-bb53-fabaa35ba5d9)

**Comment by mirari** [comment]
需求可能无法完美满足，这需要viewerjs支持

目前只能监听缩放和移动事件，在操作完成后移动回屏幕或调整到最小大小
参考
https://github.com/mirari/v-viewer/issues/325#issuecomment-2054294146

**Comment by xd15332538931** [comment]
非常感谢 我还想问下 怎么让图片横向 或者纵向 充满整个预览框 我看原来的都左右都会存在margin  我如果修改样式 增加margin-left:0 !important 那么 图片就不能向左移动 左边margin始终都是0  怎么能让图片刚开始展示的时候 左右两边没有间距 充满这个预览框呢？

**Comment by mirari** [comment]
目前viewerjs应该也没有原生的方法支持，你需要自己计算倍率，再用zoom方法调整图片尺寸
