### ISSUE TITLE
重新定义reset事件

### ISSUE THREAD

**Issue by xd15332538931** [mirari/v-viewer#327]
我想实现  初始时候 viewer-canvas 中 ratio 放大比例为1 经过一系列操作 再点击reset 重置后 还是恢复到初始 viewer-canvas 中 ratio 放大比例为1 的样子 改怎么实现

**Comment by mirari** [comment]
初始比例可以用[initialcoverage](https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#initialcoverage)
或者考虑在重置后再执行一个zoom方法

不过，高度自定义的查看器用viewer强上可能并不适合

**Comment by xd15332538931** [comment]
好的 感谢
