### ISSUE TITLE
import 'viewerjs/dist/viewer.css' 提示找不到

### ISSUE THREAD

**Issue by ZhipengYang0605** [mirari/v-viewer#328]
跑项目的时候提示找不到该css文件
This dependency was not found:
* viewerjs/dist/viewer.css in ./src/main.js
To install it, you can run: npm install --save viewerjs/dist/viewer.css

项目中相关版本信息：
node：v16.14.2
npm：8.5.0
v-viewer: "^1.5.1"

**Comment by mirari** [comment]
需要显式安装viewerjs

**Comment by ZhipengYang0605** [comment]
安装viewerjs后已解决该问题
