### ISSUE TITLE
modal模式下怎么做到 pre和next监听(主要是键盘事件的自定义)

### ISSUE THREAD

**Issue by weifengliuhen** [mirari/v-viewer#332]
找了半天只有toolbar的prev和next
    
    const $viewer = VueViewer.api({
      images: sourceImages,
      options: {
        button:false,
        toolbar:{ 
          prev: { show: true,  click: (e)=>{
            $viewer.prev(true);
            console.log(e)
          } },
          next:{ show: true,  click: (e)=>{
            $viewer.next(true);
            console.log(e)
          } }
        },
        navbar:false,
        viewed: (e)=> {
          //console.log(e)
          sourceImages.push(this.images[this.tmp++])
          $viewer.image.addEventListener("keyown",()=>{
            console.log($viewer)
          })
        },
        ready:(e)=>{

        }
      } 

    })

**Comment by mirari** [comment]
监听事件？api模式下只能在options里定义回调
组件和指令都可以在元素上直接监听这两个事件
