### ISSUE TITLE
open inline in a specific div

### ISSUE THREAD

**Issue by lord-zeus** [mirari/v-viewer#34]
i want the image to open inline in a specific div so that i add more content by the side 
how can i do that ? thanks

**Comment by mirari** [comment]
Use `inline` mode, and separate the trigger and the viewer in different elements.
`inline` mode will create viewer in the specific div instead of body.
[https://github.com/fengyuanchen/viewerjs#inline](https://github.com/fengyuanchen/viewerjs#inline)
