### ISSUE TITLE
如何通过API退出当前预览

### ISSUE THREAD

**Issue by dinggeonly** [mirari/v-viewer#346]
通过以下代码启动预览
如何通过API主动退出预览
let images= [{……},{……}]
  viewerInstance.value = viewerApi({
    options: {
      navbar: false,
      toolbar: true,
      title: false,
      url: ‘imgUrl’,
      initialViewIndex: 1
    },
    images: images
  })

**Comment by mirari** [comment]
执行实例的hide方法
https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#hideimmediate
