### ISSUE TITLE
vite打包v-viewer有问题

### ISSUE THREAD

**Issue by wang-xing-fei** [mirari/v-viewer#347]
![image](https://github.com/user-attachments/assets/cc4db9d1-9319-4ae2-9c03-7c8cbad14f56)

**Comment by mirari** [comment]
看上去是脚手架无法处理css的引入，或者viewerjs的css没有位于node_modules目录下

需要显式引入viewerjs，才能在代码中引入css
或者需要新建.npmrc文件并声明shamefully-hoist=true

**Comment by wang-xing-fei** [comment]
已经解决了没有npm instoll 发自我的 iPhone在 2024年9月25日，16:46，mirari ***@***.***> 写道：﻿
看上去是脚手架无法处理css的引入，或者viewerjs的css没有位于node_modules目录下
需要显式引入viewerjs，才能在代码中引入css
或者需要新建.npmrc文件并声明shamefully-hoist=true
