### ISSUE TITLE
image只能设置图片大小，不能设置预览大小

### ISSUE THREAD

**Issue by dongze1** [mirari/v-viewer#348]
c
<template>
  <div id="app">
    <div v-viewer="options" class="images" ref="viewer">
      <img :src="'http://127.0.0.1:9999test.png'"
        class="image"
        :data-src="'http://127.0.0.1:9999test.png'"
        alt="Certificate Image" />
    </div>
  </div>
</template>

<script>
import 'viewerjs/dist/viewer.css';
import VueViewer from 'v-viewer';
import Vue from 'vue';

Vue.use(VueViewer);

export default {
  data() {
    return {
      options: {
        ready: () => {
          this.viewerInstance = this.$refs.viewer.$viewer;
        },
        inline: false,
        viewed(e) {
        },
        zoom(e) {
          e.detail.ratio = Math.min(e.detail.ratio, 596.84 / this.viewerInstance.imageData.naturalWidth);
        },
        toolbar: {
          oneToOne: true,
          prev: {
            show: true,
            size: 'large',
            click: () => {
              this.viewerInstance.prev(true);
            }
          },
          zoomIn: {
            size: 'large',
          },
          zoomOut: {
            size: 'large',
          },
          oneToOne: {
            show: false,
          },
          reset: {
            show: false
          },
          prev: {
            show: false
          },
          play: {
            show: false
          },
          next: {
            show: false
          },
          rotateLeft: {
            size: 'large',
          },
          rotateRight: {
            size: 'large',
          },
          }
        }
      },
    };
  },
  methods: {
    fixZoom() {
      const image = this.viewerInstance.image;
      if (image) {
        image.style.width = '596.84px';
        image.style.height = '844.16px';
      }
    }
  }
};

</script>

<style>
.images {
  height: 500px;
}

.image {
  height: 200px;
  cursor: pointer;
  margin: 5px;
  display: inline-block;
}

</style>
预设的images只能调整外部图片尺寸，能否像el-image-viewer一样通过.el-image-viewer__canvas 固定预览后的图片尺寸596.84px*844.16px且在中心呢

**Comment by mirari** [comment]
只能传入initialCoverage参数设置默认比例，无法固定尺寸
