### ISSUE TITLE
使用api的形式打开图片数组，怎么确保当前预览的是点击的图片

### ISSUE THREAD

**Issue by wmlcloude** [mirari/v-viewer#350]
我的场景是我有一个图片数组，当我点击页面的图片预览当前图片，同时可以切换查看其他图片，现在问题是，每当我点击当前图片，预览的开始始终是第一张图片

`viewerApi({
    images
  })`

**Comment by mirari** [comment]
在options里传入initialviewindex
https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#initialviewindex

**Comment by wmlcloude** [comment]
> 在options里传入initialViewIndex https://github.com/fengyuanchen/viewerjs?tab=readme-ov-file#initialviewindex

已解决，给作者点赞加star
