### ISSUE TITLE
Fix typings

### ISSUE THREAD

**Issue by skyxuanxuan** [mirari/v-viewer#351]
Switched to extending vue instead of @vue/runtime-core as recommended in the official docs. Currently, it breaks type checking and throws a lot of type errors when this library is included.

[https://vuejs.org/guide/extras/web-components#web-components-and-typescript](https://vuejs.org/guide/extras/web-components#web-components-and-typescript)

**Comment by mirari** [comment]
Thank you for the feedback. Can you submit a PR?
It looks like I just need to change it like this?
`types/index.d.ts`
```
declare module 'vue' {
  interface ComponentCustomProperties {
    $viewerApi: typeof api
  }
}
```
