### ISSUE TITLE
怎么排除某些不想显示的图片呢

### ISSUE THREAD

**Issue by jocongmin** [mirari/v-viewer#36]
v-viewer 标签里面有些不想显示，比如头像之类的，怎么排除呢

**Comment by mirari** [comment]
[使用过滤器](https://github.com/fengyuanchen/viewerjs#filter)

**Comment by Lee66** [comment]
使用过滤器之后如果从不想显示的图片开始点的话还是会弹出窗口，过滤掉了怎么还会弹窗口。如果从没有过滤掉的图片点的话正常

**Comment by mirari** [comment]
我试了下filter功能是可以正常使用的，确认下filter函数是否配置正确
[示例](https://codepen.io/mirari/pen/vvPoQb)
