### ISSUE TITLE
为什么要组件重新渲染后才能起作用呢

### ISSUE THREAD

**Issue by jocongmin** [mirari/v-viewer#37]
比如一个会话框，我重新输入会话后，会话框里面的图片才能放大，说明重新渲染了组件，那个图片放大器，才起作用，这怎么解决呢

**Comment by mirari** [comment]
没听懂，看下代码吧，或者最好弄个在线例子
参考[https://codepen.io/mirari/pen/PePrVq](https://codepen.io/mirari/pen/PePrVq)
