### ISSUE TITLE
通过接口拉取图片，然后向图片数组push新的图片，点击图片只能出现遮罩，图片不显示

### ISSUE THREAD

**Issue by Junezm** [mirari/v-viewer#39]

**Comment by mirari** [comment]
在线例子就是用push加图片的，没有出现问题
贴下代码吧，参考[https://codepen.io/mirari/pen/PePrVq](https://codepen.io/mirari/pen/PePrVq)

**Comment by mirari** [comment]
[https://codepen.io/mirari/pen/WgRrzb](https://codepen.io/mirari/pen/WgRrzb)
这个是用组件的例子，运行正常啊
```
<viewer :images="images"> <img v-for="src in images" :src="src" :key="src"> </viewer>
```
