### ISSUE TITLE
问题：PPT或者白板直播场景中：单张图片动态替换，每次切图会出现缩放，体验很不好

### ISSUE THREAD

**Issue by web525** [mirari/v-viewer#4]
应用场景：PPT或者白板直播
问题：每次切图会出现缩放
要实现的效果：切图直接替换，不要有任何效果，让用户感觉是在播放白板直播视频一样。
尝试：尝试去掉for循环，直接换图，但是src切换，组件都会重建。viewer-transition的动画也不能删除，删除后就缩放就很生硬

**Comment by mirari** [comment]
图片第一次加载时是按原尺寸显示的，这是viewer.js的设置，这里只是套了层壳，需要在那边修改。
类PPT的应用建议使用swiper之类的插件。
