### ISSUE TITLE
如何只去掉图片切换时候的动画

### ISSUE THREAD

**Issue by tomdong** [mirari/v-viewer#40]
这个组件做得很棒，先给作者点个赞。
我在使用的过程中，感觉里面的动画过渡效果很好，比如旋转、缩放时候的动画，但是当切换图片列表上一张下一张的时候，那个从中间缩放出来的效果我不想要，但是我想保留其他的动画效果。
目前只找到一个transition属性来开关所有的动画效果，但是没有办法只去掉图片切换时候的动画。

想请教如何做到，谢谢！

**Comment by mirari** [comment]
这个需求得去[viewer.js](https://github.com/fengyuanchen/viewerjs/issues)那边提，这里只是封装成了vue组件。
目前好像不支持单独去掉动画。

**Comment by tomdong** [comment]
好的，明白！多谢！
