### ISSUE TITLE
how to shown the original image when user click on any image

### ISSUE THREAD

**Issue by usmanjdn93** [mirari/v-viewer#42]
for initial view i set the **thumbnail images** but when user click on any image then i want to shown **original image**

**Comment by mirari** [comment]
Example source:
[directive](https://github.com/mirari/v-viewer/blob/master/example/views/example/DirectiveExample.vue)
[component](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue)

Document:
[viewer.js](https://github.com/fengyuanchen/viewerjs)

**Comment by usmanjdn93** [comment]
Thank's it work...
