### ISSUE TITLE
为什么vue版本的viewer不能拖拽图片了呢？

### ISSUE THREAD

**Issue by 941477276** [mirari/v-viewer#43]
为什么vue版本的viewer不能拖拽图片了呢？之前使用jQuery版本的是可以拖拽图片的！

**Comment by 941477276** [comment]
我用的是指令的形式，这种方式时候拖拽不了，使用template的方式确实可以拖拽

**Comment by mirari** [comment]
[https://codepen.io/mirari/pen/PePrVq](https://codepen.io/mirari/pen/PePrVq)
[https://mirari.cc/v-viewer/](https://mirari.cc/v-viewer/)
这两个都有指令用法，都可以拖拽
