### ISSUE TITLE
viewer.css

### ISSUE THREAD

**Issue by StephenWu5** [mirari/v-viewer#48]
import 'viewerjs/dist/viewer.css'
viewer.css 找不到哦

**Comment by lxk0301** [comment]
你解决了吗? 我npm依赖包后  直接报错 
![image](https://user-images.githubusercontent.com/21308593/48893331-12e22a00-ee7b-11e8-90e2-a72f03eabdd4.png)

**Comment by mirari** [comment]
我刚刚用vue-cli 3.0新建了一个项目测试过没有问题啊
检查你的node_modules目录是否存在viewerjs，正常情况下安装v-viewer就会带上

**Comment by lxk0301** [comment]
> 我刚刚用vue-cli 3.0新建了一个项目测试过没有问题啊
> 检查你的node_modules目录是否存在viewerjs，正常情况下安装v-viewer就会带上

@mirari 这个肯定是node_modules目录是存在viewerjs,使用的命令npm install v-viewer --save
但是我找到node_modules里面, dist目录是没有viewer.css这个文件,不知道是不是你上传到npm的时候. 漏掉了这个文件,下面放v-viewer截图
![image](https://user-images.githubusercontent.com/21308593/48925794-b7f41580-ef02-11e8-85b2-0584959f174c.png)

**Comment by mirari** [comment]
用npm或者yarn安装时都会同时添加依赖的viewerjs到node_modules目录下

**Comment by lxk0301** [comment]
嗯,应该是我的原因了 我这边npm被我搞坏了,  导致,只下载了v-viewer这个包,  缺失了viewerjs这个包
