### ISSUE TITLE
当图片超过5M时，会出现图片加载到一半突然全部消失的问题

### ISSUE THREAD

**Issue by Qio-fairy** [mirari/v-viewer#49]
您好，我在使用您的组件时，出现了一个小问题：当图片超过5M（甚至更大）时，会出现图片加载到一半突然全部消失，等候1s（或更久）才全部弹出的问题。之前使用viewerjs时没遇见过相同情况，不知是不是Vue渲染的问题？

**Comment by mirari** [comment]
跟vue应该没有关系。这只是个壳，实际操作跟直接调用viewerjs没有区别。
我找了张5M的大图在弱网环境模拟了一下，没有发现问题。
如果你说的是图片会先按原始大小展现出来并加载，等加载完以后再突然出现到屏幕中央动画放大展现的话，这个默认样式是viewerjs控制的，现在它的官网demo上用弱网模拟一样也可以看到相同效果。

如果想要让图片loading时只显示转圈图标，等图片加载完再展现，自己加一句全局样式就行：
```
.viewer-loading > img {
  display: none;
}
```

**Comment by Qio-fairy** [comment]
谢谢您的解答！确实是等图片加载完成后再展现，就不会出现图片消失的问题了。
