### ISSUE TITLE
请问下，我能不能控制的页面展示的图片和点击打开浏览的图片大小不同？

### ISSUE THREAD

**Issue by zhangwei900808** [mirari/v-viewer#5]
意思是这样的，我页面html展示的时候是200X200，但是，我使用你们插件浏览的时候显示是原图大小，这个能控制吗，现在是浏览和展示的大小都是200X200了
![image](https://user-images.githubusercontent.com/4385154/33418500-2296b58c-d5e1-11e7-9ea7-71da8f252e5d.png)

**Comment by mirari** [comment]
示例代码就展示了缩略图和原图的使用方式。
https://github.com/mirari/v-viewer/blob/master/example/views/example/DirectiveExample.vue
详细使用查阅viewer.js的文档，v-viewer只是套了个壳。

如果你说的是css限制了图片的宽高，那就给你的css附加条件来区分。
