### ISSUE TITLE
Bounds 

### ISSUE THREAD

**Issue by Rim-777** [mirari/v-viewer#50]
Hi, Thank you for the great work. 
I'd like to try to use the plugin for displaying examples but I need  the option to keep image inside a container.
I mean when edges of a picture can't be moved inside a container  
is there a way to set bounds to keep zoomed image inside a container?

**Comment by mirari** [comment]
It's a very useful advice, but it doesn't seem to support it now. 
You can make a feature request on [viewer.js](https://github.com/fengyuanchen/viewerjs/issues).
