### ISSUE TITLE
指令形式使用时动态修改option

### ISSUE THREAD

**Issue by zmqcherish** [mirari/v-viewer#54]
以组件形式使用时可以动态的修改options变量
`<viewer :options="options" :images="images" ...`
只要修改options变量就可以实现了。

以指令形式时该如何实现？

**Comment by mirari** [comment]
稍候增加此功能

**Comment by mirari** [comment]
1.3.1已发布，添加了对指令传值对象的监听
指令值如果是字面量和表达式的话目前无法监听，考虑以后改变监听方式
