### ISSUE TITLE
为什么不支持prev，next的显示隐藏呢？

### ISSUE THREAD

**Issue by dusksoft** [mirari/v-viewer#56]
为什么不支持prev，next的显示隐藏呢？

**Comment by mirari** [comment]
这个需求得去[viewer.js](https://github.com/fengyuanchen/viewerjs/issues)提了，不过实现应该不复杂，也可以自己fork以后修改一下

**Comment by 851091009** [comment]
抱歉来晚了，已经实现标题说的，支持prev，next的显示隐藏。
v-viewer 版本 ：1.5.1
实现方法：
配置 toolbar ：
`viewerOptions: {
                    inline: true,
                    button: true,
                    navbar: false,
                    title: false ,
                    toolbar: {
                        zoomIn: 4,
                        zoomOut: 4,
                        oneToOne: 4,
                        reset: 4,
                        rotateLeft: 4,
                        rotateRight: 4,
                        flipHorizontal: 4,
                        flipVertical: 4,
                    },
                    tooltip: true,
                    movable: true,
                    zoomable: true,
                    rotatable: true,
                    scalable: true,
                    transition: true,
                    fullscreen: true,
                    keyboard: true,
                    url: 'data-source'
                },`

![Uploading 微信截图_20200806105853.png…]()
