### ISSUE TITLE
退出全屏时TypeError: Document not active

### ISSUE THREAD

**Issue by losymear** [mirari/v-viewer#57]
退出全屏时TypeError: Document not active

**Comment by myqianlan** [comment]
同意的错误

**Comment by mirari** [comment]
无法复现此问题，请提供运行环境和操作步骤等相关描述，不然无从定位问题

**Comment by mirari** [comment]
[https://codepen.io/mirari/pen/LmJRxK](https://codepen.io/mirari/pen/LmJRxK)
确认一下你打开这个例子是否会出现错误提示。
我这里用Chrome 71试了下没有问题。
document.fullscreen这整段都是出于最大兼容性目的，并不应该会影响到代码的执行。

**Comment by Skasi** [comment]
Looks like `Document not active` was fixed in viewerjs v1.3.2: https://github.com/fengyuanchen/viewerjs/releases/tag/v1.3.2

**Comment by mirari** [comment]
@Skasi 
Thank you for your notice.
v-viewer@1.4.0 released, the version of viewerjs was upgraded to 1.3.2, try later pls
