### ISSUE TITLE
ios 图片横拍,Orientation 属性 没有处理,在ios 上获取的宽度和高度正确,但是放大的时候,图片被旋转,导致错误

### ISSUE THREAD

**Issue by wp56610** [mirari/v-viewer#59]
ios 图片横拍,Orientation 属性 没有处理,在ios 上获取的宽度和高度正确,但是放大的时候,图片被旋转,导致错误

1.bug 重现, 使用ios 拍摄两张图片, 一张手机正拍,一张手机旋转90%再次拍摄, 上传后使用v-viewer ,在ios 上会出现一张图片被旋转,被错误缩放的问题, 
2.解决方法 识别ios 图片 Orientation 属性,在获取图片尺寸前,正确的处理旋转,再获取图片和缩放

**Comment by mirari** [comment]
之前没有遇到过这种场景，但是这个得去[viewer.js](https://github.com/fengyuanchen/viewerjs/issues)上提issue了，v-viewer只是套了个壳子
