### ISSUE TITLE
在inited函数里面不能执行zoomTo?加了延时就可以

### ISSUE THREAD

**Issue by LeftShoot** [mirari/v-viewer#60]
![image](https://user-images.githubusercontent.com/15210772/51881739-2d72db00-23b7-11e9-91d3-2659acd4bbd7.png)

**Comment by mirari** [comment]
inited事件只表示viewer实例初始化完成，不意味着图片已经加载完。要执行zoom方法，必须在viewer初始化且当前图片已经载入并显示之后，需要在viewed回调里执行动作
参考例子：
[https://codepen.io/mirari/pen/ZwpGBO](https://codepen.io/mirari/pen/ZwpGBO)

**Comment by LeftShoot** [comment]
> inited事件只表示viewer实例初始化完成，不意味着图片已经加载完。要执行zoom方法，必须在viewer初始化且当前图片已经载入并显示之后，需要在viewed回调里执行动作
> 参考例子：
> https://codepen.io/mirari/pen/ZwpGBO

文档有体现吗？不知道有这个写法呢。。。

**Comment by mirari** [comment]
[https://github.com/fengyuanchen/viewerjs](https://github.com/fengyuanchen/viewerjs)
这只是一个壳，文档要去[viewer.js](https://github.com/fengyuanchen/viewerjs)看
