### ISSUE TITLE
Mask layer problem

### ISSUE THREAD

**Issue by AshMica** [mirari/v-viewer#61]
When you use v-viewer to magnify a picture on an element component, the image's mask layer has a chance to appear behind the window.

**Comment by StudyForZX** [comment]
YES,I also have this problem.It use append-to-body when  elementUI has two dialogs.I think it is the same problem.

**Comment by mirari** [comment]
I didn't quite catch your meaning but I also think `append-to-body` can resolve this problem. 
Maybe you can modify this example and show it to me.
[https://codepen.io/mirari/pen/pYeQjP](https://codepen.io/mirari/pen/pYeQjP)
