### ISSUE TITLE
How to use with vuetify <v-img> ?

### ISSUE THREAD

**Issue by dogrocker** [mirari/v-viewer#62]
With `<v-img>` support lazy load img by default.
Is this posible integrate to vuetify `<v-img>` ?

Thanks.

**Comment by mirari** [comment]
`viewer.js  support lazy load too.

Example source:
[directive](https://github.com/mirari/v-viewer/blob/master/example/views/example/DirectiveExample.vue)
[component](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue)

Document:
[viewer.js](https://github.com/fengyuanchen/viewerjs#url)

**Comment by jofftiquez** [comment]
+1 for `v-img` usage.

**Comment by dogrocker** [comment]
I think using `url` is ok Thanks @mirari.
