### ISSUE TITLE
能否支持默认采用缩略图，放大采用原图

### ISSUE THREAD

**Issue by coder666666** [mirari/v-viewer#67]
开发中遇到用户上传图片较大，下载图片所需时间较长；能否支持两组图片地址，一组默认显示小图，另一组为真实图片地址，当用户点击的时候采用

**Comment by mirari** [comment]
Demo里就已经给出使用范例了：
[directive](https://github.com/mirari/v-viewer/blob/master/example/views/example/DirectiveExample.vue)
[component](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue)

文档:
[viewer.js](https://github.com/fengyuanchen/viewerjs#url)

**Comment by coder666666** [comment]
解决了，感谢感谢

**Comment by javaxiaobai** [comment]
是date-source属性中放置原图吗

**Comment by javaxiaobai** [comment]
@mirari 我试了一下怎么不行

**Comment by mirari** [comment]
看文档看例子啊，options里定义什么属性是原图
