### ISSUE TITLE
v-viewer能否设定固定高度？

### ISSUE THREAD

**Issue by zinwalin** [mirari/v-viewer#69]
如果是超长图片的话，整个viewer会占据网页的大部分高度。

**Comment by mirari** [comment]
用行内模式，viewer只会展示在容器以内

**Comment by zinwalin** [comment]
> 用行内模式，viewer只会展示在容器以内

能否写个例子？ 感谢。

**Comment by mirari** [comment]
[https://mirari.cc/v-viewer/](https://mirari.cc/v-viewer/)
例子第二个就是啊

**Comment by zinwalin** [comment]
> https://mirari.cc/v-viewer/
> 例子第二个就是啊

感谢.
