### ISSUE TITLE
Console logs for directive

### ISSUE THREAD

**Issue by mmustra** [mirari/v-viewer#7]
Hi Mirari,

Console logs for directive are pretty annoying. If you really need them, is it possible to pass some value `{verbose : true}` through options that will show them, so that they are not showing by default?

Regards,
Marin

**Comment by mirari** [comment]
Console logs removed by default now, thank you for your advice.

**Comment by mmustra** [comment]
Thx Mirari. Will update package as soon as it gets available from npm.
