### ISSUE TITLE
是否可以没点击之前只显示加载一张缩略图，点击打开相册。

### ISSUE THREAD

**Issue by rancongjie** [mirari/v-viewer#74]
是否可以没点击之前只显示加载一张缩略图，点击打开相册。

**Comment by rancongjie** [comment]
类似相册封面，目前好像智能全部缩略图加载了，隐藏掉除第一张其他的。

**Comment by rancongjie** [comment]
如果有多个相册，就比较消耗loading 时间，请问有没有什么好办法，外部只加载一张缩略图片。

**Comment by mirari** [comment]
把触发介质跟相册本身分开。
受viewerjs的限制它的初始化只能是内部的`img`，但这些`img`可以不用显示出来。
参考例子：
[https://codepen.io/mirari/pen/vPoGbR](https://codepen.io/mirari/pen/vPoGbR)

**Comment by rancongjie** [comment]
@mirari  这些img 能否点击以后再初始化？ 只初始化加载第一张

**Comment by mirari** [comment]
例子给的就是啊

**Comment by rancongjie** [comment]
![image](https://user-images.githubusercontent.com/13307672/59189215-1c7b7700-8bac-11e9-8a00-46081a0c8280.png)
这里还是加载了 3张图片额

**Comment by rancongjie** [comment]
![image](https://user-images.githubusercontent.com/13307672/59189383-83992b80-8bac-11e9-87f6-3611b15b597c.png)
类似这种，我一个页面有很多个viewer事例，这样怎么给this.$x 赋值呢  😷。

**Comment by mirari** [comment]
这种情况可以给v-viewer组件再封装一层，用方法动态传递URL数组。
例子：
[https://codesandbox.io/embed/jvv2y26ov9](https://codesandbox.io/embed/jvv2y26ov9)

**Comment by rancongjie** [comment]
@mirari  感谢🙏

**Comment by wysdddh** [comment]
@mirari 感谢🙏🙏🙏
