### ISSUE TITLE
Initial rotate

### ISSUE THREAD

**Issue by MaTToX3** [mirari/v-viewer#76]
Is it possible to somehow set an initial rotate to an image? 

For example, I created custom buttons for rotating an image in viewer and they work - however calling the same method in @inited does nothing. 

I tried setting initial rotate with the help of CSS but that create a new rotated image out of viewer. 

Is there any solution to this?

**Comment by mirari** [comment]
Example:
[https://codepen.io/mirari/pen/ZwpGBO](https://codepen.io/mirari/pen/ZwpGBO)
Try to call `rotate` in the `viewed` callback. 
Notice that callback functions can only be configured in options now, do **not** use like this: `@viewed="onViewed"`

Doc:
[https://github.com/fengyuanchen/viewerjs#methods](https://github.com/fengyuanchen/viewerjs#methods)

**Comment by MaTToX3** [comment]
So simple! I went trough viewerjs docs and did not saw it. Damn.

Thanks again!
