### ISSUE TITLE
可以修改全局默认配置吗?

### ISSUE THREAD

**Issue by InkoiWong** [mirari/v-viewer#8]
我直接在main.js里面import 和 Vue.use后,我就可以在所有路由组件使用<viewer></viewer>了.可是可以修改全局默认配置吗,这样就不需要再在每个使用的地方都写一遍options.Viewer.setDefaults(options)用这个会报错
errMsg:Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_12_v_viewer___default.a.setDefaults is not a function

**Comment by InkoiWong** [comment]
还有可以有方法在点击缩略图的时候能够有点击时候的钩子函数吗

**Comment by mirari** [comment]
稍后会添加修改全局设置的功能。
文档需要查看[viewer.js](https://github.com/fengyuanchen/viewerjs)，有新需求也得在那边提，这里只是套个壳。
不过我觉得source没必要在点击时才配置，异步的话更会影响体验。

**Comment by InkoiWong** [comment]
蟹蟹您的回复
是的,我也是跟你一样这么认为的,只是需求>_<...
我们给图片的url设置了访问时间,每次超过了就要重新获取一个参数替换url里面的
能不能贴一点update API的demo代码,我不是很会使用,update应该也能解决我的问题,viewer.js那边关于update文档提出来了都没写东西和demo也没有,纠结,拜托拜托

**Comment by mirari** [comment]
viewer.js的update方法就是在图片元素的数量或属性发生改变的时候，重载viewer实例下的相关属性。
本来我也可以用update方法来实现v-viewer的双向绑定，但是viewer.js之前版本的update方法有不少问题，比如空元素时执行出错或者事件没有释放等情况，所以最后还是用了先destroy再重新初始化的做法。
如果页面不是很庞大的话，你的需求我觉得可以直接设置一个定时器，定时修改images数据源，用指令式的话只要元素内部发生了变化就应该会自动重建viewer，组件式的话也可以手动执行组件的createViewer方法。
