### ISSUE TITLE
本地图片不能显示

### ISSUE THREAD

**Issue by chenxiangjun2010** [mirari/v-viewer#80]
数组使用本地图片，显示不了，原因是在编译的时候，图片没有重新编译，导致使用本地图片的时候，路径出现了问题

**Comment by mirari** [comment]
`import img1 from './imgs/1.png'`
或者
const img1 = require('./imgs/1.png')

**Comment by chenxiangjun2010** [comment]
------------------ 原始邮件 ------------------
发件人: "mirari"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 下午5:20
收件人: "mirari/v-viewer"<v-viewer@noreply.github.com>;
抄送: "陈相军"<291493133@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [mirari/v-viewer] 本地图片不能显示 (#80)




import img1 from './imgs/1.png'
 或者
 const img1 = require('./imgs/1.png')
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.




谢谢你的解答，一开始没有以为是插件的问题，后来也发现是图片路径的问题，由于vue不是很熟悉，所以提了一个错误问题，已经自己关闭了
