### ISSUE TITLE
数据更新但是组件没有初始化

### ISSUE THREAD

**Issue by mzpuu** [mirari/v-viewer#81]
<viewer :images="imgList" @inited="inited" class="viewer images" ref="viewer">
...
</viewer>
inited (viewer) {
      this.$viewer = viewer
      this.$viewer.options.title=false
      this.$viewer.options.tooltip=false
      this.$viewer.options.keyboard=false
    }

我如何手动初始化一次viewer？
this.inited(this.refs.viewer.$viewer)会报错

**Comment by mirari** [comment]
最好能用例子复现一下数据更新但组件没初始化的情况，可以参考这个做在线例子：
[https://codepen.io/mirari/pen/vPoGbR](https://codepen.io/mirari/pen/vPoGbR)

修改options没必要用这种形式，例子里有动态传递options参数的用法：
[https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue)
