### ISSUE TITLE
如何设置小图使用缩略图地址, 大图使用原图地址

### ISSUE THREAD

**Issue by mxdwjcty** [mirari/v-viewer#82]

**Comment by mirari** [comment]
Demo里就已经给出使用范例了：
[directive](https://github.com/mirari/v-viewer/blob/master/example/views/example/DirectiveExample.vue)
[component](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue)

文档:
[viewer.js](https://github.com/fengyuanchen/viewerjs#url)
