### ISSUE TITLE
请问这个插件支持移动端吗，是否有兼容问题？我在华为nova2s上面测试，滑动图片预览窗口不能到下一张

### ISSUE THREAD

**Issue by 15927520307** [mirari/v-viewer#83]

**Comment by mirari** [comment]
在原版DEMO里测试一下
[https://fengyuanchen.github.io/viewerjs/](https://fengyuanchen.github.io/viewerjs/)
如果有问题需要提供复现环境描述到[原项目issue](https://github.com/fengyuanchen/viewerjs/issues)

**Comment by programmer-fly** [comment]
安卓下不能左右滑动切换图片，IOS系统是可以的
