### ISSUE TITLE
预览层会随着图片的更新主动关闭

### ISSUE THREAD

**Issue by zhixiaotong** [mirari/v-viewer#84]
需求：默认展示一些图片，点击打开预览效果的第一次会触发请求剩下的图片。
BUG：请求返回时，原先的预览效果会直接关闭掉，无法规避掉。

**Comment by mirari** [comment]
图片数据发生变化时，viewer实例会整个销毁重建。
如果需求是点击以后异步获取剩下的图片然后打开大图浏览，可以通过这种方案实现：
[https://codesandbox.io/embed/jvv2y26ov9](https://codesandbox.io/embed/jvv2y26ov9)
给v-viewer组件再封装一层，用方法动态传递URL数组

如果需求是在大图浏览过程中再动态加载后续图片，则需要先关闭v-viewer的动态感知，然后手动执行$viewer对象的update方法。
1. static关闭动态感知
```
<div class="images" v-viewer.static>
  <img v-for="src in images" :src="src" :key="src">
</div>
```
2.通知viewer更新
`this.$viewer.update()`
[https://github.com/fengyuanchen/viewerjs#update](https://github.com/fengyuanchen/viewerjs#update)

**Comment by zhixiaotong** [comment]
@mirari 现在我已经解决了闪退的问题了，现在的问题是打开预览图的情况下，如果手动触发update依然不会让新获取的图片被加载到预览图中，重新关闭预览再打开才能看得到。这个我给viewjs的作者也提了issue，但是他没有理睬。

**Comment by mirari** [comment]
好吧，我之前试了下直接触发update，那一瞬间重新读取到的所有img节点会被全部添加到当前预览窗口的底部图片列表里，点击任意一个图片以后才会显示正常，应该还是update没有处理好已打开的预览窗口的所有状态。如果有兴趣的话也许可以自己fork一个修正，然后发给作者。
其实我这里写成销毁重建也是因为之前发现单纯update会有问题，不如销毁重建稳定。

**Comment by zhixiaotong** [comment]
@mirari 谢谢，我联系了作者，我尝试用他说的在viewjs初始化时，声明viewed方法中调用update()，这个方式看上去有用，但是之前的图片没有清空，导致点击上一个或下一个图片会重复加载下面已有的图片，越来越多，BUG已经告诉作者了。

**Comment by mirari** [comment]
升级到1.5.1以后，默认配置可以直接通过更新images数组来更新视图，不会导致弹窗关闭了

**Comment by TerryChenUI** [comment]
> @mirari 谢谢，我联系了作者，我尝试用他说的在viewjs初始化时，声明viewed方法中调用update()，这个方式看上去有用，但是之前的图片没有清空，导致点击上一个或下一个图片会重复加载下面已有的图片，越来越多，BUG已经告诉作者了。

我也碰到异步请求获取原图，预览图还是旧的问题，请问最后是怎么解决的
