### ISSUE TITLE
请教监听上下一张按钮的功能

### ISSUE THREAD

**Issue by smileoneCXY** [mirari/v-viewer#86]
诚恳请教：想解决.pdf格式结尾的显示, 如果不能显示。还请教 如何在自己的vue页面 监听next按钮的方法,(我来自己判断剔除pdf文件)

**Comment by mirari** [comment]
传递数组的时候直接过滤掉pdf就行吧

**Comment by smileoneCXY** [comment]
抱歉我说明的问题是： 如果当前这一张是pdf  我就用浏览器的链接 弹出来给他看 其他的图片还是在viewer里面展示，如果过剃除或者过滤掉 他就不知道这一组图片里面有 pdf了

**Comment by mirari** [comment]
这恐怕是没办法通过配置简单实现的。viewerjs插件本身已经高度封装了点击后弹出的这个图片浏览器，你的需求需要修改它内部的展现和切换动作，也许只能自己fork之后修改实现。

**Comment by mirari** [comment]
插件没有提供监听next按钮的方法，而且你光监听这个事件是不够的，还有prev，以及用户点击图片列表后直接跳转。你只能通过在options对象里传递`view`回调来执行你想要的动作。
文档：
[https://github.com/fengyuanchen/viewerjs#view](https://github.com/fengyuanchen/viewerjs#view)

**Comment by smileoneCXY** [comment]
万分感谢,关于其他文件格式我已经处理好了 ,  结果又遇到了其他问题  ,蒙层都出来了 图片却显示在了 父页面下面 不再蒙层上 呜呜

**Comment by mirari** [comment]
看看是不是有什么全局样式影响到了viewer.css里的样式

**Comment by smileoneCXY** [comment]
解决了 有几个需要注意的地方 1.如果是用组件 引入的话 inited 方法初始化图片数组动态变化 ，要是一开始在data里面给个 images:[] 则出不来图片，才用第二种方式2.使用 this.$el.querySelector 从dom元素初始化 viewer  但是要注意 如果 在这之前设置images数据源的话 dom都没渲染好 图片 则还是出不来 要要延迟加载一下 使得页面渲染好 iamges  再 调用 show

**Comment by mirari** [comment]
组件引入应该不会有这个问题，images每次变化都应该能看到变化后的效果，能提供一个详细的复现描述吗

**Comment by smileoneCXY** [comment]
可能我用法不对 我main.js配置好后 在自己的组件里 引入这个 组件 然后就一直是黑遮罩 因为imgs在data里面一开始给了[] 后面动态设置值 又不能 懒加载 初始化 viewer组件 导致加载不上来了 ┭┮﹏┭┮；
<viewer v-show="false"  @inited="inited"  class="viewer" ref="viewer">
      <img v-for="src in imgs" :src="src" :key="src">
    </viewer>
props:['imges']
data(){
return:{
  imgs:[],
}
}
methods:{
otherFunc(){
//其后每次点击父页面 传入值进来 改变 这个imgs = imges 
/*一系列的操作 设置了 imgs 动态变化 切割 赋值  等*/
this.showImgs();//调用show
}
 inited (viewer) { //初始化viewer
          this.$viewer = viewer
        },
        showImgs(){ //查看图片
          this.$viewer.show();
        },
}

**Comment by mirari** [comment]
懒加载有例子可以参考
https://codesandbox.io/s/relaxed-torvalds-jvv2y26ov9

**Comment by smileoneCXY** [comment]
哇 nice  感谢
