### ISSUE TITLE
Transfer images directly to v-viewer without pre-existing images

### ISSUE THREAD

**Issue by matamune94** [mirari/v-viewer#87]
this.$refs.viewer.$viewer.images = [array image]
this.$refs.viewer.$viewer.show()
and i have alert 
Uncaught TypeError: image.getAttribute is not a function
have idea please ?

**Comment by mirari** [comment]
You'd better not modify its properties directly.

Try to use it like this:
[https://codesandbox.io/s/relaxed-torvalds-jvv2y26ov9](https://codesandbox.io/s/relaxed-torvalds-jvv2y26ov9)

**Comment by matamune94** [comment]
@mirari  best answer thanks sir
