### ISSUE TITLE
iOS13无法捏合放大缩小！！！

### ISSUE THREAD

**Issue by Catlc** [mirari/v-viewer#88]

**Comment by mirari** [comment]
在原版DEMO里测试一下
[https://fengyuanchen.github.io/viewerjs/](https://fengyuanchen.github.io/viewerjs/)
如果有问题需要提供复现环境描述到[原项目issue](https://github.com/fengyuanchen/viewerjs/issues)

**Comment by Catlc** [comment]
这个测试没问题 怀疑是被盖住了 但是iOS12没问题

**Comment by mirari** [comment]
[https://codepen.io/mirari/pen/PePrVq](https://codepen.io/mirari/pen/PePrVq)
[https://mirari.github.io/v-viewer/](https://mirari.github.io/v-viewer/)
这两个例子页面有问题吗？实际上的viewer调用方式应该是一样的

**Comment by Catlc** [comment]
已解决！！！发现问题了打包的时候用的npm，开发的时候用的cnpm导入的
