### ISSUE TITLE
右上角的关闭按钮在iPhone X上无法点击！ 点击无效

### ISSUE THREAD

**Issue by Catlc** [mirari/v-viewer#91]

**Comment by mirari** [comment]
在原版DEMO里测试一下
[https://fengyuanchen.github.io/viewerjs/](https://fengyuanchen.github.io/viewerjs/)
如果有问题需要提供复现环境描述到[原项目issue](https://github.com/fengyuanchen/viewerjs/issues)

**Comment by 13615817501** [comment]
![image](https://user-images.githubusercontent.com/23720587/70019776-7d1cc700-15c5-11ea-8b9a-3ebf95c18461.png)
