### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by pengxAlone** [mirari/v-viewer#92]
图片预览的时候，如果是触摸屏，拖动图片经常会图片翻页，能不能给了属性控制触摸滑动翻页，自己可以加按钮翻页。 然后触摸屏翻页，经常会报错， ‘Uncaught TypeError: Cannot read property 'endX' of undefined’

**Comment by mirari** [comment]
以前这个项目不是为移动端设计的，移动端多少都会有点问题。
这个问题可能得提交到viewer.js的issue](https://github.com/fengyuanchen/viewerjs/issues)。
