### ISSUE TITLE
层级问题

### ISSUE THREAD

**Issue by TankRyze** [mirari/v-viewer#93]
我的业务是这样的，对话框里面有图片，点击图片有预览效果，
对话框是element的对话框组件，图片预览是使用的您的这个组件
但是当我点开图片的时候，图片预览的组件比对话框的组件层级低
[导致图片出现在了对话框的后面
![WechatIMG82](https://user-images.githubusercontent.com/22748893/68592231-7ff83080-04cd-11ea-8242-7c72e445b320.png)

**Comment by TankRyze** [comment]
我这样配置解决了问题，是他的层级是9999
我之前这样配置，层级9999并没有生效
`Vue.use(Viewer);
Viewer.setDefaults({
    Options: {
        "zIndex": 9999,
        "inline": false,
        "button": true,
        "navbar": true,
        "title": false,
        "toolbar": true,
        "tooltip": false,
        "movable": true,
        "zoomable": false,
        "rotatable": true,
        "scalable": false,
        "transition": true,
        " fullscreen": false,
        " keyboard": false
    }
})
`
后来改成这样配置
`Vue.use(Viewer,{
  defaultOptions: {
    zIndex: 9999
  }
});`
层级生效
可以解决问题

**Comment by mirari** [comment]
setDefault的写法错了，里面直接传配置项对象，没有`Options`这样的包裹属性
`
Vue.use(Viewer, {
  defaultOptions: {
    zIndex: 9999
  }
})
`
