### ISSUE TITLE
Viewer is not opening after first time

### ISSUE THREAD

**Issue by marufmax** [mirari/v-viewer#94]
I have a array of images which contains another array of images. I want to show them in a table

After first click viewer instance is opening perfectly but second click viewer is opening. 

Here is my code: [https://codesandbox.io/s/v-viewer-b9qd1](https://codesandbox.io/s/v-viewer-b9qd1)

**Comment by mirari** [comment]
[https://codesandbox.io/s/v-viewer-hc87y](https://codesandbox.io/s/v-viewer-hc87y)

You do not need to create `viewer` repeatedly, create one and call `show` with different arrays of images.
And the second argument `index` should not exceed the length of the array.

**Comment by marufmax** [comment]
if you click twitch of same image, it won't open

**Comment by mirari** [comment]
[https://codesandbox.io/s/v-viewer-zhezr](https://codesandbox.io/s/v-viewer-zhezr)

`images` should be a new array everytime, try again.
