### ISSUE TITLE
How to listen to events?

### ISSUE THREAD

**Issue by flyingL123** [mirari/v-viewer#97]
How can I listen for events from the underlying viewer.js? For example, if I want to know when the [`view`](https://github.com/fengyuanchen/viewerjs#view-1) even takes place, is this possible?

**Comment by flyingL123** [comment]
It looks like using `.native` works.

```
<viewer
	v-if="images.length"
	:images="images"
	:options="photoGalleryOptions"
	class="viewer"
	ref="viewer"
	@inited="photoGalleryInited"
	@view.native="onPhotoGalleryView"
>
```

Is that the intended way to do it?

**Comment by mirari** [comment]
Yes, and an other way is to configure `options`:
```
options: {
  view: this.onPhotoGalleryView
}
```
