### ISSUE TITLE
Improve swipe user experience

### ISSUE THREAD

**Issue by flyingL123** [mirari/v-viewer#98]
Have you considered improving the experience of swiping to navigate between images? Currently the image doesn’t change until after the swipe motion is complete. 

In other libraries I have seen the swipe more closely mimics how the native swiping works on the phone. For example the image will start to move and follow your finger as the swipe starts, and then eventually shoot off the screen for the next image to enter. 

I think that would be a nice improvement. Just wanted to ask and see what you thought. 

Thanks for this great package!

**Comment by mirari** [comment]
`viewer.js` was not specifically designed for mobile before, you can make a issue to [viewer.js](https://github.com/fengyuanchen/viewerjs/issues).
`v-viewer` is just an adapter on `vue`.
