### ISSUE TITLE
How to handle when an image is unavailable?

### ISSUE THREAD

**Issue by flyingL123** [mirari/v-viewer#99]
I am finding then if my gallery a single image that is unavailable (due to 403 or 404 error when the browser attempts to load it), the entire viewer will not function.

Is this intentional? Is there a way to handle these errors gracefully so the viewer will still work for the other images?

I am using viewer with the inline option and it simply never appears if there is an error loading one out of 200 images.

**Comment by mirari** [comment]
Sorry I just noticed this problem, it should be a bug, and the author of `viewerjs` will fix it later.
[https://github.com/fengyuanchen/viewerjs/issues/325](https://github.com/fengyuanchen/viewerjs/issues/325)

**Comment by mukeshghodela-easternts** [comment]
@mirari : Any update on this?

**Comment by mirari** [comment]
> @mirari : Any update on this issue?

I just noticed that this problem still exists, and I have already reported it to the author.

https://codepen.io/mirari/pen/yLVrpNd
It's not work in the inline mode, but the modal mode is ok,  Is it the same as you?

**Comment by mukeshghodela-easternts** [comment]
@mirari No, In my case loader is showing when the image is unavailable or invalid image path.

**Comment by mirari** [comment]
> @mirari No, In my case loader is showing when the image is unavailable or invalid image path.

Could you reproduce it with codepen? 
You can refer to existing examples:
[directive](https://codepen.io/mirari/pen/PePrVq)
[component](https://codepen.io/mirari/pen/PowNyEY)

**Comment by mukeshghodela-easternts** [comment]
@mirari https://codepen.io/mukesh9999/pen/jOVodQV : I put wrong path

**Comment by mirari** [comment]
@mukeshghodela-easternts 
I did not find the problem, do you mean that you don’t want to show the viewer when the image fails to load?
In that case, it is another problem. Maybe you can modify its properties when the image fails to load, and then exclude it in the filter.

**Comment by mukeshghodela-easternts** [comment]
@mirari Thanks
